### ISSUE TITLE
converts single number semvers to a pinned version

### ISSUE THREAD

**Issue by jonathanong** [greenkeeperio/greenkeeper#103]
ex. i had `"bluebird": "2"`. it updated it to `"bluebird": "3.1.1"` when i want it as semver major like `"bluebird": "^3.1.1"`

**Comment by boennemann** [comment]
This is a bug, thanks for the report.

**Comment by finnp** [comment]
Closing this as a duplicate of  https://github.com/greenkeeperio/greenkeeper/issues/64
