### ISSUE TITLE
Nothing happens after initial PR has merged

### ISSUE THREAD

**Issue by takuyahara** [greenkeeperio/greenkeeper#1033]
I'm new to greenkeeper and verifying how it works. Oddly, after merging initial PR greenkeeper seems not working. I added some packages which is not up-to-date and tried pushing and PRing (in which one of their timing greenkeeper runs?), I expect that greenkeeper creates new PR but it doesn't. I also tried resetting but result never changes; initial PR can be merged without any problem but later greenkeeper does nothing. Do I lack any step?

**Comment by janl** [comment]
@takuyahara sorry for the late reply here. For timely support, please use support@greenkeeper.io

We are currently looking into this and I’ll update this issue once we know more.

**Comment by janl** [comment]
Heya @takuyahara: a fix has been deployed and things should be back to normal. If you still see any issue, please use the support email address and send us your affected repo name. ✌️
