### ISSUE TITLE
when you add a collaborator to an npm package, greenkeeper treats it like a new version was released

### ISSUE THREAD

**Issue by jonathanong** [greenkeeperio/greenkeeper#104]
i.e. it will trigger check dependencies on all its dependents.

i'm not sure if this is a bug or a feature.

**Comment by boennemann** [comment]
Hey @jonathanong,

could you elaborate on how you noticed this?

Greenkeeper listens for updates on packages via npm's changes feed: https://skimdb.npmjs.com/registry
This feed contains events for new versions, but also for new collaborators or stars. This is something that results in more load for our servers, but it shouldn't surface.

The one scenario that I can think of is this:

Your repo depends on package `xyz: ^1.0.0`, while 1.0.1 is latest. You enable Greenkeeper. xyz adds someone as contributor. You get a branch/test run with 1.0.1.

Is that what happened and if so how is it affecting you in a bad way?

Thanks,
Stephan

**Comment by boennemann** [comment]
Happy to reopen, once answered.
