### ISSUE TITLE
Filter dependency that requires constant update monitoring

### ISSUE THREAD

**Issue by inikulin** [greenkeeperio/greenkeeper#107]
Hello, guys.

Thank you for the great project! 

Is there anyway to tell greenkeeper to issue PRs only for the particular dependencies. E.g. my project has a lot of deps and in general I would like to stick with their existing versions. However, there are some dependencies that I would like to keep always fresh.

Thanks in advance.

**Comment by boennemann** [comment]
Hey @inikulin,

I'm describing the the ignore functionality in this comment: https://github.com/greenkeeperio/greenkeeper/issues/47#issuecomment-146474309

Thanks for your feedback.

Best,
Stephan

**Comment by inikulin** [comment]
Awesome, thank you!
