### ISSUE TITLE
Alternative package managers

### ISSUE THREAD

**Issue by ad-m** [greenkeeperio/greenkeeper#1078]
Are there any plans to support other package managers, e.g. pip? I would like to use the potential of lossly pinned dependencies in the world of Python. 

As I know in Python world there is no greeenkeeper alternative which pin dependencies by pull request only when required. There is a few hard-pinned manager eg. [pyup](https://pyup.io/), [renovate](https://renovatebot.com/), [requires.io](https://requires.io/). It doesn't fill for each use case eg. apache/airflow#5031 .

I would like notice that Renovate have abstracted logic of managers ( https://github.com/renovatebot/renovate/tree/master/lib/manager ). I hope it has the potential to be re-used.

**Comment by janl** [comment]
Hi @ad-m, thank you for your vote of confidence.

We currently have no plans to branch out into other ecosystems and make sure we solve the JS case the best way we can.

We periodically review this decision however and I’m taking your post here as a point towards a yes ;)
