### ISSUE TITLE
Greenkeeper not honoring pinned dependencies

### ISSUE THREAD

**Issue by drazisil** [greenkeeperio/greenkeeper#1087]
This feels like a bug. I have `@types/node` pinned to an exact version and Greenkeeper keeps trying to update it.

See this PR: https://github.com/drazisil/mco-server/pull/174

Config: https://github.com/drazisil/mco-server/blob/master/package.json#L68

I have this pinned to an exact version because any changes cause my tests to fail. Is there any way to get Greenkeeper to stop trying?

**Comment by travi** [comment]
from the [docs about pinning](https://greenkeeper.io/docs.html#pinning), this is expected behavior:

> Once you’ve pinned a package, every subsequent update to it will be considered out-of-range by Greenkeeper.

it sounds like you are looking to [ignore updates for that dependency](https://greenkeeper.io/docs.html#ignoring-dependencies)

**Comment by drazisil** [comment]
Yes, thank you.
