### ISSUE TITLE
yarn.lock is not being updated

### ISSUE THREAD

**Issue by limonte** [greenkeeperio/greenkeeper#1118]
Example: https://github.com/sweetalert2/sweetalert2/pull/1664

### Actual behavior

Only `package.json` is updated

### Expected behavior

Both `package.json` and `yarn.lock` are updated

**Comment by limonte** [comment]
another example https://github.com/sweetalert2/sweetalert2/pull/1670

**Comment by EvHaus** [comment]
Same problem for me as well. https://github.com/GlobexDesignsInc/eslint-config-globex/pull/2/files

**Comment by Siggnja** [comment]
Is there anyone looking into this? We are experiencing the same issue.

**Comment by janl** [comment]
Hey all, thanks for all your patience. We’ve deployed a fix for this earlier today that should cover most of the reasons for this issue. If any of you still see this, please send let us know.

**Comment by EvHaus** [comment]
Greenkeeper just opened this PR but didn't include a `yarn.lock` update: https://github.com/GlobexDesignsInc/magna.gg/pull/22/files

**Comment by nojaf** [comment]
Same here, https://github.com/nojaf/fable-reactstrap/pull/12/files

**Comment by janl** [comment]
Thanks, we’ll investigate

**Comment by Siggnja** [comment]
Same for us.

**Comment by janl** [comment]
Thanks for your patience, another fix just went live. Leaving this open until confirmed fixed.

**Comment by nojaf** [comment]
Looks ok here, https://github.com/nojaf/fable-reactstrap/pull/14/files

**Comment by janl** [comment]
Closing this now after no further reports have come in. Feel free to open if this comes up again.
