### ISSUE TITLE
Is it possible that greenkeeper makes changes in the fork rather than in the branch in the same repo?

### ISSUE THREAD

**Issue by epoberezkin** [greenkeeperio/greenkeeper#118]

**Comment by janl** [comment]
Heya @epoberezkin! Thanks for the question.

Greenkeeper doesn’t fork for architectural reasons, so we need to do it on your repo.

What is the problem you are trying to solve? Maybe we can find another solution.

**Comment by epoberezkin** [comment]
I had build badge showing failures in all branches... Now I can't, had to switch back to showing master only

**Comment by janl** [comment]
> I had build badge showing failures in all branches... Now I can't, had to switch back to showing master only.

Is it possible to show a badge just for your “release” branches? I’d assume that feature branches are expected  to at least temporarily break the build?

> Github complains if you fork everything?

Something like that :)

**Comment by epoberezkin** [comment]
> Is it possible to show a badge just for your “release” branches?

That's what I had to do. It can only show status for one branch though (or for all).

Forking would be cleaner in any case. As is I have to also remove those branches after they are merged...

**Comment by janl** [comment]
>  As is I have to also remove those branches after they are merged...

We have a solution coming up for this.

Forking is not an option for us any time soon, sorry!
