### ISSUE TITLE
Greenkeeper does not create pull requests

### ISSUE THREAD

**Issue by ayrton** [greenkeeperio/greenkeeper#119]
Hey

Collaborator on [chai-enzyme](https://github.com/producthunt/chai-enzyme) here, I've been using greenkeeper for the first time and I  think I've successfully set it up for the mentioned repository.

I've noticed greenkeeper is creating branches and that the branches are green, but it does not create any pull requests yet. Is there something misconfigured or something I can do about this?

**Comment by boennemann** [comment]
Hey @ayrton,

thanks for your feedback. You haven't configured anything wrong, and Greenkeeper is working as expected.

> ### I enabled a repo, but nothing’s happening / Deleted branches

> This might be because the dependency updates are within your specified ranges, and not breaking your tests. So there’s no point in bothering you with a PR, since everything still works.

> You’ll only receive pull requests when an in-range dependency breaks your build, or when a dependency updates outside your specified range.


I updated our FAQ and made them more visible on our website.

Thanks,
Stephan

**Comment by ayrton** [comment]
Thanks for the clarification!

**Comment by pguth** [comment]
Will Greenkeeper also remove the branches at some point?
