### ISSUE TITLE
if a new version of a package is released and the tests pass, delete old branches/PR of that package

### ISSUE THREAD

**Issue by jonathanong** [greenkeeperio/greenkeeper#120]
so i don't end up with 1000 PRs for the same module

**Comment by boennemann** [comment]
We started to roll out our auto-closing feature. Details: https://github.com/greenkeeperio/greenkeeper/issues/62#issuecomment-176248343

**Comment by jonathanong** [comment]
:+1:

**Comment by jonathanong** [comment]
Not seeing this working for me. I still see multiple PRs

**Comment by boennemann** [comment]
We're closing the other PRs once you have merged the first one. I've explained why we're doing it like this in detail in the linked issue ;)
