### ISSUE TITLE
'Couldn’t enable a project with this slug.' on brand new repo

### ISSUE THREAD

**Issue by charlespeters** [greenkeeperio/greenkeeper#122]
tried setting up greenkeeper on a new repo https://github.com/charlespeters/athanor

```
🌴  info enable The GitHub slug is: charlespeters/athanor
🌴  ERR! enable Couldn’t enable a project with this slug.
🌴  ERR! enable If you want to try your free private repo make sure to grant the necessary rights by running $ greenkeeper login --force --private
🌴  ERR! enable You have to have a plan for more than one private repo. To verify run $ greenkeeper whoami
🌴  ERR! enable If you have just recently created this repo try running $ greenkeeper sync
🌴  ERR! enable You need admin access to a repo to enable it.
🌴  ERR! enable If you think this error really shouldn’t appear let us look into it with $ greenkeeper support
```

used `greenkeeper --slug=charlespeters/athanor enable` & `greenkeeper enable`, same error.

**Comment by janl** [comment]
Heya @charlespeters (Great to see Black Pixel folk use Greenkeeper! :)

Can you try running `greenkeeper sync`, it looks like your repo is fairly new.

On to of that, GitHub had major connectivity issues, so that might have had something to do with this: https://status.github.com

**Comment by boennemann** [comment]
Hey @charlespeters,

sorry for the issues. The solution posted above should work™. I'll close this now, as we're tracking a better UX around this in this issue: https://github.com/greenkeeperio/greenkeeper/issues/113

If this problems persists please let us know here and we'll reopen immediately.

Best,
Stephan

**Comment by charlespeters** [comment]
working great now, thanks @janl @boennemann!
