### ISSUE TITLE
Minimal diff for package.json updates

### ISSUE THREAD

**Issue by qfox** [greenkeeperio/greenkeeper#123]
I see PR's from greenkeeper that remove whitespace "formatting" from the package.json.

## Expected behavior:

If a version bump is suggested, the PR should affect only one line, and basically only the version string on that line.

## Actual behavior:

Whitespace is removed, structures are "beautified" according to some preference/styleguide that isn't mine/ours.

**Comment by janl** [comment]
Heya, thanks for the report! Can you show us a link to the PR?

**Comment by qfox** [comment]
I updated and squashed the one in question, but here's an old one that wasn't pulled;

https://github.com/the-grid/finitedomain/pull/31/files

**Comment by qfox** [comment]
And for reference, this is what I'd expect;

https://github.com/the-grid/finitedomain/pull/47/files

**Comment by boennemann** [comment]
For reference: We're currently using this package to do the updates https://github.com/boennemann/json-preserve-indent

If anyone wants to improve our behaviour on their own a PR to that package is highly appreciated.
We are also considering switching to a RegEx based option, but would ideally would want to avoid it.

There is a package that already does what we want, except for it's broken: https://github.com/substack/jsup

Thanks,
Stephan

**Comment by boennemann** [comment]
This is fixed, as we're now using https://github.com/finnp/json-in-place in the worker.
Thanks y'all.

**Comment by gdi2290** [comment]
thanks!
