### ISSUE TITLE
When version range uses > (greater than), pull request is for invalid version

### ISSUE THREAD

**Issue by bdukes** [greenkeeperio/greenkeeper#124]
I have a project which specifies a dependency with the version range `>0.1.20` (because there was a bug in 0.1.20 that was fixes in 0.1.21).  When version 0.1.22 came out, I received a pull request (https://github.com/bdukes/grunt-xmlpoke/pull/20) which updated the version range to `>0.1.22`, which doesn't exist (hence, the tests failed).

**Comment by boennemann** [comment]
Hey @bdukes,

thanks for catching this. This is fixed in our pull-request job and will be deployed now.
This won't happen from now on.

Best,
Stephan

**Comment by bdukes** [comment]
:+1: thanks!
