### ISSUE TITLE
No easy way to test greenkeeper on a repo

### ISSUE THREAD

**Issue by kumar303** [greenkeeperio/greenkeeper#125]
It would be nice to have an easy way to test greenkeeper when setting up a new repo or making administrative changes. 

For example, I set it up with the wrong origin the first time and after I fixed it, I couldn't figure out how to trigger a pull request. I tried decrementing a dependency in my package.json (it was a node project) and committing to master but no pull request was issued for an upgrade. I assume this is because of caching (greenkeeper had already made a fix on the wrong origin). One way to allow for easy testing would be to support making pull requests for decremented dependencies. Maybe there is a more straight forward way though.

**Comment by leo** [comment]
@kumar303 I don't think that greenkeeper get's "triggered". As far as I know, it simply checks for updates of your dependencies every x minutes/hours after it was enabled.

Therefore it's not possible "trigger" a PR.

**Comment by boennemann** [comment]
Hey @kumar303,

@leo is right, Greenkeeper PRs aren't triggered by actions in your repository, but by the dependencies being updated. If you manually downgrade a dependency you won't receive a branch/PR until the next time the dependency updates.

If you want to check whether things are up and running you can always do `greenkeeper info`.

To make sure Greenkeeper uses the correct repository you can do `greenkeeper sync` and then `greenkeeper` enable again.

Best,
Stephan

**Comment by kumar303** [comment]
Thanks for all the clarifications
