### ISSUE TITLE
How to ignore dependencies?

### ISSUE THREAD

**Issue by ErisDS** [greenkeeperio/greenkeeper#132]
Hi there! I've been [excited to try out greenkeeper](https://github.com/TryGhost/Ghost/issues/6452). 

I found [this issue](https://github.com/greenkeeperio/greenkeeper/issues/47#issuecomment-146474309) which described a feature to ignore dependencies by adding a `greenkeeper: {ignore: []}` array to the package.json, which I have done [here](https://github.com/TryGhost/Ghost/blob/master/package.json#L105).

But the first thing greenkeeper did was try to update all of our dependencies: https://github.com/TryGhost/Ghost/pull/6460/files

Most of these are deliberately pinned for reasons tracked elsewhere in the repo.

Is there another way to ignore certain dependencies?

**Comment by christophwitzko** [comment]
Hi @ErisDS,

thank you for giving Greenkeeper a try.
At the moment `greenkeeper.ignore` does not work for the `update-all` pull request.
This is clearly a bug, thanks for reporting.

Have a great day,
Christoph

**Comment by christophwitzko** [comment]
This should be fixed now. Just run `greenkeeper disable --slug TryGhost/Ghost` and `greenkeeper enable --slug TryGhost/Ghost` to get a new `update-all` pull request.

**Comment by ErisDS** [comment]
That's super cool, and super quick thanks :tada: 

However, with #133 also causing us a problem, I'm not quite ready to turn greenkeeper back on yet :wink:
