### ISSUE TITLE
Greenkeeper tries to update to prerelease (non stable) versions.

### ISSUE THREAD

**Issue by ErisDS** [greenkeeperio/greenkeeper#133]
This is another issue I noticed from the [initial PR](https://github.com/TryGhost/Ghost/pull/6460/files) that greenkeeper.io sent to Ghost.

Amongst our dependencies, there are two which have pre-releases / release candidates: [cookie-session](https://github.com/TryGhost/Ghost/pull/6460/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R39) and [knex](https://github.com/TryGhost/Ghost/pull/6460/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R51).

![](http://puu.sh/n7piM.png)

Cookie-session has an alpha build `2.0.0-alpha.1`, knex has an RC1 `0.10.0-rc1` - both of these are using the correct semver notation for [prereleases](http://semver.org/#spec-item-9) and neither of these are intended for use in production.

I don't think that trying to push a codebase onto prereleases, i.e. code that has been specifically designated not yet ready for a main release, fits greenkeeper's MO of helping to  "ship up-to-date, stable software"?

On [david-dm](https://david-dm.org/tryghost/ghost#info=dependencies&view=table) there is a difference between "lastest" and "stable" which I think would also be useful in greenkeeper.

**Comment by ErisDS** [comment]
I've updated this issue with more info as I realised it might not have been clear.

**Comment by janl** [comment]
@ErisDS just a quick heads-up: this does look wrong and we are looking into it. I definitely agree that pre-release versions should not make it into production unless explicitly selected.

**Comment by ErisDS** [comment]
Excellent news, thanks for letting me know :+1:

**Comment by donny-dont** [comment]
We're hitting this same issue with our GHE install @janl any idea when it'll be resolved?

**Comment by finnp** [comment]
@donny-dont We're going to release a fix for this soon. We'll keep you updated here.

**Comment by janl** [comment]
Thank you for your patience everyone! We have now deployed a fix for this.

**Comment by ErisDS** [comment]
OMG OMG OMG 💃

**Comment by donny-dont** [comment]
@janl when is this going to hit the enterprise version? We're not seeing an updated version. Ours still says 1.0.0

**Comment by janl** [comment]
@donny-dont very soon, monday the latest.

**Comment by ErisDS** [comment]
Hey, I've tried re-enabling greenkeeper twice this evening. A [branch](https://github.com/TryGhost/Ghost/tree/greenkeeper-update-all) gets created (and this bug is definitely fixed, huzzahh!) but no PR gets raised, is this expected?

**Comment by janl** [comment]
@donny-dont the Enterprise release is up now.

**Comment by janl** [comment]
@ErisDS the update happened during an aslant update and thus was a little delayed. It should be this one: https://github.com/TryGhost/Ghost/pull/6776

**Comment by janl** [comment]
@ErisDS sorry, the background is that we have a queueing system that is busy when packages that a lot of other packages depend on get updated..

**Comment by ErisDS** [comment]
No prob, I saw it pop up a bit later on and realised I was being impatient. I obviously got lucky the first time I used greenkeeper 😁

**Comment by zkiiito** [comment]
well, I got an alpha update PR 2 weeks ago: https://github.com/zkiiito/SURF/pull/5

**Comment by wopian** [comment]
[express](https://github.com/expressjs/express/releases) released a stable 4.15.2 at the same time as its 5.0.0-alpha.5 pre-release.

Greenkeeper [opened](https://github.com/wopian/hibari/pull/87) a PR for the alpha pre-release

**Comment by xPaw** [comment]
@wopian same problem here.

https://github.com/thelounge/lounge/pull/948
https://github.com/thelounge/lounge/pull/942
