### ISSUE TITLE
Unable to enable private repo

### ISSUE THREAD

**Issue by michaelcontento** [greenkeeperio/greenkeeper#136]
> $ gk enable --slug michaelcontento/avalon
> 🌴  info enable The GitHub slug is: michaelcontento/avalon
> 🌴  ERR! enable Couldn’t enable a project with this slug.
> 🌴  ERR! enable The repo has to exist on GitHub and it has to be public,
> 🌴  ERR! enable or you have to have a private plan. To verify run $ greenkeeper whoami
> 🌴  ERR! enable If you have just recently created this repo try running $ greenkeeper sync
> 🌴  ERR! enable You need admin access to enable repos.
> 🌴  ERR! enable If you think this error really shouldn’t appear let us look into it with $ greenkeeper support

I've tried to figure out if there is another private repo blocking the *"1 private repo is free"-slot* with `$ gk list` but there is none. Is there a better way to see who is blocking the free slot? 

**Note:** I already tried `$ gk login --force`, `$ gk sync` and completely revoke GK from my account. Nothing seems to work :disappointed:  

Thanks in advance and let me know if there is something I can support you with! :tada:

**Comment by christophwitzko** [comment]
Hi @michaelcontento,

you need to grant Greenkeeper access to your private repositories with `greenkeeper login --force --private`.

Have a great day,
Christoph

**Comment by michaelcontento** [comment]
Hi @christophwitzko,

yes, thank you. I saw it a few seconds ago by myself after a upgrade to the latest version of GK with the improved error message :joy: 

Thanks a lot :tada:
