### ISSUE TITLE
Automatic (or triggered) rebases

### ISSUE THREAD

**Issue by hughrawlinson** [greenkeeperio/greenkeeper#137]
If you get a PR from gk, and you let it wait for a while, and it becomes unmergeable, it'd be really really awesome if you could ask gk to rebase the commit onto the current master to make it mergeable again. In the case of the kinds of commits gk makes, this would usually solve an unmergeable commit, right?

If not, having gk just remake the PR would be great.

**Comment by jonathanong** [comment]
:+1: especially when `react` and `react-dom` are both updated and i can't merge both sequentially because merging one creates a merge conflict on the other

**Comment by boennemann** [comment]
Thanks for your feedback,

this is a great idea and it's on our roadmap, but I can't yet give you any date on it.
I'll keep you posted here.

Best,
Stephan

**Comment by boennemann** [comment]
Hey y'all,

happy to tell you that this landed. Whenever you merge a Greenkeeper PR we'll automatically reapply the other open PRs against the latest changes of the base branch. This way there isn't even any interaction required. We're automatically testing all other PRs and make them merge-able again.

Best,
Stephan

**Comment by YaManicKill** [comment]
> Whenever you merge a Greenkeeper PR we'll automatically reapply the other open PRs against the latest changes of the base branch.

So, does this only rebase when you merge a Greenkeeper PR, or does it do it if you merge a PR from someone else?

**Comment by jbcpollak** [comment]
Is this enabled by default? I haven't seen this happen - am I just not being patient enough?

**Comment by mbrevda** [comment]
Is this live? I don't see the [GK branch](https://github.com/mbrevda/react-img-multi/pull/24
) being rebased?
