### ISSUE TITLE
make greenkeeper less spammy

### ISSUE THREAD

**Issue by jonathanong** [greenkeeperio/greenkeeper#138]
i've tried to enable greenkeeper on a lot of shared projects, but people end up complaining about it. this is an issue for various ideas for making greenkeeper seem less spammy. making it less spammy will improve UX and increase usage. by spam, people (usually) mean github notifications when opening PRs. people aren't really bothered by new branches being created since that doesn't create notifications.

some ideas i just thought of:

- update a PR instead of creating new PRs when new versions are created. prone to error obviously if tests pass on one but not another. maybe only if the tests failed?
  - is there a way in the GitHub API to change a branch of a PR?
- https://github.com/greenkeeperio/greenkeeper/issues/62 if a PR is created for a newer version and the tests pass, close all the other ones
- debounce updates. ex. many modules create 5 versions within a span of a few hours. i don't mind debouncing updates for a day. better than having 5 PRs.

**Comment by rom1504** [comment]
:+1: 
I'd like to avoid that kind of thing https://github.com/PrismarineJS/mineflayer/pull/376 https://github.com/PrismarineJS/mineflayer/pull/377 https://github.com/PrismarineJS/mineflayer/pull/378 https://github.com/PrismarineJS/mineflayer/pull/379 https://github.com/PrismarineJS/mineflayer/pull/380

**Comment by boennemann** [comment]
Thanks for your feature requests,

we won't implement PR updating, preemptive auto-closing or any other kind of automated decision making for the reasons laid out [here](https://github.com/greenkeeperio/greenkeeper/issues/62#issuecomment-155127718).

The amount of "noise" Greenkeeper creates is the number one complaint we get about the experience and we are very hard at work to develop ways to handle this, **without** compromising on the philosophy of the product: 

> Greenkeeper wants to automate chores, it doesn't want to take decisions or responsibility. Greenkeeper is designed to maximally reduce friction. Ideally all that's left for humans to do, is to take said decisions and responsibility, without the repetitive work involved. That's ultimately what we're good at.

[Auto-closing PRs after a merge has happened](https://github.com/greenkeeperio/greenkeeper/issues/62) was only our first feature specifically designed to address this, but there are more ideas and approaches we're discussing and we hope we can launch more soon.

Thanks for using Greenkeeper and pushing us to improve the experience.

Best,
Stephan

**Comment by rom1504** [comment]
Is there a single case where having 2 PRs opens for 2 upgrade of the same dependency is useful ?

**Comment by rovolution** [comment]
for whats it worth, running into an issue where my CI server is constantly queuing up builds b/c of all the PRs coming from greenkeeper. I really like the idea of having some sort of config where it only makes a single PR in a 24 hr period with all the newest version of compatible deps
