### ISSUE TITLE
Enabling green keeper on private repo

### ISSUE THREAD

**Issue by ohemmi** [greenkeeperio/greenkeeper#141]
I'm a member of an organization that has paid for a greenkeeper subscription, when I attempt to enable on a private repo I get 
```
ERR! enable Couldn’t enable a repository with this slug.
```
greenkeeper whoami shows the private organization. any suggestions?

**Comment by janl** [comment]
Heya @ohemmi!

Can you try running `greenkeeper login --force --private`?

Thanks!

**Comment by ohemmi** [comment]
That seems to have enabled it thank you!

**Comment by janl** [comment]
Great! Thank you for using Greenkeeper! :)
