### ISSUE TITLE
greenkeeper login tries to open two tabs

### ISSUE THREAD

**Issue by steveklabnik** [greenkeeperio/greenkeeper#143]
When running 'greenkeeper login' just now, it attempted to open two tabs: one with the url "https" and the other with an escaped version of the rest of the URL.

**Comment by steveklabnik** [comment]
... it looks like this may actually be a bug in `open`, not greenkeeper itself.

**Comment by steveklabnik** [comment]
.... and it looks like `open` is basically unmaintained, so it's not likely to actually get fixed.

Anyway, I'll leave this open just in case, but feel free to close if this is one of those things that's just gonna be a thing. It's easy enough to work around.

**Comment by boennemann** [comment]
Hey @steveklabnik,

happy to see you're giving Greenkeeper a try.

As far as I can tell there are three modules out there to open things: "open", "opn", and "opener".
"open" appears to have quite a few problems, so swapping that out sounds like a good idea anyway.
Unfortunately "opn" prevents the process from exiting so it doesn't really improve things. It looks like "opener" works well though – can you confirm this on your machine?

If things are working on your side I'm happy to release a new version with the new module.

Best,
Stephan

**Comment by steveklabnik** [comment]
It does, I just opened a PR. Thanks! :smile:
