### ISSUE TITLE
Version range not respected?

### ISSUE THREAD

**Issue by JaKXz** [greenkeeperio/greenkeeper#145]
If you look at the [diff on this PR](https://github.com/rangle/angular2-redux-starter/pull/46/files), I think that the given package update is within our specified range (because the caret `^` should allow minor versions). The generated PR says that it's "not covered by [my] current version range", so am I wrong?

**Comment by boennemann** [comment]
Hey @JaKXz,

the caret operator automatically gives you minor and patch updates for all versions above 1.0.0.
For 0.1.0 etc you'll only get patch updates and for 0.0.1 it's essentially no range at all, just pinned.

Quoting from the [npm docs](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) (yes the first part is a bit confusing ;)).

> Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

So the PR was not sent by error.
Thanks so much for using Greenkeeper and sending us feedback.

Best,
Stephan

**Comment by andrenarchy** [comment]
@boennemann Thanks for clarifying this! I was wondering about masses of greenkeeper mails in my inbox in the last days. It's a bit spammy when package devs do not know about this rule and publish `0.x.x`-versioned packages with the `>=1.x.x` semantics (like I did :smile:). But it's probably not something you can fix – it sounds very reasonable to be compliant with the npm specs :grinning:.

Thanks for building greenkeeper!

**Comment by andrenarchy** [comment]
Now we received a [greenkeeper PR](https://github.com/paperhive/paperhive-frontend/pull/381/files) for upgrading `^0.7.5` to `^0.7.7`. 

@boennemann Do you agree that this should not happen? If so: do you want to reopen this issue?

**Comment by JaKXz** [comment]
@andrenarchy @boennemann that's a good catch actually, we're seeing similar issues - getting every `0.0.x` patch labelled as "not covered in our version range".

**Comment by nschloe** [comment]
How about reopening this?

**Comment by janl** [comment]
See #152 for a related issue.
