### ISSUE TITLE
Include more information in gk info command

### ISSUE THREAD

**Issue by donny-dont** [greenkeeperio/greenkeeper#150]
Currently the `gk info` command just returns whether the repository is enabled or disabled. It would be great to include more information such as whether the repository was found to be up to date or if there were some tasks pending. Currently there's no insight into what greenkeeper is doing so its hard to determine if the setup was successful.

**Comment by boennemann** [comment]
Hey @donny-dont,

you're right the info command should contain more information.
The API currently supports listing all PRs that got sent, but that didn't land in the CLI yet.

As a short-term fix you can talk to the API directly:

```
https://gke.my-domain.net/packages/myuser/myrepo?access_token=<token>&include_prs=true
```

The token can be found in `~/.greenkeeperrc`.

As a Enterprise customer you can look into the job queue to see failed jobs directly by clicking the "Open" link on your dashboard.

<img width="469" alt="screen shot 2016-03-10 at 20 54 20" src="https://cloud.githubusercontent.com/assets/908178/13682633/e9d6986c-e702-11e5-80e2-c169082843d3.png">


Best,
Stephan

**Comment by donny-dont** [comment]
@christophwitzko awesome work! This something that requires an enterprise update or is it all in the cli?

**Comment by christophwitzko** [comment]
Hi @donny-dont, this requires an upgrade of the Greenkeeper Enterprise API.
We will release this update in the next few weeks with a bunch of other features.
Thank you for your patience.
Best,
Christoph
