### ISSUE TITLE
Greenkeeper thinks tilde range covers minor version

### ISSUE THREAD

**Issue by SimenB** [greenkeeperio/greenkeeper#152]
Tilde only covers patch versions.

SimenB/wait-until-promise#6

![image](https://cloud.githubusercontent.com/assets/1404810/13722254/5834a366-e83f-11e5-9f8d-8d5f8ba6f1a5.png)

![image](https://cloud.githubusercontent.com/assets/1404810/13722256/606cf9e8-e83f-11e5-8be9-0f50c66cefc7.png)

**Comment by ljharb** [comment]
and `^` should cover patch versions: https://github.com/ljharb/object.assign/pull/28

**Comment by boennemann** [comment]
Hey @SimenB, @ljharb, @blakeembrey, @andrenarchy, @JaKXz, @nschloe,

thanks again for reporting this issue.

We have identified the issue. There were some problems in properly syncing up the package.json contents, so that the pull requests were based on outdated package.json content.

**Comment by boennemann** [comment]
Sorry I accidentally hit the close and comment button too early.

So continuing:

We are now getting all you package.json files back in sync. We installed checks to make sure this won't happen again. On top of that we have additional monitoring for this issue now.

Thanks for your patience and using Greenkeeper.

Best,
Stephan
