### ISSUE TITLE
Possibly add 24h delay

### ISSUE THREAD

**Issue by nkbt** [greenkeeperio/greenkeeper#157]
http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

Since NPM has introduced the policy of 24 hours for 'unpublish' it might be worth delaying update notifications by that time. 

Possibly as opt-in

**Comment by boennemann** [comment]
Thanks for your suggestions @nkbt!

As explained [here](https://github.com/greenkeeperio/greenkeeper/issues/156#issuecomment-204062483) this isn't what we would want to do for now.

If this problem becomes apparent and many users are complaining we will take another look at it.
However I would prefer to check for unpublished versions and simply close affected pull requests automatically.

Happy to reopen this issue then.

Best,
Stephan

**Comment by nkbt** [comment]
No worries, Stephan, that is reasonable. After all I can always postpone merging a PR for a day or so =)
