### ISSUE TITLE
ERR! enable Couldn’t enable a repository with this slug

### ISSUE THREAD

**Issue by cdaringe** [greenkeeperio/greenkeeper#158]
hello:

i have a series of open source repos under the "MRN-Code/" org.  e.g. https://github.com/MRN-Code/coinstac-ui

however, greenkeeper won't let me enable them.  are there org specific settings i need to adjust?  i am able to `enable` on my own repos

thanks!

```
🛰  cdieringer:~/node/coinstac-ui$ greenkeeper --slug=MRN-Code/coinstac-ui enable
🌴  info enable The GitHub slug is: MRN-Code/coinstac-ui
🌴  ERR! enable Couldn’t enable a repository with this slug.
🌴  ERR! enable If you want to try your free private repository make sure to grant the necessary rights by running greenkeeper login --force --private
🌴  ERR! enable You have to have a plan for more than one private repository. To verify run greenkeeper whoami
🌴  ERR! enable If you have just recently created this repository try running greenkeeper sync
🌴  ERR! enable You need admin access to a repository to enable it.
🌴  ERR! enable If you think this error really shouldn’t appear let us look into it with greenkeeper support
```

**Comment by boennemann** [comment]
Hey @cdaringe,

you might need to grant Greenkeeper access to that organization on an individual basis.
First make sure whether that's the case already by running `greenkeeper whoami`.
If your org doesn't show up please use `greenkeeper access` to grant rights to that organization.
After granting rights to a new organization run `greenkeeper sync` to make these repos available to us.

Best,
Stephan

(Happy to reopen if that does not fix it)

**Comment by cdaringe** [comment]
thank you!  the CLI is excellent.  i did have to login/logout, but everything else was smooth!
