### ISSUE TITLE
Failed to create pull request on GHE 2.5

### ISSUE THREAD

**Issue by donny-dont** [greenkeeperio/greenkeeper#161]
We recently updated to GHE 2.5 and finally got our Greenkeeper instance running. It connected up fine but we're seeing the following error when browsing the kue.* site.

![pull_request_error](https://cloud.githubusercontent.com/assets/666297/14301135/17a2d7be-fb4a-11e5-95fe-20146f73889c.png)

**Comment by donny-dont** [comment]
@boennemann or @finnp any way we can get a response here? This is currently preventing us from enabling more projects during our GHE trial.

**Comment by janl** [comment]
@donny-dont sorry for missing this! — Can you use enterprise@greenkeeper.io for more urgent matters? We are monitoring that email more closely than the repo issues here. Thank you!

@christophwitzko @finnp could one of you have a look?

**Comment by finnp** [comment]
Hey @donny-dont,

it might be that the greenkeeper bot account (or its token) doesn't have the necessary rights to send a pull request to the repository.

Can you log in to your GHE greenkeeper bot user to verify that this account can see the repository and create pull requests? (This might only be a problem if your testing repository is private)

If that works, please create a new personal access token for that user with the OAuth scope `repo` enabled and copy that over in the admin consoles general settings to `"Github token for Greenkeeper bot account"`.

Let us know if this works for you or when you have any questions

**Comment by donny-dont** [comment]
@finnp IT setup issue. We gave the service account the correct rights and things were good to go.
