### ISSUE TITLE
Fails to detect automated tests

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#162]
We have at least one repository, but I think a few other ones where GreenKeeper thinks that there are no automated tests, when there are several running on the repo. This leads to spamming of PR's that shouldn't need to be there as all tests are passing.

An example of that can be found here: https://github.com/AtomLinter/linter-sass-lint/pull/67

We've tried disabling greenkeeper and re-enabling it on this repo before, but that didn't seem to work. Is there something we aren't setting up properly, or why is it failing to detect them for this repository?

**Comment by boennemann** [comment]
Hey @Arcanemagus,

sorry for this. I just had a quick look at your Travis configuration and saw that you're only running the tests on master. https://github.com/AtomLinter/linter-sass-lint/blob/master/.travis.yml#L20-L22
Greenkeeper creates branches on your own repository and subscribes to status changes, which don't happen, because Travis does not run without us opening a PR.

I'd suggest you add at least `greenkeeper-*` to that branches list in the `.travis.yml`.

Happy to reopen if that didn't help.

Best,
Stephan

**Comment by Arcanemagus** [comment]
Actually that's not quite the way it works, the CI configuration like that still runs a test on the branch, it just runs a test on the state of master as if the branch had been merged in, instead of the branch itself. If you don't have that configuration Travis runs two sets of builds for every PR.

You can see that Travis is still running on the branch, and we have dozens of other repositories configured in this manner that work just fine. When I first filed this it looks like I was mistaking this for a different repo where this issue is more common, I'm trying to find that now.

If you want an example of this configuration working just fine [this PR](https://github.com/AtomLinter/linter-stylelint/pull/141) on `linter-stylelint` ran properly, even though it's Travis configuration is [the same](https://github.com/AtomLinter/linter-stylelint/blob/master/.travis.yml#L6-L8).

**Comment by Arcanemagus** [comment]
Ah, looks like the other problem repo was `linter-pydocstyle`, see [this PR](https://github.com/AtomLinter/linter-pydocstyle/pull/45).

**Comment by yaycmyk** [comment]
Going to jump onto this as well and say it's not working for me, but I use a less-strict config: https://github.com/yaycmyk/markdown-to-jsx/blob/master/.travis.yml

However, greenkeeper doesn't detect that the tests do in fact run: https://github.com/yaycmyk/markdown-to-jsx/pull/14
