### ISSUE TITLE
pie-in-the-sky: avoid manual merges

### ISSUE THREAD

**Issue by boneskull** [greenkeeperio/greenkeeper#163]
I just merged [PR 15](https://github.com/boneskull/ketch/pull/15).

Now, I want to merge [PR 11](https://github.com/boneskull/ketch/pull/11).

But now I have to do it manually, because there's a "conflict".  There isn't a *real* conflict here; the modified lines in `package.json` are adjacent.  I don't know enough about Git to know whether this can be avoided with a different merge strategy--but that's on GitHub's end anyway.

Are there any solutions GK could provide to this problem?  

Being able to tell GK to "retry" the PR, or rebase the PR on top of `master` would solve the issue, but I don't know what that'd look like.  You could potentially leverage the CLI to do this, I guess, and/or make it a value-add for paying clients.  Maybe some fancy-ass Chrome extension that sits on top of GitHub too...

**Comment by boennemann** [comment]
Thanks for your feedback. This just got fixed via https://github.com/greenkeeperio/greenkeeper/issues/137#issuecomment-209617514.

Best,
Stephan

**Comment by boneskull** [comment]
sweet! thanks.
