### ISSUE TITLE
Can't enable greenkeeper. 

### ISSUE THREAD

**Issue by vankhoa011** [greenkeeperio/greenkeeper#165]
Hello,

I want to try with one private repo. After login successfully, I enable greenkeepr  by `greenkeeper enable` . However, it show the error .

 ```
 info enable The GitHub slug is: XXXX/XXXX
🌴  info enable Synchronizing your repositories. This might take a while.
🌴  ERR! enable Couldn’t enable a repository with this slug.
🌴  ERR! enable If you want to try your free private repository make sure to grant the necessary rights by running greenkeeper login --force --private
🌴  ERR! enable You have to have a plan for more than one private repository. To verify run greenkeeper whoami
🌴  ERR! enable You need admin access to a repository to enable it.
🌴  ERR! enable If you think this error really shouldn’t appear let us look into it with greenkeeper support
```

Please help to check it.

**Comment by finnp** [comment]
Hi @vankhoa011,

have your tried running `greenkeeper login --force --private`?  This way you can try your private repository.

Let me know if this helped :)

**Comment by vankhoa011** [comment]
Hello ,

I tried this command "  greenkeeper login --force --private" . However, the
problem is same.

Let me tell more detail.

I work in ABC company. My leader granted admin permission for
ABC/ourcompany_repo .

I logged in github with vankhoa011 account. And I want to enable
ABC/ourcompany_repo by greenkeeper.


Regards,
Khoa Nguyen


On Mon, Apr 11, 2016 at 8:55 PM, Finn Pauls <notifications@github.com>
wrote:

> Hi @vankhoa011 <https://github.com/vankhoa011>,
>
> have your tried running greenkeeper login --force --private? This way you
> can try your private repository.
>
> Let me know if this helped :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/greenkeeperio/greenkeeper/issues/165#issuecomment-208354938>
>



-- 
Thanks and Regards,
Khoa Nguyen.

**Comment by vankhoa011** [comment]
@finnp: Hello .  Any update on this problem ?

**Comment by boennemann** [comment]
Hey @vankhoa011,

unfortunately you need admin permission to enable a repository. See this issue https://github.com/greenkeeperio/greenkeeper/issues/46 for details of this limitation.
I hope someone in your organization can grant you these rights, or take care of the enabling.

Best,
Stephan

**Comment by vankhoa011** [comment]
@boennemann  : I had admin permission but still can't enable . :(

**Comment by vankhoa011** [comment]
@boennemann : Any updated ?

**Comment by finnp** [comment]
@vankhoa011 We're not sure what's the problem here. It is likely that there is some issue with the permissions. Can you do `greenkeeper login --private --force` again? 

Then you should see a list of you organisations, if there is a button `Grant access` next to the organisation, it means greenkeeper doesn't have access to it yet.

If you see that button, click it and then finally click `Authorize Application`.

If that doesn't help, let us know.

**Comment by vankhoa011** [comment]
@finnp : I worked like a charm. Thanks you very much.
