### ISSUE TITLE
Does it work with monorepo architecture?

### ISSUE THREAD

**Issue by steelbrain** [greenkeeperio/greenkeeper#166]
Just wondering if greenkeeper works with mono repo architecture

If it does not, I would like to request the ability to have `.greenkeeper.json` in project root which has a map of all the packages that points to their roots like

```js
{
  "babel-core": "./packages/babel-core"
}
```

**Comment by boennemann** [comment]
Hey @steelbrain,

thanks for your feedback. I'm closing this issue as a duplicate of #139.
Please subscribe to that issue for updates.

Best,
Stephan
