### ISSUE TITLE
CLI prompt for private repositories

### ISSUE THREAD

**Issue by donny-dont** [greenkeeperio/greenkeeper#167]
We have the GHE version of Greenkeeper and the site instructions on the instance don't mention needing to run `greenkeeper login --force --private` for private repositories. When getting people to enable it on their repos they always hit this issue. It would be great if its GHE to do a prompt or to add something in the site quick start about private repositories.

**Comment by janl** [comment]
It sounds like the ideal workflow here would be that `greenkeeper` detects that it is running against a GKE-endpoint, and does `--force --private` by default.

@finnp could you have a look if that’s feasible to build?

**Comment by finnp** [comment]
Yeah I think that should be no problem. I'm going to create a pull request for this.
