### ISSUE TITLE
Option to disable automatic rebasing?

### ISSUE THREAD

**Issue by elliottsj** [greenkeeperio/greenkeeper#169]
I've started to notice greenkeeper automatically rebasing PRs when the base branch is updated (https://github.com/greenkeeperio/greenkeeper/issues/137).

When a lot of greenkeeper PRs auto-rebase simultaneously, it triggers a lot of CI builds, which take a while to complete and blocks future builds that have higher priority. Is there a way to disable this behaviour?

**Comment by boennemann** [comment]
Hey @elliottsj,

thanks for your feedback on this.

Currently we're only rebasing our PRs whenever another Greenkeeper PR is merged, not for every change on the base branch. This gives you control over when this is happening.

We see that a blocked CI build queue is annoying, so we'll continue to observe this situation and further collect feedback so we can find a feasible solution.

Thanks again,
Stephan

**Comment by ainth** [comment]
If my head math is right falling behind by 20 PRs (which is not unusual in a large project) would take 210 builds to clear out. This assumes that you merge into your main branch causing a build and a build for each open greenkeeper PR. I would be more likely to bundle all the PRs together manually in this case which doesn't feel as good.

**Comment by wenzowski** [comment]
Huge :+1: on automatic rebasing, though having same issue with CI queue. Additionally, it looks like GK might be getting confused when I create a new branch, merge GK PRs in that branch to resolve conflicts, and subsequently merge the new branch (with several GK commits) to master in one go, since this causes several PRs to be closed simultaneously.

**Comment by boennemann** [comment]
@ainth This is true if you fall behind on 20 PRs of 20 different dependencies. Most of the time, especially when pull requests pile up, you'll have them for only a few dependencies. This is why we introduced auto-closing for those: https://github.com/greenkeeperio/greenkeeper/issues/62

**Comment by wenzowski** [comment]
@boennemann I wouldn't say I'm behind. I have >20PRs open and it's only been a week.

**Comment by boennemann** [comment]
@wenzowski Does the scenario you describe "close" or "merge" the pull requests?

**Comment by wenzowski** [comment]
@boennemann by merge through a new branch. This example would update two GK PRs simultaneously:

```
git checkout -b feature/babel-6.7.5
git merge origin/greenkeeper-babel-core-6.7.5
git merge origin/greenkeeper-babel-cli-6.7.5
git checkout master
git merge feature/babel-6.7.5
```

**Comment by rjmunro** [comment]
I think it should rebase if the PR can no longer merge cleanly, no matter weather it is a greenkeeper or another PR that has caused the problem.

**Comment by boennemann** [comment]
Auto-rebasing is no longer a part of the new Greenkeeper 2, as GitHub now supports it in their UI.
I'll close this issue.
