### ISSUE TITLE
Branch removed before Travis can complete

### ISSUE THREAD

**Issue by fvdm** [greenkeeperio/greenkeeper#171]
I have this a lot lately on many repos.

1. GK creates a branch
2. Travis creates the build
3. In the meantime GK removes the branch from origin
4. Travis starts running the build
5. Build fails because the missing branch can't be cloned

This is especially annoying when I update a lib that is used by my other repos. They all get red build status so I need to manually check them one-by-one or run them all again from their master branch.

> https://travis-ci.org/fvdm/nodejs-searchitunes/jobs/123448370
> fatal: Remote branch greenkeeper-dotest-1.8.0 not found in upstream origin

It'd be nice if GK would check Travis for the build status and only delete the branch _after_ completion.

(edit: rewrote the steps and annoyance)

**Comment by finnp** [comment]
Hi @fvdm,

thank you for the report. We actually do check the build status before deleting the branch. It seems though like there is a (rare) race condition, where we delete branches when travis didn't send the `pending` hook in time. We're going to fix this soon. In the meantime it will hopefully not happen to you again.

**Comment by boennemann** [comment]
Thanks again for your detailed report. A solution for this problem got deployed and so I'm closing this issue .

Should this problem reappear we'll reopen and investigate immediately.

Best,
Stephan

**Comment by fvdm** [comment]
Great, thanks!

**Comment by fvdm** [comment]
Yeah it's all fixed, thanks a lot!!
