### ISSUE TITLE
Repo has tests, but PRs are being opened as "untested"

### ISSUE THREAD

**Issue by Lange** [greenkeeperio/greenkeeper#172]
Hi there!

I maintain [`nodecg/dashboard`](https://github.com/nodecg/dashboard), which has both Appveyor and Travis CI tests. Greenkeeper has been opening PRs to this repo as "untested", even though the PR itself has test results from Appveyor and Travis. I'm not sure what the issue is. Any insight would be appreciated.

Links:

- [A recently opened "untested" PR that has Appveyor and Travis results](https://github.com/nodecg/dashboard/pull/6)

Thanks!

**Comment by boennemann** [comment]
Hey @Lange,

thanks for your report. We're already tracking this problem in https://github.com/greenkeeperio/greenkeeper/issues/59, so I'll close this as a duplicate. Please subscribe to the other issue to track our progress.

Best,
Stephan
