### ISSUE TITLE
Case issue when using slug with enable

### ISSUE THREAD

**Issue by Morklympious** [greenkeeperio/greenkeeper#174]
Hey! Loving Greenkeeper!

I ran into an issue where I kept getting errors with GK unable to use the slug it detected in my local repo. 

I usually end up pulling down my repos in all lower case since Github seems to not care that my username starts with a capital M. I run something like:

`git clone https://github.com/morklympious/hipster-module-patterns` 

and it clones just fine, but if I enable greenkeeper and get that error, it turns out it's because there's a mismatch with my Github username (Morklympious) and the username attached to the related slug (morklympious/hipster-module-patterns)

I end up having to specify `greenkeeper --slug=Morklympious/repo-name enable` any time I want to enable GK. 

Not horrible, but definitely made me lose 2 hours looking for a problem that didn't seem to be documented! So Ideally we should either document that this can happen if theres a mismatch in username and slug used by GK, or make sure the `.git/config` file has a slug that matches the auth parameters.

**Comment by janl** [comment]
Agreed, this should be documented.

**Comment by gdi2290** [comment]
I ran into this error just now and the workaround using `--slug` worked for me
```coffee
git:(master+commits.)
patrick@gdi2290:~/Documents/AngularClass/angular2-webpack-starter $ greenkeeper enable
🌴  info enable The GitHub slug is: angularclass/angular2-webpack-starter
🌴  info enable Synchronizing your repositories. This might take a while.
🌴  ERR! enable Couldn’t enable a repository with this slug.
🌴  ERR! enable If you want to try your free private repository make sure to grant the necessary rights by running greenkeeper login --force --private
🌴  ERR! enable You have to have a plan for more than one private repository. To verify run greenkeeper whoami
🌴  ERR! enable You need admin access to a repository to enable it.
🌴  ERR! enable If you think this error really shouldn’t appear let us look into it with greenkeeper support
git:(master)
patrick@gdi2290:~/Documents/AngularClass/angular2-webpack-starter $ greenkeeper support
🌴  info support Opening GitHub issues (free plan) or Intercom
git:(master)
patrick@gdi2290:~/Documents/AngularClass/angular2-webpack-starter $ greenkeeper --slug=AngularClass/angular2-webpack-starter enable
🌴  info enable The GitHub slug is: AngularClass/angular2-webpack-starter
AngularClass/angular2-webpack-starter enabled
git:(master)
patrick@gdi2290:~/Documents/AngularClass/angular2-webpack-starter $
```

**Comment by boennemann** [comment]
Hey y'all,

this is now fixed on our side and will go live with the next deploy.

Thanks for your reports and patience.


Best,
Stephan

**Comment by Morklympious** [comment]
@gdi2290 Glad it worked for you!

@boennemann Much obliged! :) :+1:
