### ISSUE TITLE
Unable to enable fairmanager/fm-log

### ISSUE THREAD

**Issue by oliversalzburg** [greenkeeperio/greenkeeper#175]
```
$ greenkeeper enable
info enable The GitHub slug is: fairmanager/fm-log
info enable Synchronizing your repositories. This might take a while.
ERR! enable Couldn’t enable a repository with this slug.
ERR! enable If you want to try your free private repository make sure to grant the necessary rights by running greenkeeper login --force --private
ERR! enable You have to have a plan for more than one private repository. To verify run greenkeeper whoami
ERR! enable You need admin access to a repository to enable it.
ERR! enable If you think this error really shouldn’t appear let us look into it with greenkeeper support
```
I'm an admin for this organization and the repo is public. So, what's the problem?

**Comment by janl** [comment]
Hi @oliversalzburg, sorry for your troubles with Greenkeeper!

Have you verified that your organisation is known to Greenkeeper with `greenkeeper whoami`?

If it is not listed there, `greenkeeper whoami` will ask you to run `greenkeeper access` to grant Greenkeeper access to your organisation.

If that’s not it, and if that isn’t clear from our error messages, please let us know!

**Comment by oliversalzburg** [comment]
Hi @janl. Yeah, seems like that was the issue. Seems like I neglected to grant access to the fairmanager org.

Thanks :)
