### ISSUE TITLE
Use email instead of PR to notify about failed dependency update

### ISSUE THREAD

**Issue by feross** [greenkeeperio/greenkeeper#181]
I added Greenkeeper to all my repos, but I have a few collaborators who find the PR notifications extremely annoying -- especially all the false positives that are caused by flaky remote browser testing services.

I suggested that they block the Greenkeeper GitHub user, but even that doesn't work. They're still notified when *I* close or merge the Greenkeeper PRs.

I don't want to bother my collaborators, but I still want to keep using Greenkeeper. A solution might be to do what Travis does -- just send me (the repo owner) an email when something starts failing.

In the meantime, I had to disable Greenkeeper because I'm currently getting hundreds of PRs per week.

<img width="849" alt="screen shot 2016-05-04 at 23 49 59" src="https://cloud.githubusercontent.com/assets/121766/15030520/057fc4aa-1253-11e6-86fd-39216b55e66f.png">

**Comment by janl** [comment]
Heya @feross, thank you for taking the time to write this up!

GitHub is sending these emails, not us, there isn’t much we can do about this until GitHub adds APIs that are more bot-friendly (so we could opt out of notifications), or more granular for end-users, to enable/disable this with better rules.

At the moment, GitHub is designed for humans and that sometimes is at odds with services like Greenkeeper. We keep in close touch with the GitHub team, but there won’t be a way around this for the foreseeable future.

For us, this a bit of a “shoot the messenger” type of situation. Greenkeeper is simply showing the churn that is real in your packages, not creating it :)

As for “especially all the false positives that are caused by flaky remote browser testing services.” <- there is not much we can do about flakey test suites ;)

**Comment by feross** [comment]
Hey @janl -- thanks for the response.

I understand that you don't control the GitHub emails. However, you *do* control the PRs that Greenkeeper is sending -- and that's what this issue is about.

I want Greenkeeper to continue making branches and triggering CI, but instead of sending a PR when there is a test failure, I want to receive an email instead.

This way, I (the repo owner) am the only user who is disturbed. Surely this is something that is actually in Greenkeeper's control.

**Comment by boennemann** [comment]
Hey @feross,

thanks again for your feedback. I think what you suggest here is something that could work, especially for high volume repos with lots of watchers.

Just so I understood you correctly.

For new versions in range:

Create Branch. a) delete branch after success b) send email after fail and keep branch.
I think that email could already contain a link to the "Create new PR" interface.

How would you handle out of range updates? I think these are causing most of the PR/email traffic in the first place.
Create branch, send same email directly?

For the email address to use: We could use the one attached to the account that enabled Greenkeeper, but some accounts are configured to not share that data. Would the `package.json`'s author(s) field be a good source/fallback?

All in all this is something I think we could do, but I can't promise anything in the near future.

Best,
Stephan

**Comment by feross** [comment]
Thanks for considering the request. I'd love to re-enable Greenkeeper on my repos once such functionality is available. 👍 My collaborators thank you in advance!

> How would you handle out of range updates? I think these are causing most of the PR/email traffic in the first place. Create branch, send same email directly?

That sounds great.

> For the email address to use: We could use the one attached to the account that enabled Greenkeeper, but some accounts are configured to not share that data. Would the package.json's author(s) field be a good source/fallback?

Sounds reasonable to me.

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations. You can try it out today: https://github.com/integration/greenkeeper

There are several changes that affect this feature request.
1. GitHub no longer sends eMail notifications for PRs created by bots
2. We will now only create a single PR (out of range) or Issue (in range) per dependency at a time, and keep that up to date with comments. The noise should be greatly reduced.

We think that these changes make this feature requests unnecessary, but we're happy to reconsider once you've tried it.

Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
