### ISSUE TITLE
Automatic (or triggered) rebases on force pushes to branches

### ISSUE THREAD

**Issue by OmgImAlexis** [greenkeeperio/greenkeeper#184]
Similar to https://github.com/greenkeeperio/greenkeeper/issues/137 if you force push to a branch greenkeeper doesn't auto rebase on top of any changes. Just like the other issue this makes the PR unmergeable without going to the command line.

For example: https://github.com/OmgImAlexis/wvvw.me/pull/8

**Comment by boennemann** [comment]
Auto-rebasing is no longer a part of the new Greenkeeper 2, as GitHub now supports it in their UI.
I'll close this issue.
