### ISSUE TITLE
Check if gk points to greenkeeper

### ISSUE THREAD

**Issue by OmgImAlexis** [greenkeeperio/greenkeeper#185]
Since git from Homebrew tends to install gitk when installing git people using OSX may end up with `gk` being an alias to `gitk --all --branches`.
Maybe Greenkeeper should check `which gk` points to greenkeeper before suggesting to use `gk` in the `greenkeeper help` command.

**Comment by janl** [comment]
@OmgImAlexis thanks for bringing this up.

I see no mention of `gitk` in https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb

In addition, by the time `greenkeeper help` runs, the `gk` alias is already installed, and we have no way of telling (aside from running, which is surely not what we should be doing), whether it’s us or someone else.
