### ISSUE TITLE
Pull Request attempts to remove license property

### ISSUE THREAD

**Issue by maxrimue** [greenkeeperio/greenkeeper#186]
I have Greenkeeper enabled for my repository [node-autostart](https://github.com/maxrimue/node-autostart), but as I had to notice, a recent PR for updating a dependency not only attempted to do that (correctly), but also removed the `license` property in my `package.json` in its commit.

You can find the PR [here](https://github.com/maxrimue/node-autostart/pull/20/files), thanks.

**Comment by janl** [comment]
Just a quick confirmation that this is not desired behaviour and we are definitely considering this to be a bug.

**Comment by bcoe** [comment]
@janl @maxrimue looking at the original package.json; it looks like there are _two_ license stanzas, and greenkeeper simply removed the duplicate -- the underlying culprit could very well be `npm-registry-client`, seems like something npm would do by default.

**Comment by christophwitzko** [comment]
Hi @maxrimue,

as @bcoe said, you have _two_ license fields in your `package.json` ([1](https://github.com/maxrimue/node-autostart/blob/ba671dc1b3479e4617caf80f548150d603851265/package.json#L41), [2](https://github.com/maxrimue/node-autostart/blob/ba671dc1b3479e4617caf80f548150d603851265/package.json#L57)).

At the moment we cannot handle JSON with duplicate keys.

Have a great day,
Christoph

**Comment by boennemann** [comment]
Referencing https://github.com/greenkeeperio/greenkeeper/issues/123

**Comment by maxrimue** [comment]
Ah yes, that explains everything, thanks to everyone!
