### ISSUE TITLE
disable PRs for out-of-semver-range version updates

### ISSUE THREAD

**Issue by noffle** [greenkeeperio/greenkeeper#189]
Is there some way to disable PRs for dependency updates that **aren't** within the project's semver? We'd still like to know if someone broke us, but don't need PR clutter for versions outside our semver range.

**Comment by iamstarkov** [comment]
thats will be good

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations. You can try it out today: https://github.com/integration/greenkeeper

There are several changes that affect this feature request.
1. GitHub no longer sends eMail notifications for PRs created by bots
2. We will now only create a single PR (out of range) or Issue (in range) per dependency at a time, and keep that up to date with comments. The noise should be greatly reduced.

We think that these changes make this feature requests unnecessary, but we're happy to reconsider once you've tried it.

Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
