### ISSUE TITLE
--help is truncated

### ISSUE THREAD

**Issue by dignifiedquire** [greenkeeperio/greenkeeper#190]
I just installed a fresh version of `greenkeeper@2.11.2` and running help seems to be truncated

```sh
➜  greenkeeper -h
# Usage
Have a question? Check the FAQ at https://greenkeeper.io/faq.html, or talk to a human:
Run greenkeeper support :)

Usage: greenkeeper [--slug=user/repository] <command>

┌─────────────┬─────────────────────────────────────────────────────────────────────┐
│ command     │                                                                     │
├─────────────┼─────────────────────────────────────────────────────────────────────┤
│ start       │ learn how to get started           %                                                                           
➜  
```

I'm running `node@6.0.0` at the moment on OS X 10.11.4 and use zsh + iterm2.

**Comment by boennemann** [comment]
Hey @dignifiedquire,

thanks for the report. Confirmed from my side.
Looks like a bug in newer node versions: https://github.com/nodejs/node/issues/6456

It seems like there is work around for it already: https://github.com/yargs/set-blocking
I'll try to implement this soon.

Best,
Stephan

**Comment by iamstarkov** [comment]
@boennemann any news?
