### ISSUE TITLE
feature request: an option to get a PR for each version. 

### ISSUE THREAD

**Issue by aredridel** [greenkeeperio/greenkeeper#191]
Since we deploy with just npm install && npm start, upgrades only happen when we bump minimum specs.

**Comment by danielnbarbosa** [comment]
👍  We have a workflow that requires that all changes generate a PR that is approved by a human.

**Comment by mickhansen** [comment]
Our usecase is continous deployment, if we publish any kind of fix in a dependency package we'd like a PR to all dependent so they can be deployed with the fix without a human having to bump each repo.

**Comment by boennemann** [comment]
I'm not sure anymore if I understand this correctly, but I think this behavior can be achieved by pinning dependencies. Greenkeeper will then send a PR for each version.
Happy to reopen if I misunderstood this.
