### ISSUE TITLE
Customise commit messages

### ISSUE THREAD

**Issue by LinusU** [greenkeeperio/greenkeeper#192]
I would like to have the ability to customise the commit messages that greenkeeper uses. We are enforcing a specific style on our repos and thus the tests are failing simply because greenkeeper doesn't follow it.

In my specific case I would like it to be `🍭 Update ${name} to version ${version}`, but I would love for this to be a setting in the package.json, something like this:

```js
{
  // ...
  "greenkeeper": {
    "commitMessage": "🍭 Update ${name} to version ${version}"
  }
}
```

**Comment by boennemann** [comment]
Hey @LinusU,

thanks for your feedback.
This is something we're considering for the future.

You may track the progress on the existing issue: #153

I'm closing this as a duplicate.


Thanks,
Stephan

**Comment by LinusU** [comment]
Thanks, I tried searching but must have missed that one 👍
