### ISSUE TITLE
Using greenkeeper as a kind of integration test + stats for a project

### ISSUE THREAD

**Issue by hzoo** [greenkeeperio/greenkeeper#195]
This is a feature request so that open source projects can get useful information from greenkeeper as well. The basic idea is to get a summary/stats page of projects using greenkeeper to upgrade the dependency of your own project.

I was looking at https://github.com/greenkeeperio-bot?tab=activity and noticed things like

```
babel-polyfill@6.9.1 untested ⚠️
babel-core@6.9.1 breaks build ⚠️
Update babel-runtime to version 6.9.1 🚀
```

I forgot I had just published a new release of babel so then the activity would be all the public projects using it.

What would be nice is to see how many projects have a rocket (passing tests) after upgrading and how many are failing and even better if we could isolate or have an easy link to logs to check for any quick regressions after releasing (a sanity check).

Basically this would act as a really big integration test for us using all the projects out there using [insert project] + greenkeeper. Normally you would `git clone` a few popular projects and test on the latest release or master but this would do the same on a wider scale. It might be a bit difficult since tests could be flaky but its worth a shot.

It's kind of abstract at the moment, but the general idea is being able to use greenkeeper PR information and give that back to the project itself in a useful way. Maybe just scraping the event log is good enough.

Just doing https://github.com/pulls?q=is%3Apr+author%3Agreenkeeperio-bot+babel+6.9.1+is%3Aopen was pretty cool in itself

<img width="812" alt="screen shot 2016-05-29 at 5 05 00 pm" src="https://cloud.githubusercontent.com/assets/588473/15636004/8e63ff32-25bf-11e6-967f-9fe607b6de93.png">

**Comment by boennemann** [comment]
Thanks for the suggestion. This is part of our roadmap. https://github.com/greenkeeperio/greenkeeper/projects
> Support "beta" and "next" dist-tags for real world testing and feedback

I'll close this issue, as it's already on there.
