### ISSUE TITLE
Support adding the changelog/github release for a monorepo package

### ISSUE THREAD

**Issue by hzoo** [greenkeeperio/greenkeeper#196]
I was looking through some greenkeeper prs for babel packages and noticed there wasn't a changelog/section where it says `GitHub Release`.

I'm assuming it's not showing up because the repo (babel/babel) doesn't match the npm package name or something (babel-core, etc)? All the packages are under the `packages/` folder at https://github.com/babel/babel/tree/master/packages.

https://github.com/babel/babel/blob/master/packages/babel-core/package.json#L1-L8

**Comment by janl** [comment]
https://blog.greenkeeper.io/announcing-greenkeeper-3-1504f5113998
