### ISSUE TITLE
Auto-merge greenkeeper PR when Status Check is green (protected branches only)

### ISSUE THREAD

**Issue by singles** [greenkeeperio/greenkeeper#198]
GH provides [combined status endpoint](https://developer.github.com/enterprise/2.6/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref) which could be used for that. It should be possible to enable only for protected branches using [required status check](https://help.github.com/articles/about-required-status-checks/)

I wanted to implement that using our github bot, but before that I would like to ask if you have something like that in plans?

**Comment by leo** [comment]
Cool idea! But there should be a way to disable this using an option.

**Comment by jbcpollak** [comment]
I'm drowning in pull requests now - would love something like this.

**Comment by kkemple** [comment]
This is something I have wanted also and even went so far as to make a service that does this :: https://github.com/kkemple/greenkeeper-keeper

I would be willing to give it a shot so i could retire my bot and let greenkeeper handle this

**Comment by boennemann** [comment]
We do not plan to support this in the core of Greenkeeper, but as community solutions do exists I'll go ahead and close this issue.
