### ISSUE TITLE
Travis CI target maintenance

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#200]
@seriousManual commented on [Mon Sep 28 2015](https://github.com/greenkeeperio/support/issues/9)

Maybe a bit out of the scope of greenkeeper:
As new node versions are getting release it would be a nice feature if greenkeeper also keeps the list of travis build targets up to date.

---

@gr2m commented on [Mon Sep 28 2015](https://github.com/greenkeeperio/support/issues/9#issuecomment-143717221)

Love it :)

---

@janl commented on [Mon Sep 28 2015](https://github.com/greenkeeperio/support/issues/9#issuecomment-143717658)

This is high on our roadmap, in fact :)

---

@seriousManual commented on [Mon Sep 28 2015](https://github.com/greenkeeperio/support/issues/9#issuecomment-143725605)

Nice!

---

@ariporad commented on [Mon Nov 02 2015](https://github.com/greenkeeperio/support/issues/9#issuecomment-152888925)

+1, this would make greenkeeper even more awesome. (really, Travis should do this by itself).

One other (related) request:
In my `.travis.yml`, I have:

``` yaml
before_install:
    - npm i -g npm@3
```

It would be nice if greenkeeper offered a way to pin that version as well.

Thanks for making something so awesome!

**Comment by janl** [comment]
We’re doing this now :)
