### ISSUE TITLE
Peer Dependencies

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#201]
@ForbesLindesay commented on [Thu Oct 15 2015](https://github.com/greenkeeperio/support/issues/14)

It would be really great if this could also update `peerDependencies`.  Ideally, it should make the new version range include everything in the old version range, as well as whatever new version has been published.

---

@lukekarrys commented on [Mon Nov 16 2015](https://github.com/greenkeeperio/support/issues/14#issuecomment-157127622)

:+1:

I'm currently running into an issue where my repo has some of the same peer and dev dependencies, so when greenkeeper makes a PR for a dev dependency `npm install` fails on travis with a `peerinvalid` since the peer dependency doesn't get updated.

Here's an example [PR](https://github.com/lukekarrys/eslint-config/pull/2) and resulting [travis build](https://travis-ci.org/lukekarrys/eslint-config/builds/91300116#L117) for reference. I realize this is pretty edge case :smile:

Also, thanks for greenkeeper!

---

@artemv commented on [Mon Mar 07 2016](https://github.com/greenkeeperio/support/issues/14#issuecomment-193445782)

+1

For our case straightforward peerDependency update is needed. 

Our configuration is: 
- B and C packages use A as peerDependsncy, and 
- D uses A, B and C as depenencies, 

all with exact versions - this way we want to make sure D uses B and C tested with the same version of A.

**Comment by simonkberg** [comment]
:+1: kind of weird because greenkeeper says the type is `peerDependency` in [this pr](https://github.com/simonkberg/eslint-config-react/pull/5), even thought it's actually updating the `devDependency`.

**Comment by boennemann** [comment]
Closing this as duplicated of #151.
