### ISSUE TITLE
because i make the PRs, I am never notified

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#203]
@jonathanong commented on [Wed Dec 30 2015](https://github.com/greenkeeperio/support/issues/19)

i would like a feature where we can somehow hook up a bot (another github user of my choosing or a bot provided by you). i am never notified that greenkeeper made a PR.

also, assigning it to me (or allow setting a default assigner) would be nice.

---

@jonathanong commented on [Thu Dec 31 2015](https://github.com/greenkeeperio/support/issues/19#issuecomment-168096961)

To be more specific, this is for private repos. Public repos are fine.

It would be easier if I could login with a bot easier. I guess I'll wait for the web UI

**Comment by leo** [comment]
Same problem here! I never get notifications for private repos when a PR from greenkeeper arrives.

**Comment by finnp** [comment]
Hey @jonathanong @leo,

basically this is already possible. You would need to create a new GitHub account, add them to your private repositories with the necessary rights, then do `greenkeeper login` with that account and enable the private repositories.

Now your bot user will create the pull requests and you will be notified.
