### ISSUE TITLE
Getting updates on older versions of a package

### ISSUE THREAD

**Issue by callumacrae** [greenkeeperio/greenkeeper#208]
We're using jQuery 1.x and React 0.14.x at work, and we don't want to update them because we can't drop support for IE8 (😞 ). Currently whenever there is a release of jQuery 2.x, we get a PR which we immediately ignore, and whenever there is a release of jQuery 1.x, we don't know about it.

Is there any way to configure this behaviour?

**Comment by jgzamora** [comment]
Don't know about configuring for getting new newest 1.x, but can add an ignore array to your `package.json` in order to get rid of the unwanted 2.x PRs for now.

```
"greenkeeper": {
  "ignore": ["jQuery"]
}
```

**Comment by gr2m** [comment]
> I wish that there was a way to have Greenkeeper stop trying to upgrade us to Vue 2.x when we're still on Vue 1.1.x as we're not in a place to upgrade yet.

Would it be helpful if we would allow to not only ignore package names, but package names with version numbers? E.g. something like this?

```
  "greenkeeper": {
    "ignore": ["jquery > 1"]
  }
```

Not making any promises, just gathering more opinions :)

**Comment by janl** [comment]
Closing in favour of #581
