### ISSUE TITLE
Claim in PR is a tad strong

### ISSUE THREAD

**Issue by glenjamin** [greenkeeperio/greenkeeper#21]
Hello! I'm in the process of trying out greenkeeper, and ran into the following in the initial PR:

> No more surprises because some of your dependencies didn’t follow SemVer. Your software is always in a state you know about, regardless of when someone does $ npm install.

This claim is slightly stronger than the full truth, because it only applies if all transitive dependencies have pinned versions - which is not the norm.

I'm not sure whether this is a big enough different to merit a change, but wanted to raise it for your consideration.

**Comment by boennemann** [comment]
Thanks for the feedback, I've now slightly adapted the message.
