### ISSUE TITLE
Do "xyz breaks build" PRs get closed if next patch version passes?

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#211]
e.g. https://github.com/hoodiehq/hoodie-admin/pull/5. I wonder if Greenkeeper created another branch for `loader.js@4.0.7` which passed. And if it did, it would be nice if it would have closed the PR with a note or something :)

**Comment by jbcpollak** [comment]
For that matter - any later PR should close older PRs. For example, eslint released `0.12.1`, `0.13.0`, then `0.13.1` really quickly, so I had 3 PRs open at once (all green). I would love Greenkeeper to auto-close the older PRs (and delete the branch) and just leave the latest one.

**Comment by gr2m** [comment]
I think it does that when you merge the last PR

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations. You can try it out today: https://github.com/integration/greenkeeper

We will now only create an issue for in-range updates that break. Once there is a new version that passes again you'll receive a comment in there.

We think that these changes make this feature requests unnecessary, but we're happy to reconsider once you've tried it.

Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
