### ISSUE TITLE
Greenkeeper has submitted pull request with corrupt package.json

### ISSUE THREAD

**Issue by evansiroky** [greenkeeperio/greenkeeper#212]
See here:  https://github.com/evansiroky/db-streamer/pull/7/commits/77b2bffb40e81d2e4a5cd937eb3e952f3d8ae874

And here:  https://github.com/evansiroky/gtfs-sequelize/pull/18/commits/55fb68d10f738c83170e6970b2cdd0aaf559bcf9

**Comment by finnp** [comment]
Hey, thanks for reporting this. It's a bug in the way we try to preserve indentation. We're going to update this soon.

**Comment by finnp** [comment]
Hey @evansiroky,

This is fixed now. Sorry for the inconvenience!

**Comment by evansiroky** [comment]
Thanks!
