### ISSUE TITLE
Close PRs for breaking changes while in version-range if patch release fixes it

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#216]
Example: https://github.com/hoodiehq/hoodie/pull/508

About 3h ago nyc@6.6.0 was released which broke tests in several repositories I maintain. Only 25minutes later nyc@6.6.1 was released which fixed the problem. It would be nice if Greenkeeper would do a check with `nyc@6.6.1` and see that tests are now passing, then go ahead and close the PRs for nyc@6.6.0 itself, with a note that `nyc@6.6.1` was released and it solved the issue.

The same happened several times in the past, it would help with maintaining projects quite a bit :)

**Comment by boennemann** [comment]
With Greenkeeper 2 and threaded PRs this is solved quite nicely. I'll close this issue.
