### ISSUE TITLE
link issues like `#123` in changelogs

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#226]
Example: https://github.com/gr2m/editable-table/pull/14

<img width="466" alt="screen shot 2016-06-20 at 16 35 25" src="https://cloud.githubusercontent.com/assets/39992/16213547/06ccf856-3705-11e6-98d5-b3e8e1c09c68.png">

it would be nice if `#41` etc would link to the respective pull request / issue for quicker review

**Comment by boennemann** [comment]
We tried to fix this with the new Greenkeeper, but the GitHub markdown API doesn't convert these correctly. Currently we can't fix this :(
