### ISSUE TITLE
False build failures when using End-to-End tests with SauceLabs/Sauce Connect

### ISSUE THREAD

**Issue by leutloff** [greenkeeperio/greenkeeper#228]
I now often get false build failures for a small project used to demonstrate the basic use of an end to end test. In the Travis CI log files you will see this failure: "Error bringing up tunnel VM."

Starting the test manually will lead to a successful run of the test.

This is obviously not a greenkeeper error by itself. But it may be triggered by greenkeeper. I suppose that greenkeeper is changing a huge amount of repositories at nearls the same time. The available testing infrastructure may not be sufficient for such a use case. Perhaps it is possible to slow down the rate of changes executed by greenkeeper to reduce the amount of workload put on CI infrastructure. I am using all the services for free. So I am interested in using the provided resources in a fair manner, too.

Another approach would be restart the failed job when the above error message is located in the log files.

Here is one of the failing jobs (my be green when restarted)
https://travis-ci.org/leutloff/e2e-webdriverio-mocha-tdd-example/jobs/139934091

This is the relevant snippet from the log file:

Extracting Sauce Connect
Waiting for Sauce Connect readyfile
24 Jun 02:42:08 - Sauce Connect 4.3.16, build 2396 39e807b
24 Jun 02:42:08 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
24 Jun 02:42:08 - Using CA certificate verify path /etc/ssl/certs.
24 Jun 02:42:08 - Starting up; pid 3747
24 Jun 02:42:08 - Command line arguments: sc-4.3.16-linux//bin/sc -i 109.9 -f sauce-connect-ready-29867 -l /home/travis/sauce-connect.log
24 Jun 02:42:08 - Log file: /home/travis/sauce-connect.log
24 Jun 02:42:08 - Pid file: /tmp/sc_client_109.9.pid
24 Jun 02:42:08 - Timezone: UTC GMT offset: 0h
24 Jun 02:42:08 - Using no proxy for connecting to Sauce Labs REST API.
24 Jun 02:42:08 - Resolving saucelabs.com to 162.222.75.243 took 0 ms.
24 Jun 02:42:08 - Started scproxy on port 42720.
24 Jun 02:42:08 - Please wait for 'you may start your tests' to start your tests.
24 Jun 02:42:08 - Starting secure remote tunnel VM...
24 Jun 02:42:12 - Secure remote tunnel VM provisioned.
24 Jun 02:42:12 - Tunnel ID: 453b3cbdd7d341c69bac99cbe7c1f909
24 Jun 02:42:12 - Secure remote tunnel VM is now: booting
24 Jun 02:43:26 - Error bringing up tunnel VM.
24 Jun 02:43:26 - Cleaning up.
24 Jun 02:43:26 - Removing tunnel 453b3cbdd7d341c69bac99cbe7c1f909.
24 Jun 02:43:30 - All jobs using tunnel have finished.
24 Jun 02:43:30 - Sauce Connect could not establish a connection.
24 Jun 02:43:30 - Please check your firewall and proxy settings.
24 Jun 02:43:30 - You can also use sc --doctor to launch Sauce Connect in diagnostic mode.
24 Jun 02:43:30 - Goodbye.

Thanks for providing greenkeeper.

**Comment by boennemann** [comment]
Thanks for reporting this issue. As this is not immediately fixable by Greenkeeper I'll go ahead and close it though, so our issue tracker stays actionable.
