### ISSUE TITLE
Why was pin dependencies disabled?

### ISSUE THREAD

**Issue by gihrig** [greenkeeperio/greenkeeper#229]
`greenkeeper enable` used to pin deps automatically. see [here](https://www.youtube.com/watch?v=XbQvxCLkBbw) @0:55 but this seems not to be the case presently. Sure seems like a good idea to avoid end users installing breaking changes. ref: https://github.com/mxstbr/react-boilerplate/issues/598

Can someone shed some light on why this feature was removed?

**Comment by finnp** [comment]
Hey @gihrig,

to decrease the number of pull requests a maintainer has to handle we removed pinning the dependencies automatically. However: We still check if new versions within your range would break your tests (by creating branches). But we only create PRs for the ones that FAIL your tests. If the new version passes, you will not be bothered with a pull request.

If you want to really be sure, you can of course still pin down the dependencies yourself and you will get PRs for every new version.

**Comment by gihrig** [comment]
Thank you! that clarifies it perfectly.
