### ISSUE TITLE
Doesn't understand github URL shorthands

### ISSUE THREAD

**Issue by Munter** [greenkeeperio/greenkeeper#23]
Greenkeeper 2.0.2 tells me this when I run `greenkeeper enable`

```
$ greenkeeper enable
🌴  ERR! disable Couldn't find a GitHub remote "origin" in this folder.
🌴  ERR! disable Try passing the slug explicitly $ greenkeeper enable --slug <user>/<repo>
🌴  ERR! enable Missing slug
🌴  ERR! enable Run this command from inside your repo and add a repository field to the package.json
🌴  ERR! enable Explicitly passing the slug works as well $ greenkeeper enable --slug <user>/<repo>
```

I assume this is related to my [.gitconfig](https://github.com/Munter/dotfiles/blob/master/.gitconfig#L78-L90) and that I cloned my repository with `git clone gh:Munter/fusile`.

This is my `.git/config`:

```
$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
[remote "origin"]
	url = gh:Munter/fusile
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "direct_io"]
	remote = origin
	merge = refs/heads/direct_io
```

**Comment by Munter** [comment]
Running `greenkeeper enable --slug Munter/fusile` works, so I guess this is not really high prio

**Comment by finnp** [comment]
@Munter This is an issue with the dependency used to get the GitHub slug. If this issue is fixed this should work:  https://github.com/finnp/github-slug/issues/7

**Comment by finnp** [comment]
This is now possible since the  `3.0.1` release.
