### ISSUE TITLE
Repo syncing failing

### ISSUE THREAD

**Issue by AlecRust** [greenkeeperio/greenkeeper#230]
After installing and using greenkeeper for the first time I get this:

![screenshot](https://i.imgur.com/L9UgANr.png)

I keep getting this even with a few `greenkeeper login --force`, so reporting here.

**Comment by finnp** [comment]
Hello @AlecRust,

Thank you for your report. I was able to reproduce the problem for your account, but didn't yet figure out what caused the problem. However it seems to me that despite the error message, the sync actually worked. So you should be able to use greenkeeper normally and run `greenkeeper enable` on your repositories to activate them.

We're going to work on a fix for this bug. If you run into any other problems, please let us know.

**Comment by AlecRust** [comment]
Hi @finnp thanks for that. OK, I've gone ahead and enabled greenkeeper on a public repo (https://github.com/AlecRust/wordpress-gulp) which seemed to work fine. I'll let you know if a PR isn't made when my dependencies become out of date!
