### ISSUE TITLE
Auto rebase pull-requests

### ISSUE THREAD

**Issue by piranna** [greenkeeperio/greenkeeper#232]
When a GreenKeeper pull-request fails, sometimes is not due to the dependency itself but due to the project code itself (hidden bugs that appear with the new version of the dependency, working in parallel on several interdependent layered projects...) so when the main one got fixed, the failing GreenKeeper pull-request would work again. The same way that when a new dependency version appear and automatically close the pull-request for previous ones, GreenKeeper should monitor the project itself and rebase the pull-requests when they get updated on master branch, so they don't get stashed on old commits.

**Comment by boennemann** [comment]
This is live. When a Greenkeeper PR gets merged we rebase older Greenkeeper PRs.
