### ISSUE TITLE
Can't enable greenkeeper for a github repo that I am a contributor of

### ISSUE THREAD

**Issue by amilajack** [greenkeeperio/greenkeeper#233]
I have read and write permissions for t3chnoboy/thepiratebay and I can't enable greenkeeper

**Comment by finnp** [comment]
Hey @amilajack,

only the owner of a personal repository has the right to add or change hooks on that repository. Greenkeeper needs those hooks. So you would need @t3chnoboy to enable it for you.

Alternatively I'd recommend moving the repository to an organisation. There it is possible for multiple people to have admin rights and you could set it up yourself.

**Comment by amilajack** [comment]
Thanks!
