### ISSUE TITLE
Strange behavior with pinned versions

### ISSUE THREAD

**Issue by gihrig** [greenkeeperio/greenkeeper#235]
[mxstbr/react-boilerplate](https://github.com/mxstbr/react-boilerplate) is pinning dependency versions. It was decided better to let GK handle dependency updates than rely on semver. This after being burned by what should have been an innocent update [#598](https://github.com/mxstbr/react-boilerplate/issues/598) and [#468](https://github.com/mxstbr/react-boilerplate/issues/468)

GK has been enabled and first PR is a little strange...

![image](https://cloud.githubusercontent.com/assets/1481063/16527470/e9fbc832-3f6b-11e6-9313-9603178f2167.png)
![image](https://cloud.githubusercontent.com/assets/1481063/16496786/9c964d74-3ea8-11e6-9e5d-b0656a505b0b.png)
![image](https://cloud.githubusercontent.com/assets/1481063/16496823/c919e8f6-3ea8-11e6-848d-baa34e245584.png)
![image](https://cloud.githubusercontent.com/assets/1481063/16496853/f3b201f2-3ea8-11e6-9839-69cc4cee3de3.png)
- compression (and most others) had no version rev and were not altered.
- history was bumped as expected.
- react (and others) were "updated" with version range `^` added, but no change in version.
- react-router was legitimately updated, but version range `^` added

ref: mxstbr/react-router GK PR [#616](https://github.com/mxstbr/react-boilerplate/pull/616)

Thoughts, advice?

**Comment by finnp** [comment]
Hey @gihrig,

well it seems like this happened through a race condition where your pinning of the dependencies and the pull request happened around the same time. So the bot used the old version of your `package.json` when pushing that commit. This is definitely a bug.

In the meantime I suggest you merge the greenkeeper PR and remove the carets again.

**Comment by gihrig** [comment]
Makes sense. Indeed a later GK PR [#619](https://github.com/mxstbr/react-boilerplate/pull/619/files) appears as expected.

Thanks for responding :smile:
