### ISSUE TITLE
Inform authors when they release a breaking change

### ISSUE THREAD

**Issue by TheSavior** [greenkeeperio/greenkeeper#241]
Greenkeeper likely has data on what pull requests it opened as a result of a new version from a given package. It would be great if greenkeeper could detect when a new, non major, version came out that caused a high percentage of downstream greenkeeper updates to fail. 

Greenekeeper would then ideally open a github issue informing the library of the breaking change and the effect of that change.

I believe this would have a huge impact on resolution times for breaking changes across the entire npm ecosystem.

**Comment by boennemann** [comment]
Thanks for the suggestion.

With "Support "beta" and "next" dist-tags for real world testing and feedback" this is already part of our roadmap: https://github.com/greenkeeperio/greenkeeper/projects

I'll go ahead an close this issue, as the progress is already tracked on GitHub projects.

**Comment by TheSavior** [comment]
@boennemann, this is great to see and I'm super excited that it is part of the roadmap. Is there a better place to be able to continue discussion on this?

I just came across [this comment](https://github.com/nodejs/node/pull/12220#issuecomment-304695834) from the Node 8 release planning thread where the error messages on assertions are changing which could break some people who rely on those error messages. It reminded me of this thread and the power that an integration with greenkeeper would be in order to get initial feedback across the ecosystem on Node upgrades as a whole, not just package updates. 

I'd imagine the impact on Travis would be...non-trivial...but it would be a very valuable use case for the community. Is this something already being considered as part of that roadmap item?
