### ISSUE TITLE
GK messes with my versions

### ISSUE THREAD

**Issue by krainboltgreene** [greenkeeperio/greenkeeper#242]
https://github.com/krainboltgreene/abstraction.js/pull/7/commits/bf4514a725cc577b49b5ac070b45a1b7ee78e484

**Comment by finnp** [comment]
Hey @krainboltgreene,

Sorry, this is currently a bug in Greenkeeper and is already tracked here #103. Please subscribe to that issue to get updated about a fix. I'm closing this as a duplicate.

Note however that `^3` is semantically equivalent with `^3.0.0`.

Best,
Finn

**Comment by krainboltgreene** [comment]
I know that it's semantically equivalent, but the former makes it human clear what's going on. Thanks for the update!
