### ISSUE TITLE
received a notification for a version that does not currently exist in the npm registry

### ISSUE THREAD

**Issue by ashleygwilliams** [greenkeeperio/greenkeeper#244]
version `0.21.0` does not exist in the registry, see http://registry.npmjs.org/cheerio

greenkeeper PR here: https://github.com/npm/docs/pull/707
revert PR here: https://github.com/npm/docs/pull/711

i see version `0.21.0` in the `package.json` on github: https://github.com/cheeriojs/cheerio/blob/master/package.json

but `history.md` only has `0.20.0`: https://github.com/cheeriojs/cheerio/blob/master/History.md

anyways. weird stuff. lemme know if you need any more info!

**Comment by ashleygwilliams** [comment]
looks like `0.21.0` was published `"0.21.0": "2016-06-12T05:34:11.519Z"` ... and unpublished?

**Comment by boennemann** [comment]
Hey Ashley 👋

thanks for reporting this.
The whole behavior reminds of this issue we had before: https://github.com/greenkeeperio/greenkeeper/issues/156

My stance from back then (March 31) was this:

> I just tried to publish a completely new package and to unpublish a few versions to see what the metadata looks like, but unpublish is completely broken for me right now. First I couldn't unpublish anything at all and then I managed to unpublish something, but it was possible to republish the exact same version again.

> When looking at the metadata while the version was still unpublished it didn't show up in versions at all.

> I suspect that these bugs are caused by some internal restructurings npm is currently performing in order to implement their new unpublish policy.

> #157 seems a bit drastic to me, especially given that color@0.12.0 apparently wasn't unpublished, but an npm bug. Given the new policy we will see far less unpublishes in the future. With the old policy in place this problem hasn't occurred for Greenkeeper even once.

> Here is my current stance on this: No action required. npm will fix these bugs. Unpublishes will occur very, very rarely. If so they aren't necessarily for newest versions that Greenkeeper acts upon. Delaying the entire service for 24hours does not seem appropriate to me.

> Happy to change my mind if we see these things happen again.

> Thanks for reporting and your feedback everyone! We're sorry for any inconveniences.

Could you comment on whether this evaluation still seems appropriate?

Thanks a lot,
Stephan

**Comment by boennemann** [comment]
We should probably also await a comment here: https://github.com/cheeriojs/cheerio/issues/888

**Comment by ashleygwilliams** [comment]
hey @boennemann - so npm isn't doing anything with the metadata due to the new unpublish policy, but i'm open to the idea that we should.

https://github.com/greenkeeperio/greenkeeper/issues/157 <- this makes a lot of sense given our unpublish policy.

https://github.com/greenkeeperio/greenkeeper/issues/156<- if you look at http://registry.npmjs.org/color you'll see that `0.12.0` shows up in the `time` object, but not the `versions` object. this is what an unpublished package looks like on npm- so it isn't an error, but actually behaving as expected

**Comment by ashleygwilliams** [comment]
so yeah, not entirely sure what should be done, but if greenkeeper doesn't wait 24hrs after publish, it will make PRs that could potentially be invalid as the package can be unpublished within that window. does greenkeeper follow unpublish events? this is another way to avoid waiting 24hrs.

**Comment by ashleygwilliams** [comment]
(also as always: yay greenkeeper is awesome keep up the awesome work)

this issue isn't a huge deal as people rarely unpublish, but it's probably worth thinking about (basically this is not a :fire: so no rush)

**Comment by boennemann** [comment]
I suspected some bugs back then, because [I managed to republish](https://twitter.com/boennemann/status/715599940286824448) and the `color` maintainer [commented](https://github.com/greenkeeperio/greenkeeper/issues/156#issuecomment-204033664) that they haven't unpublished anything.

In the current `cheerio` case it looks like a regular (accidental maybe?) unpublish.
In this case I think the best experience would be to close these PRs as soon as we know a version was unpublished. We currently keep track of all versions we have previously processed, so it should be possible to detect unpublishes as soon as we see a version that was previously processed but is no longer in the versions object.

I can't promise the highest priority for this, but it's something we should add in the future.

Thanks for your lovely words! We <3 your work, too ✨

**Comment by mysterycommand** [comment]
This is also happening to me. More info here: https://github.com/mysterycommand/fartts/pull/15#issuecomment-372787964

**Comment by janl** [comment]
We talked to the npm team and they suggest adding a delay on our end to account for variability on theirs. This is a change in policy and guidance from the last time we discussed this with them. We’ll implement the delay shortly.

**Comment by janl** [comment]
This is currently being tested in our staging environment and will be deployed with the next roll-out to production.
