### ISSUE TITLE
Ignore versions outside `^` for a specific module

### ISSUE THREAD

**Issue by watson** [greenkeeperio/greenkeeper#245]
I have a project with `inquirer` being a `devDependency`. The version is set to `^0.12.0` in package.json. Greenkeeper opened a pull request because a newer major version exists: `1.1.1`.

The tests doesn't fail on this because we only use `inquirer` as part of a CLI used during development. But the CLI code will not work with `1.1.1` since v1.x switched to a Promise API 💀 - so obviously we don't want to upgrade and will most likely always keep this on v0.x.

So my questions are:

- What should I do with the PR?
- If I close it will I keep getting new PR's when ever a new v1.x version is created?
- Is there a way I can disable this behaviour?
- Is there way I can keep getting PR's if a version that matches `^0.12.0` is released?

**Comment by finnp** [comment]
Hey @watson,

for now you're only option would be to ignore all updates for  the `inquirer` module, by adding this to your `package.json`:
```json
"greenkeeper": {
  "ignore": ["inquirer"]
}
```

Right now we're only tracking updates of the `latest` tag of a module. Updates to the `v0.x` would probably be published with another `dist-tag` (see #208) and therefore you wouldn't get updates anyway. However we're planning on supporting those as well. Then we'll see if we can support your use case better.

**Comment by watson** [comment]
@finnp Thanks :) This is a fine solution in this particular case as it's just a devDependency. So it's not really that important to be notified about patches.

**Comment by dschep** [comment]
We also have this same issue because of `react-router@4.0.0` and I imagine many other people do too. It'd be nice if something like this were possible:
```json
"greenkeeper": {
  "ignore": ["react-router^4.0.0"]
}
```
