### ISSUE TITLE
Struggling to find the value in GreenKeeper

### ISSUE THREAD

**Issue by gihrig** [greenkeeperio/greenkeeper#247]
Having recently engaged GK for [react-boilerplate](https://github.com/mxstbr/react-boilerplate/), we're climbing the learning curve... Reference GK issues #126, #137, #163. Also react-boilerplate [#598](https://github.com/mxstbr/react-boilerplate/issues/598)

The present issue is dealing with multiple GK PRs. This seems problematic based on the rate of advance inherent in our dependency set.

Consider that within 24 hrs the following scenario is typical.

0 - is our current react-boilerplate version
1 - dependency 1 is updated, GK, Travis and AppVeyor build/test against 0
2 - dependency 2 is updated, GK, Travis and AppVeyor build/test against 0
etc... typically 6 - 8, so far in a 24 hr period.

from @boennemann's [#137 comment](https://github.com/greenkeeperio/greenkeeper/issues/137#issuecomment-209617514)

> Whenever you merge a Greenkeeper PR we'll automatically reapply the other open PRs against the latest changes of the base branch.

This make perfect sense, but creates an untenable workflow. Now I merge the GK PR for dep 1. This changes our project base version 0 to 0.1 and triggers a reapplication of PRs for dep 2, 3, 4, ... with commensurate build/test cycles, and so on for each updated PR...

This makes merging PRs from GitHub impractical as our build test process with Travis and AppVeyor can take more than an hour on each iteration. At present, `npm outdated` lists 27 packages, it seems that GK just won't be able to catch up.

That gets us to @focusaurus's [#126 comment](https://github.com/greenkeeperio/greenkeeper/issues/126#issuecomment-189021305)

> I can now usually do something like this:
> 
> scan list of all open PRs
> bulk select any not-the-latest-version-PRs and close them
> proceed through the remaining reverse chronologically and merge and delete (I think this usually works without conflicts but haven't had enough instances to say for sure)
> That sort of works.
> 
> However, FYI it's a pain so I've decided in cases where there's more than a few backlogged PRs, to just use command line npm-check-updates to handle it and bulk close all the greenkeeper ones.
> 

So, the solution to multiple update PRs seems to be to bypass GK entirely and do a manual `npm outdated`, edit `package.json` and create a project PR against that, which runs our Travis and AppVeyor build test cycle. I could develop a script to automate this process, but then I would have re-invented GreenKeeper (sort of, more or less) ;-)

I understand there is risk in doing bulk updates, like discovering which package is responsible for breaking the build and fixing, excluding it, etc., but a once every 24 hrs bulk update process seems more practical, though I have not tried this.

Am I just doing it wrong?

**Comment by gihrig** [comment]
Just did a full dependency (local) update. One thing broke, and several warnings appeared on the browser console in execution...

Not a nice, or quick experience.

For now, I'll try keeping up with GK. My concern is, given the time (hrs) required for travis/AppVeyor to cycle, can the GK/Travis/AppVeyor process keep up with changes from the community?

Still learning...

**Comment by gihrig** [comment]
Completed local update, test PR, test, merge cycle. All seems to be good. All deps up to latest.

Will see what GK has to say tomorrow. Won't have time to devote to updates until Monday am (PDT), will see what it looks like then.

**Comment by gihrig** [comment]
I see that GK eats own dog food (good on you guys) and has a string of multiple [open GK PR](https://github.com/greenkeeperio/greenkeeper/pulls)s. How do you guys deal with this?

**Comment by gihrig** [comment]
After a couple of weeks, I decided that GK is more trouble than it's worth. Maybe it's the nature of the project to have too many dependency updates, maybe it's because we're pinning dependencies or maybe I'm just doing it wrong...

Good Luck GK (seriously)

**Comment by hairyhenderson** [comment]
> maybe it's because we're pinning dependencies

That'll certainly cause frustration... In my experience, GK is most effective when you're using semver ranges. One side-effect of this is you tend to get security patches "for free".

If you have _good reasons_ for pinning dependencies, then be prepared for this sort of frustration, whether or not you use a tool like GK, since your dependencies are pretty much going to be constantly out of date. If you don't have _good reasons_, consider using semver ranges.

**Comment by gihrig** [comment]
@hairyhenderson Thanks for the wisdom. 

The logic behind pinned deps was that we have experienced project breakage a couple of times due to in-range updates which were errors on the part of dependent devs. At least we know what  we are getting with each new install.

Many trade-offs.

**Comment by hairyhenderson** [comment]
> project breakage a couple of times due to in-range updates which were errors on the part of dependent devs

Exactly the reason I use greenkeeper :grin:
