### ISSUE TITLE
Unable to install due to `'@greenkeeper/flags' is not in the npm registry.` error

### ISSUE THREAD

**Issue by EvNaverniouk** [greenkeeperio/greenkeeper#252]
I am unable to install `greenkeeper` on Mac OS. Getting the following from `npm`

```
npm install -g greenkeeper
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "greenkeeper"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code E404

npm ERR! 404 no such package available : @greenkeeper/flags
npm ERR! 404 
npm ERR! 404  '@greenkeeper/flags' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'greenkeeper'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/evgueni.naverniouk/Git/ux/npm-debug.log
```

**Comment by finnp** [comment]
Hey @EvNaverniouk,

the module is [published in the npm registry](https://www.npmjs.com/package/@greenkeeper/flags). Are you using a mirror for the npm registry (scoped packages are currently not available from mirrored registries)?

**Comment by EvNaverniouk** [comment]
Ah, yes, I have npm pointing to a local sinopia registry.

Is there a particular reason for using `@greenkeeper/flags` as the package dependency name? Greenkeeper is the first library I've encountered that does this.
