### ISSUE TITLE
File a weekly PR

### ISSUE THREAD

**Issue by jasonLaster** [greenkeeperio/greenkeeper#253]
When GK is enabled, it's typical to get a lot of PRs.

It'd be nice if there were an option to set a regular interval, i.e. check every monday and file a PR if dependencies have changed.

<img width="723" alt="screen shot 2016-07-27 at 11 17 57 am" src="https://cloud.githubusercontent.com/assets/254562/17180813/b034c4ac-53eb-11e6-9d2a-4b124eff3553.png">

**Comment by emschwartz** [comment]
Weekly could be nice, or even just having GK update a single PR with all of the relevant changes until you merge it

**Comment by janl** [comment]
Single-PR defies the purpose of knowing which dependency update broke the build.

From the screenshot above I can tell that most of these PRs could be avoided by using version ranges instead of pinned dependencies.

See https://blog.greenkeeper.io/announcing-real-time-dependency-break-detection-for-greenkeeper-4f7558c10d77 how this works and at the same time ensures against the downsides of version ranges.

Hope this helps :)

**Comment by iamstarkov** [comment]
@janl it helps to understand the problem of *ranged vs pinned* deps, but mass pr bombing is still an issue

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations. You can try it out today: https://github.com/integration/greenkeeper

There are several changes that affect this feature request.
1. GitHub no longer sends eMail notifications for PRs created by bots
2. We will now only create a single PR (out of range) or Issue (in range) per dependency at a time, and keep that up to date with comments. The noise should be greatly reduced.

We think that these changes make this feature requests unnecessary, but we're happy to reconsider once you've tried it.

Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
