### ISSUE TITLE
False Negative

### ISSUE THREAD

**Issue by hjdivad** [greenkeeperio/greenkeeper#256]
https://github.com/ember-cli/ember-cli/pull/6138 claims that fs-tree-diff@0.5.1 (from 0.5.0) breaks the ember-cli build.  But the [build itself](https://travis-ci.org/ember-cli/ember-cli/builds/149038101) for [that commit](https://github.com/ember-cli/ember-cli/pull/6138/commits/dcaefb18622499b0b04fd0bacc32cb35f40f0eda) is green.

Is this something weird on our end?

**Comment by finnp** [comment]
Hey @hjdivad,

yes this seems odd. It might be that one of your CI services reported a `failed` status to the commit at one point and then later changed it to `success`. This could happen for example, when a travis build is re-run.

We currently do not track the history of the build statuses, so I can't tell for sure that this is the reason. But GitHub keeps a list of recent webhooks deliveries, where we get the CI status from. If you want to help out with this, please go to the [webhooks settings of your repos](https://github.com/ember-cli/ember-cli/settings/hooks) and then click on `https://api.greenkeeper.io/webhooks/github`.

Down at the bottom you will find a list of "Recent Deliveries", if you click on one if the hashes they'll expand. Then look for ones with the `X-GitHub-Event: status` in the header and `"sha": "dcaefb18622499b0b04fd0bacc32cb35f40f0eda"` (for the commit) in the Payload. If there are any that also have `"state": "failure"` in the Payload, that would be good to know :)

**Comment by hjdivad** [comment]
Okay I found the delivery you were asking for (details below).  It occurred at 2016-08-01 17:28:45.  There was an earlier delivery (93109b80-583c-11e6-9979-b8a21402fab6) that failed at 2016-08-01 16:06:27.

I can't quite verify in the travis UI but it certainly looks like there was an initial build that reported a failure followed by a rebuild that I at least was not expecting.

It seems there is not actually a bug.  Handling rebuilds more gracefully would obviously be a nice feature, but it's one I imagine you've already thought of. ^_^

## Success Delivery

### delivery
`12579c80-5848-11e6-952e-0e0433c8efa4`

### headers
```
Request URL: https://api.greenkeeper.io/webhooks/github
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/5a08997
X-GitHub-Delivery: 12579c80-5848-11e6-952e-0e0433c8efa4
X-GitHub-Event: status
X-Hub-Signature: sha1=8a3042fc0893701fa2dd6ec52ec450ecb4465b22
```

### payload
```json
{
  "id": 678781781,
  "sha": "dcaefb18622499b0b04fd0bacc32cb35f40f0eda",
  "name": "ember-cli/ember-cli",
  "target_url": "https://greenkeeper.io/verify.html",
  "context": "greenkeeper/verify",
  "description": "Greenkeeper verified pull request",
  "state": "success",
  "commit": {
    "sha": "dcaefb18622499b0b04fd0bacc32cb35f40f0eda",
    "commit": {
      "author": {
        "name": "greenkeeperio-bot",
        "email": "support@greenkeeper.io",
        "date": "2016-08-01T22:51:29Z"
      },
      "committer": {
        "name": "greenkeeperio-bot",
        "email": "support@greenkeeper.io",
        "date": "2016-08-01T22:51:29Z"
      },
      "message": "chore(package): update fs-tree-diff to version 0.5.1\n\nhttps://greenkeeper.io/",
      "tree": {
        "sha": "54b5e0729481f5a96d3e7743e7c4bbd1019188d6",
        "url": "https://api.github.com/repos/ember-cli/ember-cli/git/trees/54b5e0729481f5a96d3e7743e7c4bbd1019188d6"
      },
      "url": "https://api.github.com/repos/ember-cli/ember-cli/git/commits/dcaefb18622499b0b04fd0bacc32cb35f40f0eda",
      "comment_count": 0
    }
  // snip
}
```

## Failure Delivery

### delivery
`93109b80-583c-11e6-9979-b8a21402fab6`

### headers
```
Request URL: https://api.greenkeeper.io/webhooks/github
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/5a08997
X-GitHub-Delivery: 93109b80-583c-11e6-9979-b8a21402fab6
X-GitHub-Event: status
X-Hub-Signature: sha1=30de4144a46a8e56d2afa12b0af7cc685285f54a
```

### body

```json
{
  "id": 678669426,
  "sha": "dcaefb18622499b0b04fd0bacc32cb35f40f0eda",
  "name": "ember-cli/ember-cli",
  "target_url": "https://travis-ci.org/ember-cli/ember-cli/builds/149038101",
  "context": "continuous-integration/travis-ci/push",
  "description": "The Travis CI build failed",
  "state": "failure",
  "commit": {
    "sha": "dcaefb18622499b0b04fd0bacc32cb35f40f0eda",
    "commit": {
      "author": {
        "name": "greenkeeperio-bot",
        "email": "support@greenkeeper.io",
        "date": "2016-08-01T22:51:29Z"
      },
      "committer": {
        "name": "greenkeeperio-bot",
        "email": "support@greenkeeper.io",
        "date": "2016-08-01T22:51:29Z"
      },
      "message": "chore(package): update fs-tree-diff to version 0.5.1\n\nhttps://greenkeeper.io/",
      "tree": {
        "sha": "54b5e0729481f5a96d3e7743e7c4bbd1019188d6",
        "url": "https://api.github.com/repos/ember-cli/ember-cli/git/trees/54b5e0729481f5a96d3e7743e7c4bbd1019188d6"
      },
      "url": "https://api.github.com/repos/ember-cli/ember-cli/git/commits/dcaefb18622499b0b04fd0bacc32cb35f40f0eda",
      "comment_count": 0
    }
  // snip
}
```

**Comment by hjdivad** [comment]
@finnp Seems like this is not a bug, but rather a feature request.  Closing in favour of #257.

**Comment by finnp** [comment]
@hjdivad Thank you for looking into this! Yes, this is something we should improve on.
