### ISSUE TITLE
Update PR status on CI rebuilds

### ISSUE THREAD

**Issue by hjdivad** [greenkeeperio/greenkeeper#257]
Sometimes a greenkeeper build will fail for uninteresting reasons (such as CI npm cache not updated; other root-cause modules getting publishes &c.).  If CI builds are re-run for a greenkeeper pr and turn green, the greenkeeper PR should reflect that.

See #256 as an example.

**Comment by foopoiuyt** [comment]
This would be a nice enhancement since we end up with a scary looking PR message about things being broken and successful build status.
