### ISSUE TITLE
Mention on Totally Tooling Tips

### ISSUE THREAD

**Issue by gauntface** [greenkeeperio/greenkeeper#258]
Hi,

I wanted to see if it was ok to mention Green Keeper on a Totally Tooling Tips episode.

(See here for examples: https://www.youtube.com/watch?v=IWgNn1kqrsA&list=PLOU2XLYxmsILKwwASNS0xgfcmakbK_8JZ)

Kind Regards,
Matt

**Comment by finnp** [comment]
Hey @gauntface,

yes sure! That sounds great. Let us know if you have any questions about it.

Best,
Finn

**Comment by gauntface** [comment]
Thanks a lot Finn :)
