### ISSUE TITLE
Ability to disable "new pull request" emails

### ISSUE THREAD

**Issue by miksago** [greenkeeperio/greenkeeper#26]
I'm finding that I'm getting two emails for each PR that gets made automatically:

1. Greenkeeper
2. Standard Github PR emails

I also get pull request creation events in slack from github.

The Greenkeeper emails seem like extra noise to me, and I'd really like to turn them off.

**Comment by boennemann** [comment]
I'm happy to tell you that this just landed.

Add `"greenkeeper": {"emails": false"}` to your package.json and gone they are.

Best,
Stephan
