### ISSUE TITLE
Reach 5000 requests/ hours rate limit on Github

### ISSUE THREAD

**Issue by ume-integration** [greenkeeperio/greenkeeper#263]
Hello,

Currently , we are using Greenkeeper to update version. When the Greenkeeper create a PR, Our CI will run unit test and update the result on PRs on Github.

However, we have a problem when the developer publish version in short time . The our jenkins reach 5000 requests. Do the greenkeeeper have any scheduler to create a PRs. 

For example: If Greenkeeper receive 50 events to update the version. However, the greekeeper will queue 50 events, then the greenkeepr will create 10 PRs every hours.
What do you think about that ? 

Regards,
Khoa Nguyen.

**Comment by ume-integration** [comment]
I asked the github to increase rate limit . However, they rejected because they suggest we should ask greenkeeper for optimize their application.

Can you take a look at this issue ?

Hi Khoa,

Thanks for reaching out again. As we mentioned 2 months ago when you first reached out -- we can't offer a better rate limit. The traffic from that greenkeeper application is extremely spiky, and traffic spikes are a performance and availability concern on our end. Just to give you an example, in the period of two minutes, that application made ~3000 requests, sometimes making over 100 requests per second. That kind of behavior will drain your quota really fast regardless of what that quota is (it will drain your quota even if we did give you a 10000 reqs/hour rate limit).

The current limits help us keep the API fast and reliable for all our users and applications, not just one. For the same reason, hitting the API rate limit shouldn't be considered abnormal -- it's a core part of using the API and the API returns information about your remaining quota and when it will refresh with every response. You (or the integrations you use) can use that either to pace your processes so that you never hit the limit, or sleep until the limit refreshes if you do hit it and notify users.

I recommend that you reach out the the maintainers of greenkeeper and ask them to modify the application so that it spreads out the requests a bit more instead of making 3000 requests within two minutes. If this behavior from one of the applications you use is causing problems for you and other applications, you can also revoke access from that problematic application temporarily while they optimize their usage.

I hope this answers your question, but let me know if there's anything else.

Best,
Ivan

**Comment by boennemann** [comment]
Hey @ume-integration,

thanks for reaching out.
This indeed looks like a problem and we're currently looking into establishing such a mechanism.

We'll let you know once we've got sth. ready in this issue.

Best,
Stephan

**Comment by ume-integration** [comment]
@boennemann : Thanks .

**Comment by finnp** [comment]
Hello @ume-integration,

we recently deployed a fix in our system that will respect the GitHub rate limiting better. However it is likely that in your case the problem hasn't been too many Greenkeeper requests but instead a Jenkins plugin bug, documented here https://issues.jenkins-ci.org/browse/JENKINS-36121. Someone already submitted a patch for this, so I'll hope this will be fixed soon.

You might be able to fix your issues for now by editing your Jenkins webhooks for each repository and change `Send me everything` to `Let me select individual events` and then select `Pull request` and `Push`.

Best,
Finn

**Comment by ume-integration** [comment]
Hi Finn,

Thank you for your reply. However, We didn't use `GitHub Branch Source
Plugin
<https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Branch+Source+Plugin>`
plugin.

Let me enable again all repos and see what happen.

Regards,
Khoa Nguyen.

**Comment by boennemann** [comment]
Hey @ume-integration,

how did our update turn out for you? Any updates? Does it work again, or could the Jenkins issues be resolved?

Best,
Stephan

**Comment by ume-integration** [comment]
Hi Stephan,

It is good so far. Thank you very much.

Regards,
Khoa Nguyen.
