### ISSUE TITLE
Report the old version of the dependency

### ISSUE THREAD

**Issue by cchan** [greenkeeperio/greenkeeper#265]
For example, instead of just `greenkeeper@0.5.6` it should be `greenkeeper@0.5.4 => greenkeeper@0.5.6`.

**Comment by lukechilds** [comment]
Just came here to say this too. It would also be great if it said what SemVer range was being bumped.

For example in this PR: https://github.com/lukechilds/node-browser-environment/pull/9 I have to check the diff to see that it is updating from 6.9.0 to 6.14.0 and that it's a minor SemVer bump.

It would be great if you added to the table:

State | Update 🚀 
---|---
SemVer Bump | Minor
Previous version | 6.9.0
New version | 6.14.0

**Comment by boennemann** [comment]
Thanks for suggestion.

We're considering this, please track the status here https://github.com/greenkeeperio/greenkeeper/issues/77
