### ISSUE TITLE
Add feature to delete all greenkeeper branches

### ISSUE THREAD

**Issue by kellyselden** [greenkeeperio/greenkeeper#272]
greenkeeper branches keep stacking up with no associated pull requests
```
E:\Code\package-hint-historic-resolver>git branch --remote
  heroku/master
  origin/ember-cli-code-coverage
  origin/eslint
  origin/greenkeeper-broccoli-asset-rev-2.4.6
  origin/greenkeeper-ember-ajax-2.5.0
  origin/greenkeeper-ember-ajax-2.5.1
  origin/greenkeeper-ember-browserify-1.1.12
  origin/greenkeeper-ember-cli-app-version-1.0.1
  origin/greenkeeper-ember-cli-babel-5.1.10
  origin/greenkeeper-ember-cli-babel-5.1.8
  origin/greenkeeper-ember-cli-babel-5.1.9
  origin/greenkeeper-ember-cli-htmlbars-1.0.11
  origin/greenkeeper-ember-cli-htmlbars-1.1.0
  origin/greenkeeper-ember-cli-htmlbars-inline-precompile-0.3.4
  origin/greenkeeper-ember-cli-htmlbars-inline-precompile-0.3.5
  origin/greenkeeper-ember-cli-sri-2.1.1
  origin/greenkeeper-loader.js-4.0.11
  origin/master
  origin/mirage
  origin/percy
  origin/refactor
  origin/test
```

Maybe it's because the versions are in the allowed semver range? Anyways, it would be great if, from the command line, I could just blow away all the greenkeeper remote branches. Maybe `greenkeeper purge` or something?

**Comment by boennemann** [comment]
Hey @kellyselden,

thanks for this report. I'm hesitant to add such a command, because this scenario is definitely not the way things are supposed to be.

We'll investigate what has happened here. Sorry for this inconvenience.

Best,
Stephan

**Comment by finnp** [comment]
Hey @kellyselden,

your tests only run for the master branch. However for in-range updates, greenkeeper creates a branch, waits for the status to reported and only creates a pull request if the CI fails.  You should whitelist greenkeeper branches by adding `- /^greenkeeper.*$/'` to your [.travis.yml](https://github.com/kellyselden/package-hint-historic-resolver/blob/greenkeeper-ember-browserify-1.1.12/.travis.yml#L8). Then greenkeeper will work properly again.

Best,
Finn

**Comment by kellyselden** [comment]
@finnp Makes a lot of sense. Is this a documented gotchya? I can add it if it's not. Thanks.
