### ISSUE TITLE
Changing who commits

### ISSUE THREAD

**Issue by gergelyke** [greenkeeperio/greenkeeper#274]
Hey,

originally, i have connected my account for Greenkeeper - as we are using an org plan, we want to use a "Bot" user. How can I upgrade our integration, so all our repos use the bot to commit?

Thanks,

**Comment by boennemann** [comment]
Hey @gergelyke,

great to see you're using Greenkeeper :) We're using the enabler of the repository to open PRs.
Log into Greenkeeper (cli or https://app.greenkeeper.io/) and authenticate with the GitHub bot account. (Re-)enable repos with this user and their account will be used to open PRs.

We're looking into an explicit way to set this user for the future.

Best,
Stephan

**Comment by felixfbecker** [comment]
Codecov is able to post as a bot even for private repos, any specific reason why Greenkeeper needs a user account?

**Comment by finnp** [comment]
Hey @felixfbecker, with our [new integration](https://github.com/integration/greenkeeper) our bot-user takes care or private repositories as well.

**Comment by felixfbecker** [comment]
@finnp I activated that, but PRs are still opened from my account
