### ISSUE TITLE
Feature request: setup a repository without having to grant access at organisation level

### ISSUE THREAD

**Issue by jmfrancois** [greenkeeperio/greenkeeper#281]
I'm in a context where the CLI just don't works.
I'm member of a github organisation: [Talend](https://github.com/Talend)
I'm admin of a repository on that organisation: [react-cmf](https://github.com/Talend/react-cmf)

What ever I'm trying to do I just can't enable the repository.
Administrators of talend organisation do not want to allow greenkeeper on the organisation level.

Because I'm administrator of the repository I can setup all the things step by step in the settings tab of this repository.

The documentation to [setup webhooks manually](https://greenkeeper.io/manual-webhooks.html) exists but it doesn't work for me:

* greenkeeper login --force --no-admin -> ok
* greenkeeper enable --slug Talend/react-cmf -> KO

```
🌴  ERR! enable Couldn’t enable a repository with slug Talend/react-cmf.
# Enabling a repository
Most of the time enabling a repository is straight forward – just execute greenkeeper enable.
In some cases, especially when there are private repositories or permissions involved, it can fail.
Fear not. This guide will walk you through all the required steps.
If you can’t get your repository enabled after these steps please contact us. greenkeeper support



    1. If you want to enable a private repository for the first time make sure to grant Greenkeeper the necessary rights by running greenkeeper login --force --private.
    2. With GitHub’s new permission model you need to grant Greenkeeper access per organization. You can do this with greenkeeper access.
    3. Keep in mind that you need admin access to a repository to enable it. If you don’t have access please ask someone on your team for help.
```

But the documentation said:

```
Once the login is completed you can enable repositories as usual. Detailed instructions on how to setup the hooks will follow after you have enabled a repository.

greenkeeper enable --slug user/repo
Please note that you still need admin access to a repository to setup Greenkeeper. The only difference is that you don’t need to grant that access to us.
```

So what happens ? This is an issue because I should be able to do that at the moment and I can't.

Using verbose mode here is what I have:

```
🌴  verb enable Repository not found. Starting a sync.
🌴  info enable Synchronizing your repositories. This might take a while.
🌴  verb enable Repository not found after sync.
```

Any idea ? Is this can be a bug ?

**Comment by finnp** [comment]
Hi,

the way you describe it, it seems like you didn't grant Greenkeeper the right to see the repositories in the Talend organization. In the CLI, you need to run `greenkeeper access` and then click `Grant access` for the Talend organization. After that enabling the repository should be possible.

​Let me know in case this doesn't work out for you.

Best,
Finn

**Comment by jmfrancois** [comment]
greenkeeper access is the thing I don't want because it request for access at organisation level.
What I would like is to setup per repository.

I really think this is a change in the way greenkeeper enable the repository. Why do we need to list all existing repository when I need to activate one ?

I mean I use --slug=username/reponame but the CLI still try to list the repositories. This is where it fails.

We should try to accept enable per repository with good documentation on how to setup it up.

I will try to find time to investigate this a bit more.

**Comment by jmfrancois** [comment]
So I have read the code of the CLI.
Most of the interesting part appear on server side which is not on github AFAIK.

The following request in enable.js

```javascript
      request({
        method: 'POST',
        url: flags.api + 'packages',
        json: true,
        headers: {
          Authorization: 'Bearer ' + flags.token
        },
        body: {slug: slug, manual_webhooks: flags.admin === false}
      }
```
return the following results:
```
🌴  info enable { statusCode: 400,
🌴  info enable   error: 'Bad Request',
🌴  info enable   message: 'could not enable package' }
```

As mentionned by the CLI :
```
With GitHub’s new permission model you need to grant Greenkeeper access per organization.
```

So greenkeper can't do pull request to a repository without having some access to organisation ?
I don't undetstand that. It just need to do pull request. All the rest is to provide easy setup. Both solutions should be provided. For example we use travis servis without any troubles, I just can't activate a repository throw the CLI but I can by adding the webhook settings on the given repository.

So this is a feature request: Please provide a setup step by step for a repository without access to the github organisation.

**Comment by bd82** [comment]
I am also interested in this feature as I want to enable greenkeeper for my repository **only** which is under an Organization I have very little control of...

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved. You can grant permissions based on an organisations and even repository level. It is no longer required to grant us admin access.

You can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
