### ISSUE TITLE
Handling multi-releases from monorepos

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#283]
For example, PouchDB went monorepo which is great. We can now more granularity add the modules to our dependencies that we need and leave out things we don’t. A side effect of that are things like these though:

<img width="731" alt="screenshot" src="https://cloud.githubusercontent.com/assets/39992/18254886/99155256-7357-11e6-9bee-6884c8a82941.png">

I just created the issue to start a discussion if someone has a trick on how to work with these

**Comment by gr2m** [comment]
A related problem is that I’ve setup semantic-release, and each time I merge a dependency (not devDependency) I change the commit message to `fix(package): ...` so that a new patch version gets released, to avoid different dependency versions in people’s app dependency trees.

If I merge all these one-by-one, they would all create separate versions. 

My suggestions for this (and maybe related cases) would be to add a feature to the web application which would allow me to merge multiple pull-requests at once, with only one commit. That would also create a single commit and only a single patch version.

**Comment by gr2m** [comment]
Oh-oh, to add to this problem with monorepos updates: tests likely fail because the modules are often times interdependent. For example this build fails not because there is an issue, but because all the other sibling dependencies are still on the old major version: 
https://github.com/nolanlawson/pouchdb-adapter-fs/pull/21

**Comment by gr2m** [comment]
I have an idea: we can identify monorepo modules by checking the `repository` field in package.json. As far as I know, Greenkeeper caches all package.json files, so we should be able to identify that.

So if a dependency updates and it’s name is different than the repository name, we could check all other dependencies if any of them has the same repository URL (and probably are on the same version or version range). If there are any, update them all at once, in one PR

**Comment by nolanlawson** [comment]
FWIW now that we're using @boennemann's alle technique, Greenkeeper "just works"

**Comment by nolanlawson** [comment]
As for the problem of getting flooded with GK pull requests, though, we don't really have a good solution for that. I agree it's awkward.

**Comment by boennemann** [comment]
One idea that comes to mind: How about package authors can group their modules together, or tell whether their module belongs to another one (think plugins). Either via our API, or via a to be defined package.json field. Using Gregor's approach sounds cool, too, but would be limited to monorepos.

Now whenever a grouped module updates we wait a certain amount of time whether some other module in the group updates as well. Grouped modules will then be sent out as a single PR.

So for this case all `pouchdb-*` modules should be grouped. We wait for 5 minutes (we're doing that already because npm CDN problems #60). All updates are aggregated and sent as a single PR.

If we introduce something like this I really like the approach of letting module authors set this up, because then it's not a config that has to be done over and over again. "It just works" for users.

**Comment by nolanlawson** [comment]
I'm fine with that; maybe a "greenkeeper" field in the top-level package.json?

**Comment by gr2m** [comment]
> Using Gregor's approach sounds cool, too, but would be limited to monorepos

Can you think of any valid cases beyond monorepos? I think the idea with using the repo field is elegant becaues it’s either already there or adding it should be no big trouble as it’ll have other benefits, too

**Comment by gr2m** [comment]
It’s really bothering now, we get failed builds for each patch release, although there is no problem if all dependencies belonging to the monorepo would be updated in the same PR

<img width="745" alt="screen shot 2016-09-17 at 12 18 27" src="https://cloud.githubusercontent.com/assets/39992/18610430/17825d0a-7cd1-11e6-848b-bdd9531a89e7.png">

**Comment by nolanlawson** [comment]
I'm really sorry about that, @gr2m. If it's any consolation, I got a ton of spam too. :(

@boennemann Maybe an optimization could be this:

1. Check which packages were updated in last ~5 minutes
2. Check if the publisher is the same person
3. If so, group them all together.

Could that work? Our build script takes ~30 seconds to do all the `npm publish`es, FWIW.

**Comment by gr2m** [comment]
not your fault at all @nolanlawson no reason to feel bad :) 

I still think the best property that we can use for that is the package.json’s `repository` field. PouchDB already uses the same value for all repositories released from the monorepo: https://unpkg.com/pouchdb-core@6.0.5/package.json

I’m not sure if the same person is a good idea. We have a bot user that does all the releases at Hoodie, and sometimes we have multiple releases of different packages within a short amount of time.

I think using the `repository` property and a timeout is our best bet? If the repository field is missing in packages belonging to a monorepo it would make sense to add it anyway to the project

**Comment by boennemann** [comment]
@nolanlawson @gr2m After thinking a bit more about it I have to agree with Gregor here – the repository field really makes a lot of sense here.

On our roadmap we have to prioritize to properly integrate with GitHub through their new "Integrations". I hope we can tackle this problem afterwards.

**Comment by jedwards1211** [comment]
@boennemann regardless of some projects being in monorepos, I wish that greenkeeper would periodically make a single PR to my project with all dependencies updated (to latest semver-compatible version), and only make single-package PRs for major releases.

I'm already using greenkeeper in a number of projects and with individual PRs for each package upgrade, it comes out to hundreds of PRs.  To make matters worse, if I've added or removed deps to a project, many of these PRs can wind up having pesky merge conflicts.

I've been thinking about writing a script on my local machine to go through my projects and run `npm upgrade`, then make a PR instead...

**Comment by jedwards1211** [comment]
@gr2m so you're saying the pouchdb packages are often interdependent and it causes build failures, but couldn't those dependencies be reflected in each pouchdb package anyway, so that upgrading just one causes the others it interacts with to be upgraded to something compatible?

**Comment by jedwards1211** [comment]
@gr2m I wonder if using `optionalDependencies` would solve the problem?  I'd think npm has some way of specifying that a package only works with version X of package Y if it's present.

Also I'm not talking about separate PRs for each upgrade vs one PR per dependency, I'm saying instead of one PR per dependency I'd like as many dependency upgrades as possible in a single PR, which should be fine as long as all the upgrade deps in that PR are semver-compatible.

**Comment by gr2m** [comment]
I see what you are asking for, but I think it’s off topic, can you create a separate issue please? This issue is specifically about the case where multiple package release are coming from a monorepo setup at the same time like from PouchDB for example, your request is much broader

**Comment by jedwards1211** [comment]
Yeah, fair enough

**Comment by janl** [comment]
https://blog.greenkeeper.io/announcing-greenkeeper-3-1504f5113998
