### ISSUE TITLE
[Feature request] Greenkeeper config

### ISSUE THREAD

**Issue by kunagpal** [greenkeeperio/greenkeeper#288]
Using a file like `.gkeeperrc`, or `.gkeeper.yml` within a target repository, one could specify additional configuration options, including, but not limited to:

* Blocking updates on certain packages, for a wide variety of reasons
* Specifying update sensitivity. For instance, a sensitivity setting of `minor` would only trigger PRs for a minor release to a specified dependency / all dependencies

**Comment by finnp** [comment]
Hey,

**Comment by kunagpal** [comment]
Thanks! Didn't see that earlier.

**Comment by finnp** [comment]
We only recently added it to the documentation ☺️

**Comment by kunagpal** [comment]
Is it possible to have greenkeeper pull requests for just minor / major updates to a dependency version, instead of every version bump?
