### ISSUE TITLE
Link to a diff

### ISSUE THREAD

**Issue by kevinburke** [greenkeeperio/greenkeeper#29]
If you are going to encourage projects to constantly update their dependencies to the cutting edge, it would be nice to include a link to what actually changed in the dependency. A single version bump in a `package.json` file can hide a lot about what's changing.

It's a good practice to actually read the changes to a package before you update, the same way you would expect to read through changes in a pull request before deploying it.

**Comment by boennemann** [comment]
Thanks for your feedback @kevinburke,

this is already on our roadmap and I'll let you know the moment it lands.

Best,
Stephan

**Comment by boennemann** [comment]
Hey @kevinburke,

I'm happy to tell you that we've just began rolling out this feature. You'll get the Release notes (should they be available) plus a list of all the commits that happened in between.

Best,
Stephan
