### ISSUE TITLE
No PRs in any of organisation repos, greenkeeper is enabled

### ISSUE THREAD

**Issue by epoberezkin** [greenkeeperio/greenkeeper#292]
See repos in https://github.com/JSONScript

**Comment by boennemann** [comment]
Sorry for the late reply. Around the time you opened this issue we had slight problems in our queue, but executed all remaining tasks.
Looking at your PR site it looks like it's working now, so I'm assuming this got solved by now: https://github.com/JSONScript/jsonscript-proxy/pulls.

Thanks for reporting.

Stephan
