### ISSUE TITLE
PRs for prerelease versions

### ISSUE THREAD

**Issue by travi** [greenkeeperio/greenkeeper#294]
I'm not clear on whether this is something wrong on my end, how packages that I depend on are published to npm, or by design in greenkeeper, but I have never received a PR when a prerelease version is updated. Should I be receiving these?

Certainly I would not want a stable version upgraded to a prerelease, but if I've already opted into the prerelease, it would be valuable to receive a PR when an update is published for the prereleases.

In case it happens to be an issue with how the packages are being published to npm, a few examples from a [single project](https://github.com/travi/travi.org-admin) that I at least have public are:
- [istanbul](https://github.com/gotwarlost/istanbul) (alpha)
- [react-hot-loader](https://github.com/gaearon/react-hot-loader) (beta)
- [webpack](https://github.com/webpack/webpack) (beta)
- [webpack-dev-server](https://github.com/webpack/webpack-dev-server) (beta)
- [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin) (beta)

**Comment by dschep** [comment]
In the opposite vein, I just got a PR for `react-router-redux@5.0.0-alpha.5` (while on 4.0.8 stable) and would really rather not.

**Comment by travi** [comment]
@dschep unfortunately, that was an issue with how `react-router-redux` published that alpha. if you run `npm info react-router-redux` you can see that it is tagged as `latest` rather than for a release channel, like `alpha`

**Comment by dschep** [comment]
Oh. Thanks @travi, that makes sense.

**Comment by absolutehype** [comment]
How about this? https://github.com/expressjs/express/releases

I just received an update for `greenkeeper/express-5.0.0-alpha.6`.

I'm currently running `4.15.4` and their current release is `4.15.5`. Shouldn't I be receiving an update to `4.15.5` rather than their pre-release? This feels like a bug to me.

**Comment by janl** [comment]
at this point we completely ignore pre-release versions. We’ve also safeguarded against pre-release versions making it onto the `latest` dist-tag.
