### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by Munter** [greenkeeperio/greenkeeper#30]
When pinning all dependencies, also add into the same PR, or as a separate PR:

```diff
diff --git a/.npmrc b/.npmrc
new file mode 100644
index 0000000..cffe8cd
--- /dev/null
+++ b/.npmrc
@@ -0,0 +1 @@
+save-exact=true
```

**Comment by boennemann** [comment]
That's neat, noted :)

**Comment by boennemann** [comment]
As we are no longer requiring/assuming pinned dependencies this is something we can't send along with the update PR.

Thanks for the input :)
