### ISSUE TITLE
Bug: State 	No tests ⚠️

### ISSUE THREAD

**Issue by syzer** [greenkeeperio/greenkeeper#303]
I have declared test in my package.json, however is got `lodash@4.16.2 untested` pull request

**Comment by syzer** [comment]
https://github.com/syzer/type-safety/pulls?q=is%3Apr+is%3Aclosed

**Comment by finnp** [comment]
Hey @syzer,

you need to set up a CI service like Travis. We are not running your tests, we are only looking on the ci status of the commit. Here's a guide for setting up Travis on a repo: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

Best,
Finn
