### ISSUE TITLE
Consistently rewrite issue references to urls.greenkeeper.io

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#305]
We're still causing "Referenced by …" spam in some cases.
E.g. when a project uses repo/user#123 in their commit message.
We need to full render the commit message in html, rewrite the urls, and then add it to the commit.

https://github.com/jtangelder/sass-loader/pull/267

**Comment by finnp** [comment]
Also referencing https://github.com/greenkeeperio/greenkeeper/issues/299

**Comment by boennemann** [comment]
With the new Greenkeeper this issue is resolved https://github.com/integration/greenkeeper
