### ISSUE TITLE
The bot says untested but we have 3 others check besides greenkeeper

### ISSUE THREAD

**Issue by donnanicolas** [greenkeeperio/greenkeeper#318]
Here are some screenshots of the issue:

<img width="1280" alt="screen shot 2016-10-21 at 10 41 04" src="https://cloud.githubusercontent.com/assets/1228656/19600337/eb516c48-977a-11e6-874e-8243102f142b.png">
<img width="1280" alt="screen shot 2016-10-21 at 10 41 06" src="https://cloud.githubusercontent.com/assets/1228656/19600340/ecd4196c-977a-11e6-9bac-c71360ac6da8.png">

Great tool guys, is really helpful!!!

**Comment by boennemann** [comment]
This issue is part of the old Greenkeeper which we're turning off at the end of the month. This should no longer be ab problem with Greenkeeper 2.
