### ISSUE TITLE
Author of pull reuqest

### ISSUE THREAD

**Issue by Andersos** [greenkeeperio/greenkeeper#32]
Why is the pull request opend by @erikras and not @greenkeeperio-bot ?

![skjermbilde 2015-09-30 kl 13 26 50](https://cloud.githubusercontent.com/assets/288977/10191770/51e335a2-6777-11e5-84aa-ce741c6daadc.png)

**Comment by boennemann** [comment]
Hey @Andersos,

thanks for your report. This is a known issue that we had yesterday. Unfortunately you didn't have any email associated with your GitHub account, so I couldn't contact you directly. I'm glad you made your way here now :)

We had a problem with a GitHub API client that was shared in memory between our pull-request creation jobs, which caused false attribution under rare conditions.

Unfortunately you have received one such pull-request under a wrong name:

Once we were aware of the problem we immediately stopped all machines until we could resolve the problem. At no time did anyone have unauthorized access to repositories.

We are sorry for the caused problems and confusion.

Best,

Stephan

**Comment by erikras** [comment]
Hee hee. I saw the tweet warning of the error and then saw it manifest itself on a PR on my repo which I closed and did manually. Nice to know I was credited with a PR on someone else's repo. :-)

**Comment by Andersos** [comment]
Ok, tried to find a issue related to this but could not find it. It is nice that it is solved.

Great job on the PR btw @erikras ;P

**Comment by boennemann** [comment]
@erikras You were the other person without an email address associated to your account, so I'm happy you made it here as well. The same goes for you, we're sorry about the caused problems and confusion.

Best,
Stephan
