### ISSUE TITLE
404 while running `gk login` on GitHub Enterprise instance

### ISSUE THREAD

**Issue by singles** [greenkeeperio/greenkeeper#321]
Hi,

we're using Greenkeeper Enterprise with GitHub Enterprise. Whenever I try to run `greenkeeper login` and I login as a user I want to configure webhook as, I'm redirected to `404` page on GH. 

Mentioned user is a part of a team which has **admin** rights to the repository.

**Comment by singles** [comment]
I will close this and write to enterprise@greenkeeper.io instead.

**Comment by janl** [comment]
For posterity, this was an oauth setup issue.
