### ISSUE TITLE
Enable Greenkeeper on an organization repo w/o being admin of that org.

### ISSUE THREAD

**Issue by bd82** [greenkeeperio/greenkeeper#324]
Steps:
1. Open https://github.com/integration/greenkeeper.
2. click "install".
3. select my github username (bd82)
4. give access to "all repositories"

Result:
All my repositories under https://github.com/bd82?tab=repositories
Started using greenkeeper. However the [one repository](https://github.com/SAP/chevrotain) I actually wanted to enable greenkeeper in does not become enabled.

This repository is in **another organization**. (not under my user name).
but I have **admin** privileges in it.

The previous issue was [Feature request: setup a repository without having to grant access at organization level](https://github.com/greenkeeperio/greenkeeper/issues/281) Now it seems like that while granting access at the organization level is not needed. being an admin/owner of the organization is still needed (at least when using the UI at https://github.com/integration/greenkeeper).

What do I need to do to enable greenkeeper for a repository I am an admin of
but which sits under an organization I do not control?

**Comment by boennemann** [comment]
Hey @bd82,

thanks for your feedback. GitHub Integrations are only in their early stage at this point. I will ask whether this is something they want to support or not.

For now you would have to ask an SAP admin to install Greenkeeper. They can grant access down to the repository level then.

This is something we don't have more control over, so unfortunately this all that I can offer right now.

Thanks for understanding.

Best,
Stephan

**Comment by bd82** [comment]
I will try to contact my organization's admins. 😢

**Comment by boennemann** [comment]
Good luck with it. I hope without requiring admin access anymore this is something they will allow 👍

**Comment by boennemann** [comment]
Unfortunately there is nothing we can do about this issue, as this behavior is controlled by GitHub.
In order to keep our issue tracker actionable I'll go ahead an close this issue.
Thanks!
