### ISSUE TITLE
Branches are created but no PR is opened

### ISSUE THREAD

**Issue by IOAyman** [greenkeeperio/greenkeeper#326]
I'm not receiving any PRs from @greenkeeperio-bot, although new branches are being created!

As it is shown in the following screenshot for the last few days (Oct 27-29, 2016):
![screenshot_2016-10-30_14-01-38](https://cloud.githubusercontent.com/assets/6185849/19836727/be758e26-9ea9-11e6-967f-9d7a8d0b64e7.png)

But no PRs are opened (filtering all PRs since Oct 25th):
![screenshot_2016-10-30_14-01-04](https://cloud.githubusercontent.com/assets/6185849/19836738/fb190290-9ea9-11e6-8327-20f370ad82cc.png)

**Comment by IOAyman** [comment]
Also having some weird behavior!

![screenshot_2016-11-03_19-19-16__0](https://cloud.githubusercontent.com/assets/6185849/19979439/bf1b80ca-a1fa-11e6-850c-ff7182b8aff4.png)

**Comment by finnp** [comment]
Hey @IOAyman, 

if new  dependency updates are already satisfied by your packages version range, then we will only notify you in case the update broke something. We are doing this by creating new branches, waiting for your CI status to be reported and then deleting them. We will only let you know in case the status on the branch was failing, so you can act accordingly.

We should probably make sure to communicate the system better.

Best,
Finn
