### ISSUE TITLE
Passing branches are no longer being automatically deleted

### ISSUE THREAD

**Issue by curiousdannii** [greenkeeperio/greenkeeper#327]
Passing branches are no longer being automatically deleted. I have seen this in a few repositories.

https://github.com/curiousdannii/reversify/branches
https://travis-ci.org/curiousdannii/reversify/builds

https://github.com/alerque/stack-verse-mapper/branches
https://travis-ci.org/alerque/stack-verse-mapper/builds

**Comment by curiousdannii** [comment]
Seems to be fixed now.

**Comment by Soliah** [comment]
Seems to be happening again or maybe just localised to CircleCI?

https://github.com/kinesisptyltd/ember-kns-helpers/branches
https://circleci.com/gh/kinesisptyltd/ember-kns-helpers/41

**Comment by curiousdannii** [comment]
I've seen it again too.

**Comment by finnp** [comment]
@Soliah @curiousdanni 
Thank you for reporting it. We introduced a bug a few days ago that caused some branches/updates not to be handled correctly. We've deployed a fix now.

However those branches that were not deleted are not going to be handled by greenkeeper anymore. Please review those branches and merge or delete them accordingly. Sorry for the inconvenience.
