### ISSUE TITLE
Typo in integration update all PR

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#328]
The new integration "Update dependencies to enable GreenKeeper" PR has a typo in the "If this pull request passes...." section.

It currently reads:
"These are really good news" when it should read "This is really good news."

For an example, see https://github.com/AtomLinter/linter-bootlint/pull/89.

**Comment by boennemann** [comment]
Ooops 🙈 

Thank you, this is fixed now :)
