### ISSUE TITLE
greenkeeper ignore may not be working

### ISSUE THREAD

**Issue by kellyselden** [greenkeeperio/greenkeeper#331]
Here is the PR https://github.com/ember-cli/ember-cli/pull/6411#issuecomment-258362478 to update an ignored package.
Here is the commit https://github.com/ember-cli/ember-cli/commit/9e423b24ee26e6a62aff1fea0d4a5e18dcb5f786#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 to ignore it three days prior.

Unless there is a couple day propagation period, it may be not working correctly.

**Comment by finnp** [comment]
@kellyselden Thank you for reporting this. We didn't add the `ignore` option to the new integration yet. However we will add that soonish. I will let you know here.

**Comment by kellyselden** [comment]
Fixed?

**Comment by finnp** [comment]
Hey @kellyselden, yes this is fixed now. Thanks again :)

**Comment by kellyselden** [comment]
No, thank you!
