### ISSUE TITLE
How to remove old greenkeeper?

### ISSUE THREAD

**Issue by rwwagner90** [greenkeeperio/greenkeeper#333]
I updated my entire org to use the new GitHub Integration, and now I get double the PRs for everything. I assumed activating the new version would disable the old. How do I disable the old one?

**Comment by janl** [comment]
@rwwagner90 that should definitely have been the case. Can you tell me the org name? If you prefer privately to support@greenkeeper.io thank you!

**Comment by rwwagner90** [comment]
@janl it is shipshapecode. You can see two PRs open for the same thing here right now https://github.com/shipshapecode/ember-shepherd/pulls

**Comment by rwwagner90** [comment]
@janl I ended up merging those PRs, but the org is shipshapecode. Can you help me please?

**Comment by joefitzgerald** [comment]
I am also experiencing this issue, reasulying in double PRs for https://github.com/joefitzgerald/go-plus.

**Comment by davelandry** [comment]
I also have multiple repositories in my organization that are getting double PRs: https://github.com/d3plus/

**Comment by boennemann** [comment]
We have fixed this problem in the meantime.
As we're shutting down Greenkeeper 1 at the end of this month this won't be a problem anymore anyays :)
