### ISSUE TITLE
Branches are pushed too quickly, apparently

### ISSUE THREAD

**Issue by tusbar** [greenkeeperio/greenkeeper#338]
Today, lodash was updated to 4.17.2, so greenkeeper created a branch on all my repositories with lodash 4.17.2.

All the builds failed with:

```
npm ERR! notarget No compatible version found: lodash@4.17.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.17.1, 4.17.0, 4.16.6, 4.16.5, 4.16.4, 4.16.3, 4.16.2, 4.16.1, 4.16.0, 4.15.0, 4.14.2, 4.14.1, 4.14.0, 4.13.1, 4.13.0, 4.12.0, 4.11.2, 4.11.1, 4.11.0, 4.10.0, 4.9.0, 4.8.2, 4.8.1, 4.8.0, 4.7.0, 4.6.1, 4.6.0, 4.5.1, 4.5.0, 4.4.0, 4.3.0, 4.2.1, 4.2.0, 4.1.0, 4.0.1, 4.0.0, 3.10.1, 3.10.0, 3.9.3, 3.9.2, 3.9.1, 3.9.0, 3.8.0, 3.7.0, 3.6.0, 3.5.0, 3.4.0, 3.3.1, 3.3.0, 3.2.0, 3.1.0, 3.0.1, 3.0.0, 2.4.2, 2.4.1, 2.4.0, 2.3.0, 2.2.1, 2.2.0, 2.1.0, 2.0.0, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 1.0.0-rc.3, 1.0.0-rc.2, 1.0.0-rc.1, 0.10.0, 0.9.2, 0.9.1, 0.9.0, 0.8.2, 0.8.1, 0.8.0, 0.7.0, 0.6.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.5.0-rc.1, 0.4.2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.0
npm ERR! notarget
```

So I don’t know if this is a caching issue, of if you’re checking for new tags and the npm package hasn’t been released yet, but it is failing every time.

**Comment by aivus** [comment]
Yeah, really, we are getting lots of false positive issues:
https://github.com/s0ph1e/node-website-scraper/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Agreenkeeper%20

**Comment by dwrensha** [comment]
Another instance: https://github.com/wekan/wekan/pull/734#issuecomment-260950997

**Comment by travi** [comment]
I've been seeing this very regularly over the last few days as well.

**Comment by travi** [comment]
could be related to https://npmjs.statuspage.io/incidents/wx7mld1cj0vz

**Comment by travi** [comment]
seems to have been fixed on the npm side, so i think this issue could be closed

**Comment by finnp** [comment]
I'm closing this for now since it appeared to be related to the npm incident. If this happens again in the future however, we will reconsider it.

@travi Thank you for your investigation!
