### ISSUE TITLE
False breaking build issues on in-rande update

### ISSUE THREAD

**Issue by s0ph1e** [greenkeeperio/greenkeeper#339]
Hi guys. First of all thanks for great tool!

Last couple of days I faced with multiple issues "in-range update is breaking build", in build logs I see that updated package version was not found.
After I manually restart build - everything is green.
For example:  https://github.com/s0ph1e/node-website-scraper/issues/150

Probably it is appveyor-CI problem, but it would be great to reduce amount of false breaking build issues created by greenkeeper bot

**Comment by aivus** [comment]
Related to #338

**Comment by boennemann** [comment]
Thanks for reporting. I'll close this as a duplicate of #338, where the problem is described.
