### ISSUE TITLE
Make PR titles customisable

### ISSUE THREAD

**Issue by kumar303** [greenkeeperio/greenkeeper#343]
Hi. Github's new [squash on merge](https://github.com/blog/2141-squash-your-commits) feature is really handy for greenkeeper pull requests because it adds one commit (instead of multiple) to our project's history.

We also auto-generate a changelog so the angular prefixing is very helpful. Thanks for that! We use a [linter](https://github.com/marionebl/conventional-changelog-lint) to make sure people don't forget to use a valid prefix.

If there's only one commit on a pull request, Github's squash on merge will use that commit message for the squashed commit. No problem here -- the changelog prefix is left in tact. 

However, **if there is more than one commit** (say, a developer had to push a fix after an upgrade) then Github will use the pull request's title as the commit and the merger needs to remember to edit it.

Could you add the changelog prefix to the pull request title to accommodate this? For example, a pull request titled *Update dependencies to enable Greenkeeper* would become *chore(package): Update dependencies to enable Greenkeeper*

**Comment by Realtin** [comment]
PR Titles are now customisable: https://greenkeeper.io/docs.html#custom-pr-titles
