### ISSUE TITLE
Integration status ignored by greenkeeper info

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#345]
Running the `greenkeeper info` command seems to ignore the status of the organization integration, always showing as disabled.

Related, it seems there is no way to check the integration from the command line?

**Comment by finnp** [comment]
The Greenkeeper integration doesn't work with the CLI. The CLI will probably be deprecated in the future.

**Comment by Arcanemagus** [comment]
Okay... is there anything we as users can do to attempt to diagnose issues like https://github.com/greenkeeperio/greenkeeper/issues/346 then? I have _no_ idea how many of my repos are currently not working.
