### ISSUE TITLE
Repo no longer working after integration enabled

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#346]
It seems that [this repo](https://github.com/AtomLinter/linter-stylelint) is no longer properly getting PR's after the integration was enabled, even though it disabled the previously active "individual repo" mode. A dependency ([stylelint](https://github.com/stylelint/stylelint/releases)) which is pinned to `7.5.0` released an update to `7.6.0` but no PR has been submitted.

Is this because the repo was already up to date when the integration was enabled, so it never got the initial update all PR? Other repos in the organization are working properly.

**Comment by travi** [comment]
I seem to be having a similar issue. I noticed the problem with [this repo](https://github.com/travi/travi.org-admin) last night and tried to configure settings for the integration. However, I get a message stating

> Already installed on all repositories

However, it is clearly not keeping dependencies up to date, because I have the following list from `npm outdated`:

```
Package                            Current         Wanted        Latest  Location
@pact-foundation/pact-node           4.5.3          4.5.3         4.5.4  travi.org-admin
@travi/any                           0.6.1          0.6.1         0.7.0  travi.org-admin
babel-core                          6.18.0         6.18.0        6.18.2  travi.org-admin
babel-loader                         6.2.7          6.2.7         6.2.8  travi.org-admin
babel-preset-stage-2                6.17.0         6.17.0        6.18.0  travi.org-admin
clean-webpack-plugin                0.1.13         0.1.13        0.1.14  travi.org-admin
coveralls                          2.11.14        2.11.14       2.11.15  travi.org-admin
css-loader                          0.25.0         0.25.0        0.26.0  travi.org-admin
dotenv-safe                          2.3.3          2.3.3         3.0.0  travi.org-admin
enzyme                               2.5.1          2.5.1         2.6.0  travi.org-admin
extract-text-webpack-plugin   2.0.0-beta.3   2.0.0-beta.3         1.0.1  travi.org-admin
good-squeeze                         5.0.0          5.0.0         5.0.1  travi.org-admin
grunt-cucumberjs                    0.10.7         0.10.7        0.10.8  travi.org-admin
history                              4.3.0          4.3.0         4.4.0  travi.org-admin
istanbul                     1.1.0-alpha.1  1.1.0-alpha.1         0.4.5  travi.org-admin
jsdom                                9.8.1          9.8.1         9.8.3  travi.org-admin
lodash                              4.16.4         4.16.4        4.17.2  travi.org-admin
newrelic                            1.32.0         1.32.0        1.34.0  travi.org-admin
nock                                 9.0.1          9.0.1         9.0.2  travi.org-admin
node-sass                           3.10.1         3.10.1        3.13.0  travi.org-admin
react                               15.3.2         15.3.2        15.4.0  travi.org-admin
react-addons-test-utils             15.3.2         15.3.2        15.4.0  travi.org-admin
react-dom                           15.3.2         15.3.2        15.4.0  travi.org-admin
react-helmet                         3.1.0          3.1.0         3.2.2  travi.org-admin
react-hot-loader              3.0.0-beta.5   3.0.0-beta.5  3.0.0-beta.6  travi.org-admin
react-redux                          4.4.5          4.4.5         4.4.6  travi.org-admin
snyk                                1.19.1         1.19.1        1.20.0  travi.org-admin
stampit                              3.0.4          3.0.4         3.0.6  travi.org-admin
webpack                      2.1.0-beta.22  2.1.0-beta.22        1.13.3  travi.org-admin
webpack-dev-server            2.1.0-beta.4   2.1.0-beta.4        1.16.2  travi.org-admin
xhr                                  2.2.2          2.2.2         2.3.0  travi.org-admin
```

**Comment by Arcanemagus** [comment]
This problem appears to be far more prevalent than I thought. Using the v11 release of `eslint-config-airbnb-base` I'm seeing **38%** of the repositories appearing to be completely ignored currently!

Repositories with no update PR:
* [linter-haml](https://github.com/AtomLinter/linter-haml)
* [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint/pulls)
* [linter-js-yaml](https://github.com/AtomLinter/linter-js-yaml)
* [linter-markdown](https://github.com/AtomLinter/linter-markdown)
* [linter-moonscript](https://github.com/AtomLinter/linter-moonscript)
* [linter-puppet-lint](https://github.com/AtomLinter/linter-puppet-lint)
* [linter-rubocop](https://github.com/AtomLinter/linter-rubocop)
* [linter-ruby](https://github.com/AtomLinter/linter-ruby)
* [linter-shellcheck](https://github.com/AtomLinter/linter-shellcheck)
* [linter-stylelint](https://github.com/AtomLinter/linter-stylelint)
* [linter-stylint](https://github.com/AtomLinter/linter-stylint)
* [linter-swagger](https://github.com/AtomLinter/linter-swagger)
* [linter-tslint](https://github.com/AtomLinter/linter-tslint)

Note that none of the above repos got the `Update dependencies to enable Greenkeeper` PR, I assumed that was because they were up to date when it was enabled on the organization, but maybe that was a sign of problems to come.

There are also 13 more repositories that _might_ have issues, but they have pending PR's from the old method of enabling Greenkeeper that haven't been merged as of yet, so I'm not going to count them as broken as of yet.

Is there any information that I can provide to help diagnose what is going on here?

**Comment by Arcanemagus** [comment]
Okay, found the badge link and went through and checked the status of all of the repos in the organization to find that **53** repos never got enabled that should have been. It seems that the integration stopped processing after 30 repos!

The integration screen of course shows everything as perfectly fine:
![image](https://cloud.githubusercontent.com/assets/427137/21192968/5698bba8-c1df-11e6-8f35-dfbc826825f9.png)

You can see the status in the spreadsheet tracking this [here](https://docs.google.com/spreadsheets/d/1bLFn9ctG_1O36ft35kg9ybBgFIlmNklsuv8vIZyh3rc/pubhtml?gid=0&single=true).

@finnp I'm tagging you here as you seem to be the one responding to things currently and this is a major bug that needs attention.

**Comment by travi** [comment]
@Arcanemagus could you give more detail about the "badge link" that you found? I'm definitely seeing this issue in many repos. At least seeing some confirmation of the ones that are not enabled would help me understand what is happening a bit better.

**Comment by finnp** [comment]
@Arcanemagus Seems like we lost some jobs when you installed Greenkeeper, because we didn't used to handle GitHub outages properly. I've rescheduled them, and now you should see a lot of initial PRs 😄  Sorry about that!

**Comment by finnp** [comment]
@travi I see you are already merging PRs 😄  I rescheduled your jobs as well.  Here's how you use the badges: ` ![greenkeeper badge](https://badges.greenkeeper.io/travi/hapi-react-router.svg)` ->  ![badge](https://badges.greenkeeper.io/travi/hapi-react-router.svg)

**Comment by travi** [comment]
yes. looks like they came through. 

thanks a ton for getting this resolved

**Comment by travi** [comment]
@finnp what is the expectation for repos that were added after the greenkeeper integration was added to an org? 

i added the badge you mentioned to a (private) repo that was created 7 days ago and the badge reports "not found". this repo did not receive a PR as a result of the rescheduling that you ran this morning, but we do have other private repos that seem to be working correctly.

is this related, or a separate issue?

**Comment by Arcanemagus** [comment]
@finnp Thanks for taking care of this! If it's feasible you might think about rescheduling all the orgs enabled before handling of outages was put in place as there are most likely others out there that haven't caught that Greenkeeper isn't enabled for all of their repos.

**Comment by finnp** [comment]
@travi This is because the greenkeeper badges are public, so we can not show the repository status for private repositories. However we're rolling out a feature soon, where badges in private repos can be used by adding a token to the badge url.

@Arcanemagus Yeah, that's a good suggestion, we'll probably do something like this soon :)

**Comment by travi** [comment]
ah, that makes sense. now that i know that badges are available, i am interested in adding them. is there an issue that i can follow to track progress for the ones for private repos?
