### ISSUE TITLE
[Question] How it work internally?

### ISSUE THREAD

**Issue by katopz** [greenkeeperio/greenkeeper#347]
Hi,

I'm curious how `greenkeeper` syncing versions, here's my guess...
- [ ] Read `package.json` and use user cpu/network to fetch and sync `npm` via cli and trigger PR. (no server need)

or
- [ ] Upload user `package.json` to server then merge it with other and run cron to fetch and sync with `npm` later. (need serevr)

or
- [ ] Hook with user's github keep an eye on `package.json` and trigger sync with `npm` at that time then PR if need. (need serevr)

or maybe some other way?

Thanks

**Comment by finnp** [comment]
Well, we listen to your Github hooks for your repository to always sync the latest `package.json` to our database. Then we listen to the npm changes feed and for each update we determine which repositories depend on it and then send the pull requests.

I hope that explained it for you.
