### ISSUE TITLE
`gk` issue.

### ISSUE THREAD

**Issue by hemanth** [greenkeeperio/greenkeeper#35]
My `gk`: 

```sh
$ which gk
gk: aliased to \gitk --all --branches
```

**Comment by arthurvr** [comment]
Did you alias `gk` to `gitk --all --branches` yourself or did that ship with `gitk`?

**Comment by arthurvr** [comment]
Doesn't really matter much though. We can't prevent people from using aliases with the name `gk` and we can't work around that eighter.

**Comment by hemanth** [comment]
@arthurvr Yes the whole intent was to inform the user that `gk` is aliased to something else and is not overridden.

**Comment by boennemann** [comment]
I'm with @arthurvr here, this is not something we can address.
