### ISSUE TITLE
autoupdate greenkeeper branch ignore regex

### ISSUE THREAD

**Issue by kellyselden** [greenkeeperio/greenkeeper#352]
I had to update all my repos like this:
https://github.com/kellyselden/babel-plugin-fake-import-specifiers/pull/2

to support the new branch convention. I know other people are ignoring like this. Maybe a codemod like your node 0.10 changes would be useful when a project migrate to from the old API to the new integration.

**Comment by finnp** [comment]
Thank you for pointing this out. We're currently adding a feature that will check the travis.yml on enable, so we can prevent this in the future. But we might also send PRs to older projects as well, let's see :thinking:

**Comment by kellyselden** [comment]
No problem. I already went through it all, so just wanted to share.

**Comment by janl** [comment]
closing for now.
