### ISSUE TITLE
Option for all updates in a single branch / PR

### ISSUE THREAD

**Issue by rjmunro** [greenkeeperio/greenkeeper#354]
It would be great if greenkeeper was able to maintain a single branch / PR with all the latest updates as commits on that branch. So whenever a new update comes out, the branch should be rebased onto master and another commit added with the new update to package.json. This branch could then periodically be merged, e.g. after a stable release, rather than having a backlog of lots of greenkeeper PRs open all the time (some of which will conflict with each other)

**Comment by stjohnjohnson** [comment]
At least if it could be one PR for each package, I just had 4 branches/PRs open for the same package that shipped patch releases since their major update.

**Comment by janl** [comment]
The “new” issue-per dependency model should be a lot nicer here.
