### ISSUE TITLE
Enabling the new integration on one account seems to have disabled it for another account

### ISSUE THREAD

**Issue by curiousdannii** [greenkeeperio/greenkeeper#358]
I have commit access to https://github.com/alerque/stack-verse-mapper and previously greenkeeper was enabled on it.

Yesterday I enabled the new integration for my own account, and it is working on my repos. But now greenkeeper seems to be disabled for alerque/stack-verse-mapper. Here's the badge: ![badge](https://badges.greenkeeper.io/alerque/stack-verse-mapper.svg)

I can't prove the integration disabled it - it could just be a coincidence. But clarification would be good either way!

**Comment by finnp** [comment]
Greenkeeper ist still enabled on that repository. The badge doesn't work with the old integration. Have a look at https://app.greenkeeper.io/ to see which repositories are enabled in the old integration.
