### ISSUE TITLE
No package.json present, you wont receive pull requests

### ISSUE THREAD

**Issue by ShadOoW** [greenkeeperio/greenkeeper#359]
I have a repository with folders for backend/frontend, when i run ```greenkeeper enable``` it says ```No package.json present, you wont receive pull requests```.

Is their an option to specify the path to packages.json?

**Comment by rkuykendall** [comment]
See https://github.com/greenkeeperio/greenkeeper/issues/139

**Comment by finnp** [comment]
Yes, please watch #139 for updates :)
