### ISSUE TITLE
Add ability to customise branch name format

### ISSUE THREAD

**Issue by miksago** [greenkeeperio/greenkeeper#36]
We roughly use git flow, and like the idea of prefixing branch names with groupings, as such we'd like to have the greenkeeper created branches named as:

```
greenkeeper/[package-name]-[version]
```

**Comment by boennemann** [comment]
Thanks for your feedback. Keep those suggestions coming :) This is something that's on our to do list, along with templates for the commit messages.

Best,
Stephan

**Comment by boennemann** [comment]
Adding a `"branchPrefix"` property to the `"greenkeeper"` field in your `package.json` allows to modify this behavior for paid plans now :)

Thanks for the great feedback

Stephan
