### ISSUE TITLE
Make pull-requests for updates where major is 0

### ISSUE THREAD

**Issue by mightyiam** [greenkeeperio/greenkeeper#360]
Is [this comment](https://github.com/yarom-and-shahar/cyclejs-shooter/pull/191#issuecomment-268561263) correct?

**Comment by mightyiam** [comment]
Also, forgive me if this is a duplicate. I really did search.

**Comment by finnp** [comment]
Hey @mightyiam,

no I think this was simply an error on our side. You're correct that `0.17.0` is not part of the `^0.16.0` range, but greenkeeper will still send you a pull request. In the meantime we improved the stability of the new greenkeeper, so this will hopefully not happen again :)

Best,
Finn
