### ISSUE TITLE
revert an accidentally merged PR

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#361]
We accidentally merged a PR from greenkeeper which automatically got released as a patch realease, although it should have been a breaking change: https://github.com/hoodiehq/hoodie-client/pull/118

I know probably we should add more tests. But I wonder if something like that happens, is there a simple hack to revert a PR with another `fix(package) ...` commit / PR coming from Greenkeeper? 

It’s probably out of scope, but maybe someone has an idea for it :)

**Comment by boennemann** [comment]
<img width="334" alt="screen shot 2017-05-21 at 1 57 09 am" src="https://cloud.githubusercontent.com/assets/908178/26280145/d4c729fa-3dc8-11e7-8317-bfa2f214af57.png">

Reverting a merged PR is part of GitHub, so I guess this is already solved :)
