### ISSUE TITLE
Don't send email notifications

### ISSUE THREAD

**Issue by goldylucks** [greenkeeperio/greenkeeper#362]
Title kinda says it all
I get an email notification for pull requests.

would b nice to have a way to config that.

I c 2 places for configuring this:
1. in every email, add a "don't send me more emails" button
2. When enabling a repo

Thoughts?

**Comment by Arcanemagus** [comment]
Are you sure this isn't GitHub itself notifying you? As far as I know Greenkeeper doesn't send any emails.

**Comment by goldylucks** [comment]
@Arcanemagus thanks for your quick reply

u r right, I should've been more clear.

It is github notifying me, however i only get emails for PRs from GK. maybe it's because it's a different user then me opening the PR?

and if so, is there a way around that?

**Comment by Arcanemagus** [comment]
You can simply change your notification preferences [here](https://github.com/settings/notifications).

**Comment by goldylucks** [comment]
yes but AFAIK there's no way to disable notifications from specific users

**Comment by finnp** [comment]
Hey @goldylucks,

yeah this is an issue with GitHub. I recommend setting up a local email filter to manage the load. But we hope Github will improve their settings in the future.

Best,
Finn
