### ISSUE TITLE
Got 'is not a function' while call jasmine-spec-reporter after udate to 3.0.0

### ISSUE THREAD

**Issue by MihailStopnik** [greenkeeperio/greenkeeper#363]
Hi,

I got  E/launcher - Error: TypeError: specReporter is not a function 
E/launcher - Process exited with error code 100

in protractor config:
var specReporter = require('jasmine-spec-reporter');
jasmine.getEnv().addReporter(new specReporter({displayStackTrace: true}));

rollback to 2.7.0 and it works again.
Please advise how I can debug it.

**Comment by finnp** [comment]
Sorry I don't think we can help with that.

**Comment by xgirma** [comment]
@MihailStopnik add .SpecReporter

```js
var specReporter = require('jasmine-spec-reporter').SpecReporter;
jasmine.getEnv().addReporter(new specReporter({
displayStackTrace: true
}));
```

**Comment by tuliobluz** [comment]
Hey, to solve this problem, back the version to:

npm install jasmine-spec-reporter@2.7.0

That's works to me
