### ISSUE TITLE
Greenkeeper says build failed, even though it passed

### ISSUE THREAD

**Issue by wopian** [greenkeeperio/greenkeeper#365]
Recently I've been getting several issues opened about in-range updates breaking the build.

In the Status Details section it says the tests are failing, however clicking on the details for each test shows that they passed successfully.

https://github.com/wopian/hatayama/issues/8
https://github.com/wopian/hatayama/issues/9
https://github.com/wopian/hatayama/issues/10
https://github.com/wopian/hatayama/issues/11

**Comment by finnp** [comment]
Hey,

you're set up several checks for your commit. It appears like bitHound reported an error about some dependencies. So while the other services pass, this error leads Greenkeeper to flag this as an error. You can look at the status details, where is says `bitHound - Dependencies 3 failing dependencies. `.

Best,
Finn

**Comment by wopian** [comment]
Ah, woops. Thought I'd disabled that bitHound failure condition on all repos 😊
