### ISSUE TITLE
greenkeeper CLI doesn't acknowledge slug

### ISSUE THREAD

**Issue by dbkaplun** [greenkeeperio/greenkeeper#37]
```
$ greenkeeper  '--slug=slap-editor/editor-widget' enable
🌴  info enable The GitHub slug is: dbkaplun/editor-widget
🌴  ERR! enable Couldn’t find a repo with this slug.
🌴  ERR! enable Either it doesn’t exist on GitHub, it’s a fork, or private.
```

**Comment by boennemann** [comment]
@dbkaplun Thanks for catching, this is a regression accidentally introduced [here](https://github.com/greenkeeperio/greenkeeper/commit/3d16852181e65ca73967a6719af4773c27678c0e) and fixed as of 2.1.1.

**Comment by baptistebriel** [comment]
@boennemann do you have an example of how to pass the slug in CLI?

**Comment by boennemann** [comment]
Sure @baptistebriel,

`greenkeeper enable --slug aptistebriel/smooth-scrolling`

That's how it should work ;)

Best,
Stephan

**Comment by baptistebriel** [comment]
Yay! 🎉 It works, thanks.

You should add this to the docs I guess. :)

**Comment by rstuven** [comment]
```
$ greenkeeper --version
2.1.1

$ greenkeeper enable --slug rstuven/fsa-creator
🌴  info enable The GitHub slug is: rstuven/fsa-creator
🌴  ERR! enable Couldn’t find a repo with this slug.
🌴  ERR! enable Either it doesn’t exist on GitHub, it’s a fork, or private.
```

GitHub repo: [https://github.com/rstuven/fsa-creator](https://github.com/rstuven/fsa-creator)
