### ISSUE TITLE
Duplicate Add Badge PRs

### ISSUE THREAD

**Issue by janl** [greenkeeperio/greenkeeper#371]
> @greenkeeperio I'm getting multiple "add badge" PRs. It appends another badge after the first one. Just FYI

— https://twitter.com/dbrckmn/status/823813359824945152

Asked for org/repo details in a reply, will update the issue when we get this info

**Comment by janl** [comment]
Example here: https://github.com/Springworks/swagger-md/pull/152/files

**Comment by boennemann** [comment]
Should be fixed by now. Happy to reopen.
