### ISSUE TITLE
GK no longer opening PRs

### ISSUE THREAD

**Issue by Turbo87** [greenkeeperio/greenkeeper#372]
I've noticed on several repositories that GK was correctly creating a branch to update a (pinned) dependency, Travis tested it, but apparently GK didn't open a PR to update the dependency.

one example is https://github.com/simplabs/ember-test-selectors:

- you can see the `greenkeeper/ember-cli-2.11.0` branch in https://github.com/simplabs/ember-test-selectors/branches

- you can see that the tests ran and passed at https://travis-ci.org/simplabs/ember-test-selectors/branches

- but there is no corresponding PR at https://github.com/simplabs/ember-test-selectors/pulls?q=is%3Apr

/cc @kellyselden @marcoow

**Comment by finnp** [comment]
Hey @Turbo87,

yes this is a known issue that we already fixed. For a few days some pull requests were not created. We would ask you to create those PRs manually. Future dependencies should work as expected again Sorry for the inconvenience.

**Comment by Turbo87** [comment]
@finnp good to know, thanks for the feedback and for a great service!
