### ISSUE TITLE
Greenkeeper didn't create a new PR on install despite there being a new version within my dependencies

### ISSUE THREAD

**Issue by mtford90** [greenkeeperio/greenkeeper#374]
Hello there,

I just tried to install greenkeeper on this repo: https://github.com/mtford90/react-native-watch-connectivity

There is an update to `react-native-camera` that falls outside of my version range (I have pinned all dependency versions within package.json whilst playing with greenkeeper). Greenkeeper successfully created a greenkeeper/initial branch that updates this dependency but didn't create an initial PR and the badge shows as `disabled` on that branch.

Is there something i'm missing here? 

Cheers

**Comment by finnp** [comment]
Hey @mtford90,

currently greenkeeper requires a CI service like travisci.org to be used. Right now we only create the initial pull request once a CI status is received on that commit/branch.

In the future we will have a timeout after which you will get an issue letting you know about this. But right now in the beta version, it will just wait forever for the status to be reported.

Best,
Finn

**Comment by mtford90** [comment]
Ahhh got it! Thanks @finnp

**Comment by DiegoRBaquero** [comment]
@finnp So this (https://travis-ci.org/DiegoRBaquero/V/builds/206419071) not creating a PR is because travis failed to send completion event to gk? Trying to figure out the root of the issue.

(Should PR because is outside semver range)

**Comment by boennemann** [comment]
We've added an issue that's created if there is no test status within 15min of the initial branch creation. This issue explains the problem, so I'll go ahead and close this issue.
