### ISSUE TITLE
Badges say "disabled" after the initial merge due to cache headers

### ISSUE THREAD

**Issue by rschamp** [greenkeeperio/greenkeeper#375]
See https://github.com/github/markup/issues/224, specifically https://github.com/github/markup/issues/224#issuecomment-37663375

After merging the first PR after enabling the integration, our repo's README displayed an incorrect "Greenkeeper: disabled" badge, because GitHub cached the image before the status changed (fixed with a `curl -X PURGE` on the camo-ified URL).

If the badge headers contained `cache-control: no-cache` and `ETag`, then GitHub would update its cache as soon as the `ETag` changed.

Sorry if this is the wrong repo, I didn't see one specifically for the Greenkeeper integration.

**Comment by finnp** [comment]
Hey @rschamp,

thank you for reporting this and giving us pointers to fix this. This is the exact right place to report this. We're going to look into this and let you know once we deployed a fix.

Best,
Finn

**Comment by finnp** [comment]
Thank you again for letting us know about this. We have deployed a new version with Etags support, so that the badges are not cached as long anymore.
