### ISSUE TITLE
Updated documentation

### ISSUE THREAD

**Issue by leolorenzoluis** [greenkeeperio/greenkeeper#377]
Hello,

I started using green keeper with Github integration and I can't seem to find any documentation on how does it work? Right now it says Not running. I have no clue what to do, I scoured the issues area and saw that it needs Travis CI, which I already have, but it is still saying Not running. I also did `curl -X PURGE <img>`

**Comment by boennemann** [comment]
Sorry about your problems here and not reacting earlier.
I hope your problem is solved by now so I'll go ahead and close this issue to keep our issue tracker clean and actionable.

If you still have a problem I'm happy to reopen immediately.
