### ISSUE TITLE
New greenkeeper spams my github timeline

### ISSUE THREAD

**Issue by cebor** [greenkeeperio/greenkeeper#379]
I switched just now from the old to the new greenkeeper.

I only use it in three of my repositories, but it fills my timeline with so many messages about creating/deleting branches, that i even not getting the important messages ...

See: 

<img width="659" alt="screen shot 2017-02-11 at 21 49 05" src="https://cloud.githubusercontent.com/assets/1576120/22857362/1ebc1c54-f0a4-11e6-9d92-bbb5569b0b58.png">

Is there any way to prevent greenkeeper bot from doing this ?

**Comment by finnp** [comment]
Hey @cebor,

we can not control the GitHub timeline. We'll hope GitHub will improve on it, to make it possible to filter users/events from it.

I actually created a small Chrome Extension for filtering bot activity from the GitHub homepage (https://github.com/finnp/github-less-bots). Maybe something like this can help you in the meantime.
