### ISSUE TITLE
(Squashed) Merged initial request but not activated.

### ISSUE THREAD

**Issue by Dexus** [greenkeeperio/greenkeeper#383]
I have accept the PR/Merged the branch, but the project is not activated and the branch deleted.
Will the Bot check again or what did i need to do?

**Comment by boennemann** [comment]
Hey @Dexus,

I just looked into your recent activity and found this: https://github.com/Dexus/node-sofort/pull/4
It looks like you created the PR for Greenkeeper's intial branch yourself.

Usually Greenkeeper would create that PR on its own, as soon as there are test results available from a CI service (e.g. Travis CI), but it looks like you don't have a CI service set up.

The enabling flow usually looks like this: https://github.com/greenkeeperio/greenkeeper/pull/382

Can you setup a CI service (e.g. [Travis CI](https://travis-ci.org/) is free for open source) and reinstall the integration again?

Let me know how that worked.

Best,
Stephan

**Comment by delkopiso** [comment]
@boennemann I'm not sure if it's the same issue here, but https://github.com/alphasights/ember-graphql-adapter/pull/74 was merged and the badge still says "disabled" on the repo.
