### ISSUE TITLE
Status checks passing, no PRs being created.

### ISSUE THREAD

**Issue by Charlotteis** [greenkeeperio/greenkeeper#384]
Hi!

I looked through my status builds (appveyor, travis, code coverage) to discover that greenkeeper created branches in https://github.com/charlotteis/hottake for an update to weallbehave, weallcontribute and tap. All the status checks passed. Then greenkeeper deleted all the branches. No PRs were made.

Any ideas why greenkeeper isn't creating the PRs? My greenkeeper badge reads 'enabled'. Everything seems to be passing. All the updates are withing my version ranges, too.

**Comment by Charlotteis** [comment]
I uninstalled and reinstalled the github integration again (i've done this a couple times in the last week) and will see if that works.

**Comment by Charlotteis** [comment]
Renabling it made greenkeeper create an `initial` branch on another repo of mine, but nothing at all for the hottake repo.

**Comment by colmose** [comment]
I was confused about this as well recently but I think what's happening is that greenkeeper is checking the new versions of those packages are met by your semver ranges in your package.json and if they are, it closes the branch without making a PR. 

It only needs to make a PR if the new package version is not met by your semver ranges.

**Comment by Charlotteis** [comment]
But I have another repository with the same semver range https://github.com/zkat/cacahce, and the PR was made for the package updates?

**Comment by Charlotteis** [comment]
Ah! @colmose is right. I didn't realise `^` ignored patch updates.

Thank you and sorry for the issue!

**Comment by Charlotteis** [comment]
Okay yes that was very confusing, @colmose was right. Looks like I'll go and update things manually :)
