### ISSUE TITLE
Add an empty line after the badge

### ISSUE THREAD

**Issue by dbrockman** [greenkeeperio/greenkeeper#389]
When GK adds the badge to a readme file it should include an empty line before and after the badge. 

Without an empty line, the image will render on the same line as the text which looks weird.

**Comment by finnp** [comment]
@dbrockman Can you show an example where this is happening?

**Comment by mightyiam** [comment]
In [this badge PR](https://github.com/eslint/eslint/issues/8543#issuecomment-333371779) it did add an empty line and it is wrong. It should be smart about it.

**Comment by mightyiam** [comment]
Notice there's a fixing commit:
https://github.com/mightyiam/eslint-multiple-parsers/pull/2/commits

**Comment by chinesedfan** [comment]
> In this badge PR it did add an empty line and it is wrong. It should be smart about it.

In fact, it requires [readme-badger](https://github.com/gitterHQ/readme-badger) to be smarter.
