### ISSUE TITLE
"breaking the build" issue created but branch missing

### ISSUE THREAD

**Issue by derhuerst** [greenkeeperio/greenkeeper#390]
Hey humans!

I'm using greenkeeper a lot to maintain my projects, so first of all: thanks for such a great service!

https://github.com/derhuerst/vbb-map/issues/5
https://travis-ci.org/derhuerst/vbb-map/builds/211544650

greenkeeper created this particular issue notifying me that the latest version of some dependency of a project of mine is breaking the build. But the Travis build fails because the branch (to dump the dependency) does not exist.

Am i missing something here?

**Comment by finnp** [comment]
I think this must be fixed by now. If you see this issue again let us know and feel free to reopen this issue.
