### ISSUE TITLE
Integration not enabling on newly added/renamed repositories

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#395]
It seems that although GreenKeeper has access to all repositories in the organization, and has been for the last 5 months, a few repositories that have been added somewhat recently have an unknown status for the GreenKeeper integration:

* [linter-gfortran](https://github.com/AtomLinter/linter-gfortran): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-gfortran.svg)](https://greenkeeper.io/) (newly moved into the org)
* [linter-pycodestyle](https://github.com/AtomLinter/linter-pycodestyle): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-pycodestyle.svg)](https://greenkeeper.io/) (renamed from linter-pep8)

How do I get Greenkeeper enabled on these repos?

**Comment by Arcanemagus** [comment]
Just transferred another batch of repos in about an hour ago and Greenkeeper seems to also be ignoring these:

* [linter-spell](https://github.com/AtomLinter/linter-spell): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-spell.svg)](https://greenkeeper.io/)
* [linter-spell-project](https://github.com/AtomLinter/linter-spell-project): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-spell-project.svg)](https://greenkeeper.io/)
* [linter-spell-ruby](https://github.com/AtomLinter/linter-spell-ruby): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-spell-ruby.svg)](https://greenkeeper.io/)
* [linter-spell-javascript](https://github.com/AtomLinter/linter-spell-javascript): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-spell-javascript.svg)](https://greenkeeper.io/)
* [linter-spell-html](https://github.com/AtomLinter/linter-spell-html): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-spell-html.svg)](https://greenkeeper.io/)
* [linter-spell-latex](https://github.com/AtomLinter/linter-spell-latex): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-spell-latex.svg)](https://greenkeeper.io/)
* [linter-spell-word-list](https://github.com/AtomLinter/linter-spell-word-list): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-spell-word-list.svg)](https://greenkeeper.io/)

**Comment by boennemann** [comment]
Sorry about this, we did have some problems with the badges in the past. If you're using Greenkeeper 2 badges should be properly working, so I'll go ahead an close this issue.

Happy to reopen if the problem persists.

**Comment by Arcanemagus** [comment]
I'm using the integration, I'm assuming that's what you mean by "Greenkeeper 2" and have been basically since it was announced. Since the badges still show these projects are not active I would say the problem definitely is persisting.

**Comment by Arcanemagus** [comment]
Should I just file a new issue with the same information? 😕
