### ISSUE TITLE
Badge still displaying disabled

### ISSUE THREAD

**Issue by Roaders** [greenkeeperio/greenkeeper#397]
On my Repo (http://github.com/Roaders/maybe-monad) it still says greenkeeper disabled despite me merging in the initial greenkeeper PR 3 days ago.

How to enable greenkeeper?

**Comment by finnp** [comment]
I don't see any merged initial Greenkeeper pull request on your repository. Have you actually added this repository to the integration?

**Comment by Arcanemagus** [comment]
Looks like there was a manual merge in https://github.com/Roaders/maybe-monad/commit/760a99a9e94303ba0e482e04308afbdaec7ab8a5, no PR's or issues on the repo though. 😕

**Comment by Roaders** [comment]
yes, I manually merged the branch. I am not sure if there was ever a PR, I don't remember an email and there seems to be no sign of one on the repo.
How do I get greenkeeper to try again?

**Comment by finnp** [comment]
See https://github.com/greenkeeperio/greenkeeper/issues/402#issuecomment-297676799 ✨ ✨
