### ISSUE TITLE
Update messes up dependency ranges

### ISSUE THREAD

**Issue by SimenB** [greenkeeperio/greenkeeper#398]
See https://github.com/SimenB/node-prometheus-gc-stats/pull/20/files

It should be `>= 3.2 < 9` or something 😄

**Comment by finnp** [comment]
Sorry, we can't do this. If we use `>= 3.2 < 9`, we can't guarantee that your tests will use the new `8.0.0` on install. So unfortunately you'll have to switch it back to your range before merging.
