### ISSUE TITLE
Badge displays enabled, but not receiving the initial pr

### ISSUE THREAD

**Issue by ismay** [greenkeeperio/greenkeeper#399]
I've enabled my repo in the integration, and the badge states that the integration is enabled. But I haven't received an initial PR or anything else from greenkeeper:

* https://github.com/ismay/stylelint-no-unsupported-browser-features#readme

**Comment by ismay** [comment]
Anyone? The badge is now not even loading on my readme.. I'd love to hear how I can fix this.

**Comment by finnp** [comment]
If everything is up to date your repository will be enabled right away ✨ ✨
