### ISSUE TITLE
Slightly faster boot time

### ISSUE THREAD

**Issue by remy** [greenkeeperio/greenkeeper#40]
If you move https://github.com/greenkeeperio/greenkeeper/blob/master/src/index.js#L16-L21 to the end of your index.js it's slightly faster. I noticed this on nodemon WRT time to get output on the cli.

**Comment by remy** [comment]
Hmm, though, depends on how your internals work actually. I found things like `nodemon -v` would wait 200ms before getting the version (because of the update check). But when *I* check for the version, I immediately exit, so it means I'm in and out quickly, ie. this might not benefit you. Meh. Just saying, always worth considering boot time :)

**Comment by janl** [comment]
#wontfix as outlined in #42 — sorry! :)

**Comment by remy** [comment]
s'okay.

![sad-cat](https://cloud.githubusercontent.com/assets/13700/10251805/5d32b594-692b-11e5-92c3-da57b3e68063.gif)
