### ISSUE TITLE
No update notifications for @types/xxx packages

### ISSUE THREAD

**Issue by bcaudan** [greenkeeperio/greenkeeper#400]
I've got a typescript repository with dependencies on several type declaration packages, ex: [@types/jasmine](https://www.npmjs.com/package/@types/jasmine). 
greenkeeper does not seem to be aware of updates for this kind of package.
Is there anything that I could do on my side?
Otherwise, it could be great to add support for this kind of packages.

**Comment by finnp** [comment]
Hey @bcaudan you are using the old greenkeeper, which will be shut down in a month.

The new Greenkeeper is be able to handle scoped packages like that.

You can switch to it here: https://github.com/integration/greenkeeper

**Comment by bcaudan** [comment]
Great, Thx!
