### ISSUE TITLE
Feature request to remove old version PRs amongst newer version PRs

### ISSUE THREAD

**Issue by moimikey** [greenkeeperio/greenkeeper#401]
Apologies if this issue is a duplicate. It's not the most simplistic thing to search for without spending a helluva lotta time eyeballing, but:

I tend to have some long intervals before checking greenkeeper prs in my repos. By that time, I may have a PR open for Package A version 1.0.2, and another PR for Package A version 1.0.3. It would be nice if greenkeeper was able to close out the older version PR automatically.

**Comment by Arcanemagus** [comment]
The new integration method continuously updates a single PR instead of creating a new PR for each version.
