### ISSUE TITLE
Badge saying disabled

### ISSUE THREAD

**Issue by vajahath** [greenkeeperio/greenkeeper#402]
No idea why this is saying disabled.
[![Greenkeeper badge](https://badges.greenkeeper.io/vajahath/sqlify.svg)](https://greenkeeper.io/)

Repo: https://github.com/vajahath/sqlify

**Comment by danielbayerlein** [comment]
Have the same problem. Looks like the badge is broken.

**Comment by ismay** [comment]
Same happened for me as well

**Comment by Arcanemagus** [comment]
It looks like you manually merged the `greenkeeper/initial` branch, but I don't see the initial PR that should have accompanied that in your repo. Without the initial PR (which you don't seem to even have!) getting merged Greenkeeper _is_ disabled.

**Comment by ismay** [comment]
@Arcanemagus, is there a way to trigger greenkeeper to resubmit the pr if the original pr's branch has been deleted? Reenabling the integration for the repo doesn't seem to trigger a new pr, which means greenkeeper can never recover from such a state?

**Comment by Arcanemagus** [comment]
@ismay If I knew the answer to that I could probably fix https://github.com/greenkeeperio/greenkeeper/issues/395 as well 😛. Unfortunately I think we are all waiting for somebody with @greenkeeperio to take a look at this.

**Comment by ismay** [comment]
Ah too bad. Well hopefully we'll get a reply from them 🤞

**Comment by riccardoerra** [comment]
Having same issue over here. Just added Greenkeeper to a repo -> open PR -> rebase and merged -> badge got added in the the README but it's says disabled.

**Comment by merlinnot** [comment]
Same for me in multiple repos. I've tried to merge by creating a merge commit, rebasing etc. Disabled everywhere.

**Comment by finnp** [comment]
@vajahath Hey, the badge is not broken. Your repository is not enabled. You've created the initial greenkeeper pull request manually and therefore the merge was not recognized as an enabled.

To enable Greenkeeper you need to delete the `greenkeeper/initial` branch, remove that repository from the integration, re-add it again and wait for the initial greenkeeper pull request.

Sorry that this is a bit cumbersome, we will look into making this easier.

**Comment by riccardoerra** [comment]
@finnp Thanks for explaining the right method for implementing Greenkeeper!

**Comment by merlinnot** [comment]
@finnp How long do we have to wait for the pull request to show up? Following you guide, I've deleted all greenkeeper/initial branches from my repos and re-enabled greenkeeper. These branches were recreated, but there is no pull request in any of them.

**Comment by riccardoerra** [comment]
@merlinnot I just did what @finnp suggested and I got my pull request I would say 15 minutes after I enabled again Greenkeeper.

**Comment by finnp** [comment]
@merlinnot The pull request is created once there is a CI status reported on that branch. If you don't have a CI you will not get the initial pull request. Greenkeeper is only usably if there is a CI configured.

**Comment by merlinnot** [comment]
Hm. My CI won't run for this branch since greenkeeper is not a collaborator. Our CI runs pipelines only for branches which are created/committed to by project members. I've tried to make a commit to this branch rearranging badges (Greenkeepers' was in a bad place anyway), CI reported status and pull request was actually created. Then I've merged it but it is still disabled.

**Comment by finnp** [comment]
@merlinnot Yes you are definitely allowed to make changes to the branch. However note that if our CI is not running for commits made by Greenkeeper, it will not work as expected. Greenkeeper needs your CI status to detect breaking changes, so you should make sure its commits are also run by your CI

**Comment by ismay** [comment]
@finnp So how about this: https://github.com/ismay/stylelint-no-unsupported-browser-features. I didn't merge the initial PR (accidentally removed the branch). I've enabled and disabled it countless times, but haven't received any additional greenkeeper PR and the badge still says it's enabled.

Why am I not receiving the initial PR in this case. I should right?

**Comment by finnp** [comment]
@ismay If all of your dependencies are up-to-date you don't get an initial pull request, but the repository is enabled right away.
