### ISSUE TITLE
Greenkeeper not creating pull request/branches/...

### ISSUE THREAD

**Issue by bp323** [greenkeeperio/greenkeeper#403]
Hi, Bert from oneUp.company here.

We have enabled Greenkeeper for a private repository and noticed after half an hour that nothing had been created yet. No pull request, branches, labels, etc. Is there a known issue with private repositories? I am sure everything is configured properly since configuration is very lightweight through Github. Any help or indicators would be appreciated.

Cheers

**Comment by janl** [comment]
Heya,
We're currently affected by the DigitalOcean SFO2 issues. Things should go back to normal once they resolve: https://status.digitalocean.com/#

We apologise for the trouble!

**Comment by bp323** [comment]
Thanks, I'll report back when I see some movement!

**Comment by janl** [comment]
things are picking up already, but it’s still a bit touch and go.

**Comment by bp323** [comment]
It looks as though the digitalocean status returned to normal. We are not seeing anything yet though.

**Comment by bp323** [comment]
I was able to 'fix' the issue by reinstalling the integration to our Github repository. Problem solved!

**Comment by janl** [comment]
👍
