### ISSUE TITLE
CLAHub commit status check breaks build

### ISSUE THREAD

**Issue by alebiavati** [greenkeeperio/greenkeeper#405]
We recently started using Greenkeeper on our open source repositories and we are getting a lot of issues opened with title **An in-range update of <module> is breaking the build** even though the build should pass.

We use commit status checks to make sure PRs don't break the build and one of our checks is from CLAHub (https://www.clahub.com/). This commit status check makes sure that all contributors of the PR have signed the CLA on CLAHub.

See example Issue here:
https://github.com/CAAPIM/webpack-config/issues/39

I tried disabling the CLAHub check from the branch protection settings so that the CLAHub check is not required anymore, but greenkeeper seems to still consider the build as failed.

Thank you in advance for your help

**Comment by boennemann** [comment]
Thanks for your report. The underlying problem is tracked in this issue #329, so I'll go ahead an close this one as a duplicate to keep our issue tracker clean and actionable.

Thanks!
