### ISSUE TITLE
updated peerDependencies instead of devDependencies

### ISSUE THREAD

**Issue by kellyselden** [greenkeeperio/greenkeeper#408]
https://github.com/kellyselden/eslint-mocha/issues/87

https://github.com/kellyselden/eslint-mocha/compare/greenkeeper/mocha-3.3.0

<img width="748" alt="screen shot 2017-04-24 at 10 18 45 am" src="https://cloud.githubusercontent.com/assets/602423/25349639/642ae0ca-28d7-11e7-90eb-1928f68f5d12.png">

**Comment by Realtin** [comment]
This should be resolved with https://github.com/greenkeeperio/greenkeeper/pull/465

**Comment by rmehner** [comment]
#465 is merged & deployed. Thanks for reporting this and have a great day!

**Comment by kellyselden** [comment]
Thanks for fixing!
