### ISSUE TITLE
Better handling of duplicate module in dependencies and devDependencies

### ISSUE THREAD

**Issue by lukechilds** [greenkeeperio/greenkeeper#409]
Currently if a module exists in both `dependencies` and `devDependencies` only `devDependencies` is updated. I think it should update both, and if it can only be one, then `dependencies` should be the priority.

e.g: https://github.com/lukechilds/expired/pull/17

`date-fns` is both a `dependency` and `devDependency`, however the version locked dependency doens't actually get updated by Greenkeeper.

**Comment by lukechilds** [comment]
Any update on this?

I get comments on the previously mentioned PR (https://github.com/lukechilds/expired/pull/17) every time a new version of `date-fns` is released. The GK commit always wants to update `devDependencies` and not `dependencies` and is incredibly easy to miss.

IMO this is a pretty big issue, I'm using Greenkeeper to keep my dependencies up to date, however with this bug if I merge the PR it's keeping my dependency locked to an out of date version.

**Comment by Realtin** [comment]
Hey 👋 

could you elaborate on the use case of having a dependency as both dependency and devDependency?

**Comment by lukechilds** [comment]
Yeah sure, so say for example my package makes use of a module, e.g (`get-stream` to get a stream as a buffer). Then in my tests I'm also using `get-stream` to check that a stream equals a certain value. `get-stream` is then a dependency of my package (`dependency`) and also a dependency of my tests (`devDependency`).

In the future I may wish to refactor my package to not use `get-stream`. So I could then remove `get-stream` as a `dependency` but keep it as a `devDependency`.

**Comment by Realtin** [comment]
Hey there,

thanks for the explanation :) However, in a quick test we saw that in your case, npm even throws a warning when you include the same dependency in both `dependencies` and `devDependencies`, e.g.:

`npm WARN The package standard is included as both a dev and production dependency.`

So in your example, we'd recommend removing `get-stream` from `devDependencies`. If you end up refactoring the package to not use `get-stream` anymore, you can move it from `dependencies` to `devDependencies` and everything still works as expected, also from Greenkeeper's side.

**Comment by lukechilds** [comment]
Yeah, I actually discussed this with npm before, you can read the discussion here: https://github.com/npm/npm/issues/17023 (sorry, probs should have linked to that in my last message).

It's worth noting this worked with npm before version 5 (when I created this issue), and it's only npm5 that gives the warning.

I still think this is a valid use case that needs supporting, however if you decide not to support separate `dependencies`/`devDependencies` (which is fair enough if npm themselves are saying it's no longer supported) then I think if Greenkeeper detects both it should update the `dependency` instead of the `devDependency`.

**Comment by Realtin** [comment]
We build something that should handle this issue: https://github.com/greenkeeperio/greenkeeper/pull/467 
:)

**Comment by lukechilds** [comment]
Awesome 🎉

**Comment by rmehner** [comment]
The change is deployed now. Thank you for taking the time to report this and giving us long explanations 🙏 

I'll close this issue, but feel free to reopen if you still run into this.

Thanks again!
