### ISSUE TITLE
Installing green keeper, but doesn't do anything?

### ISSUE THREAD

**Issue by minemidnight** [greenkeeperio/greenkeeper#412]
I install the bot into my repos but all it does is make the initial branch then nothing else

**Comment by finnp** [comment]
Have you configured a CI on this repository?

**Comment by minemidnight** [comment]
Sorry for the late reply, all I did was follow the installation guide which is to click the install button. The repo is minemidnight/oxyl. What exactly am I supposed to do?

**Comment by boennemann** [comment]
Hey @minemidnight,

if you enable the Integration for a repository you will receive a pull request with all necessary information. If that didn't arrive could you please try to reenable that repository?

I'll go ahead and close this issue. Happy to reopen if the problem persists.

Best,
Stephan
