### ISSUE TITLE
Disable a repository after it has been enabled

### ISSUE THREAD

**Issue by satazor** [greenkeeperio/greenkeeper#413]
I'm unable to disable a few repositories that have been enabled via GitHub integration.

For instance, I would like to disable https://github.com/IndigoUnited/pino-err-serializer since it has been deprecated. I've tried `greenkeeper disable` and while it says `IndigoUnited/pino-err-serializer is already disabled`, I continue to receive PRs on updates.

Disabling via "whitelist" in the GH integration settings is not an option.. it doesn't scale well.

Additionally, how can I enable a repository in which I've closed the initial PR (the one that if you accept, it will enable greenkeeper)?

**Comment by boennemann** [comment]
Hey @satazor,

> For instance, I would like to disable https://github.com/IndigoUnited/pino-err-serializer since it has been deprecated. I've tried greenkeeper disable and while it says IndigoUnited/pino-err-serializer is already disabled, I continue to receive PRs on updates.

The CLI is supposed to work with the old Greenkeeper. Greenkeeper 2 only works via GitHub's web interface.

> Disabling via "whitelist" in the GH integration settings is not an option.. it doesn't scale well.

We feel you. We wish GitHub added a blacklist option, which we told them already. While we're waiting for them to add this options, there isn't much we can do.
You could disable all repositories, and then enable them again. This won't affect repos that are fully up to date. For all others you would receive another initial PR that you could decide to either merge or close

> Additionally, how can I enable a repository in which I've closed the initial PR (the one that if you accept, it will enable greenkeeper)?

Either reopen the PR and merge it, or reenable the repository in the integration settings.


I hope this somewhat helpful.


Best,
Stephan
