### ISSUE TITLE
no PRs for private package

### ISSUE THREAD

**Issue by travi** [greenkeeperio/greenkeeper#414]
i finally got around to moving one of our private packages from an internal nexus registry to private npm, hoping that it would allow greenkeeper PRs to start working.

I've used the `wombat-cli` to set up webhooks for our scope using the command in the initial PR and can see that the webhook is firing successfully and that it results in a `202` from `hooks.greenkeeper.io` using `wombat hook ls`. 

however, the branch and PR for the project that consumes that package never get added. both the package project and the consumer are receiving greenkeeper PRs for other packages. i've also disabled and re-enabled the greenkeeper integration for both projects, but have not seen any change in behavior.

what suggestions can you provide to investigate this further from my side? is there something that needs to be nudged on your side?

**Comment by janl** [comment]
Hi, this should be fixed, please re-open if you see this again.

Thank you for your patience!

**Comment by travi** [comment]
thanks for getting this resolved!
