### ISSUE TITLE
add badge to my project

### ISSUE THREAD

**Issue by fibo** [greenkeeperio/greenkeeper#415]
Hi,
I have few projects that use greekeeper and it is great. I tryed to add a badge, how can I activate it?

I copyed it from

```
[![Greenkeeper badge](https://badges.greenkeeper.io/ForbesLindesay/uglify-to-browserify.svg)](https://greenkeeper.io/)
```

but if I replace with my path I see a disabled badge, even if greenkeeper is working, any hint?

[![Greenkeeper badge](https://badges.greenkeeper.io/fibo/zeroconf-redux.svg)](https://greenkeeper.io/)

**Comment by fibo** [comment]
I also installed greenkeeper v2 recently.

**Comment by boennemann** [comment]
Hey @fibo,

the badge only works if you enable Greenkeeper 2. The initial pull request will add the badge for you.
I hope that works for you.

Best,
Stephan

**Comment by fibo** [comment]
I updgraded greenkeeper.io in two projects:

* https://github.com/fibo/zeroconf-redux did not received the PR.
* https://github.com/fibo/SVGx did and has a badge now.

**Comment by finnp** [comment]
@fibo Somehow there was no CI status created on https://github.com/fibo/zeroconf-redux/commits/greenkeeper/initial. That's why it is not enabled there. You might have to check you CI.

**Comment by fibo** [comment]
ah, maybe you check if the badge is already there, I added it by hand

**Comment by fibo** [comment]
I merged the greenkeeper/initial branch, the badge is still disabled. I did not configured any CI, I don't know what could be wrong, on the other repo I had no issue.

How can I repeat the procedure to upgrade, maybe if I remove the repo and then add it again? Any hint?
