### ISSUE TITLE
Supports shields.io parameters?

### ISSUE THREAD

**Issue by breeswish** [greenkeeperio/greenkeeper#416]
I would like to see this working:

https://badges.greenkeeper.io/some_one/some_project.svg?style=flat-square

Currently greenkeeper won't return a flat-square style badge..

**Comment by christophwitzko** [comment]
Hi @breeswish,

this sounds like a great feature. At the moment we are very busy shipping other Greenkeeper features, but we just have open sourced our [badges webservice](https://github.com/greenkeeperio/badges). If you want to contribute this feature, feel free to open a pull request. ☺️ 

Have a great day,
Christoph 🌴

**Comment by janl** [comment]
This has been shipped in March ;)

**Comment by j-f1** [comment]
@janl It looks like the `style` parameter still isn’t accepted:

`https://badges.greenkeeper.io/user/repo.svg?style=flat-square` ➡️ <sub><sub>![https://badges.greenkeeper.io/greenkeeperio/greenkeeper.svg?style=flat-square](https://badges.greenkeeper.io/greenkeeperio/greenkeeper.svg?style=flat-square)</sub></sub>

**Comment by janl** [comment]
fixed!
