### ISSUE TITLE
Managing connected dependencies

### ISSUE THREAD

**Issue by posva** [greenkeeperio/greenkeeper#419]
Hi, I was wondering if there's a way to handle update on multiple dependencies at the same time. When using Vue in projects and libs, we also need to use vue-template-compiler. This package is auto generated at the same time as Vue and therefore both have the same version and both have to be updated at the same time.
Is there a way to tell greenkeeper to update those two libs at the same time? At the moment gk tries to update one of them and the build fails, so it opens a new issue every time there's a new version of Vue. Will using `*` as the version work?

**Comment by boennemann** [comment]
Hey @posva,

thanks for creating this issue. We're currently tracking the same/very similiar problem here https://github.com/greenkeeperio/greenkeeper/issues/283

I'll go ahead and close this issue as duplicate to keep our issue tracker clean and actionable.

Best,
Stephan

**Comment by posva** [comment]
Ok, sorry, I looked up for an open issue but couldn't find it 😅
