### ISSUE TITLE
Font contrast on greenkeeper.io

### ISSUE THREAD

**Issue by bnb** [greenkeeperio/greenkeeper#43]
Just found the site through Twitter, and I replied that it needed more contrast, which got a reply from @janl asking me to report it with demographics.

**OS**: Win10
**Browser**: Firefox Developer Edition (43.0)
**Reproduce**: Visit the site.
**Problem**: There are three colors for text on the site: heading yellow, bold/code lime, and dark body mint. The problem I have is there isn't enough difference between the colors (contrast) to make them distinguishable. The yellow is the hardest to read against the lime, and to a lesser extent the dark mint. The lime and dark mint are on the bleeding edge of compatibility with each other.

**Comment by Charlotteis** [comment]
Seconded. Though they do pass the accessibility requirements, (which is why I didn't change them), they could be a little friendlier to the eye. Happy to help :)

**Comment by boennemann** [comment]
Could you give us your feedback on the new version? We think it's good now, but we'd love to hear what you think.

Thanks so much,
Stephan

**Comment by espy** [comment]
@Charlotteis If you have any specific suggestions, I'd love to hear them :)

**Comment by Charlotteis** [comment]
Hey @espy! I think the new design has really improved things. My main concern was the darker green colour but it does pass colour contrast tests: http://leaverou.github.io/contrast-ratio/#%2338CF38-on-%2326292C, better than before I believe so good job:). Would like to hear if @bnb thinks the same!

**Comment by boennemann** [comment]
Thanks for your input everyone :+1: 

I'll close this now, but we can reopen immediately if there is the need.
