### ISSUE TITLE
Greenkeeper keeps commenting about new versions for a closed PR

### ISSUE THREAD

**Issue by Standard8** [greenkeeperio/greenkeeper#430]
https://github.com/mozilla/one-off-system-add-ons/pull/31 was closed a while ago, however, rather than opening a new PR, greenkeeper insists on commenting on the old PR continuously.

This makes it harder to track, as someone has to notice that and create a new PR (and get it reviewed by someone else).

I think the issue might be that a separately created PR did the version bump that landed, and closed the PR, but I'm not altogether sure.

**Comment by christophwitzko** [comment]
Hey @Standard8, it looks like the pull request state has not been automatically updated in our database. I have done that now manually. If this problem still occurs, feel free to reopen this issue.
