### ISSUE TITLE
"Greenkeeper could not be activated" message shows up despite successful build

### ISSUE THREAD

**Issue by derhuerst** [greenkeeperio/greenkeeper#432]
see https://github.com/derhuerst/vbb-stations-with-wifi/issues/1

The build on `greenkeeper/initial` succeeded, but Greenkeeper opened the issue and still doesn't close it.

Lovely service btw! 😍

**Comment by finnp** [comment]
Thank you for letting us know about this ☺️ 

I just looked into it and was not able to find the issue. It does not appear to be broken in general, but I also couldn't find any error related to that specific repository. It might be that we somehow lost or didn't get that status event from GitHub.

Could you delete the `greenkeeper/initial` branch, remove that repository from Greenkeeper and re-add it? This will trigger another `greenkeeper/initial` branch. Hopefully after the branch is built, you should get an initial PR.

If not I'll continue looking into why this fails for your repository.

**Comment by derhuerst** [comment]
this seemed to work, thanks!

**Comment by finnp** [comment]
Okay great 👍  I'll close this issue as a hiccup then.

**Comment by lukechilds** [comment]
I'm having a similar issue.

I've got Greenkeeper enabled for all my repos. Does this mean to resolve the issue I need to disable Greenkeeper, delete the branches from all of my repos, and then re-enable Greenkeeper and merge the initial pull requests on all my repos again? Because I have quite a few repos.

**Comment by kt3k** [comment]
I'm having the same issue on several repos.

https://github.com/kt3k/kocha/issues/27
https://github.com/kt3k/bundle-through/issues/13
https://github.com/kt3k/berber/issues/3

In all repos `greenkeeper/initial` branch got commit statuses (2 success, 1 failure) from CI, but greenkeeper bot says it didn't.

**Comment by kt3k** [comment]
The above repos got initial PRs from greenkeeper several hours later and then I was able to enable greenkeeper on the all repos. Thanks for the great service!

**Comment by KharitonOff** [comment]
I have the same issue with greenkeeper: 
![screen shot 2017-06-19 at 13 10 52](https://user-images.githubusercontent.com/8480657/27282596-f3b27dee-54f0-11e7-84d3-345ce587369a.png)
It looks like Travis set the status on the second commit and greenkeeper couldn't recognise it.
https://github.com/cla-assistant/cla-assistant/issues/235

**Comment by derhuerst** [comment]
Got it once more. https://github.com/derhuerst/read-audio-tags/issues/1

**Comment by Realtin** [comment]
@derhuerst Greenkeeper waits 15min for a CI status before assuming there is no CI. In your case The build took about 5 min from being triggered to the begin of the run and then had a total time of ~11 min. 

You could open a PR from [your greenkeeper/initial branch](https://github.com/derhuerst/read-audio-tags/tree/greenkeeper/initial) yourself or if you want I can also reset your repository and you'll get a fresh initial branch. But you could still run into the time out issue. I'll discuss with the team if it makes sense to extend the time we wait for CI statuses.

**Comment by derhuerst** [comment]
I can fix it by myself. I'm just letting you know that this issue keeps appearing for me even though it's closed.

**Comment by gr2m** [comment]
@derhuerst just fyi the timeout was bumped to 30minutes via [v2.11.5](https://github.com/greenkeeperio/greenkeeper/releases/tag/v2.11.5), so the problem should no longer occur for you

**Comment by derhuerst** [comment]
I'm don't know how the communication between Travis and greenskeeper works, but it just came to my mind that it might also be related to build delays. On Travis, the macOS build are often delayed be at least 5 minutes, sometimes even 30 minutes. Do you wait for a "build queued", "build running" or "build successful" webhook/event?

**Comment by gr2m** [comment]
@derhuerst I’ll look into this next week, thanks for caring Jannis 👍

**Comment by rmehner** [comment]
@derhuerst good points. In fact, we don't listen to Travis, but simply for a commit status to be set. That makes us independent from the CI system in use and allows us to function with other CI services as well.

@Realtin and I discussed looking for the `pending` status on the commit before we open up the timeout issue, but then again there might be other pending statuses on the commit that are entirely unrelated to CI.
