### ISSUE TITLE
Update to breaking GitHub hooks changes

### ISSUE THREAD

**Issue by finnp** [greenkeeperio/greenkeeper#440]
GitHub will deprecate a few things for the Webhooks in November. So we should switch to the new names:

Github replaced  `integration_id` with `app_id`

The `integration_installation_repositories` will be deprecated in favor of `installation_repositories` and `integration_installation` in favor of `installation_repositories`

See https://developer.github.com/webhooks/

**Comment by Realtin** [comment]
should be an easy change for us. But we would need to test it in the staging system. @christophwitzko how can we access that?
