### ISSUE TITLE
Greenkeeper keeps creating branches and then deleting them later

### ISSUE THREAD

**Issue by turt2live** [greenkeeperio/greenkeeper#441]
The bot keeps creating branches for minor updates, but not PRing them. It just deletes the branch shortly after.

This is causing excessive notifications for me and is quite annoying.

Here's one of the commits it created: https://github.com/turt2live/matrix-dimension/commit/f23fae8ceab64680c3a95dc246ec52bfcc0bb22b 

Another is here: https://github.com/turt2live/matrix-dimension/commit/db771744d1bd648ef8bc18d4a67946f4313a8f15

It didn't PR either of these, and the first one seems unneeded to me. Is there some configuration I might be missing?

**Comment by Arcanemagus** [comment]
That's how it's supposed to work. It creates the branch for _every_ new version of your dependencies, runs CI, and only if the build failed or it's a version outside of your current range does it actually create a PR/issue.

**Comment by turt2live** [comment]
That's kind of annoying. But alright.
