### ISSUE TITLE
Contributing / IRC?

### ISSUE THREAD

**Issue by Druotic** [greenkeeperio/greenkeeper#449]
I'm interested in contributing some changes in the near future and was hoping there might be an IRC channel, some contributing guidelines, and/or some basic instructions for getting a local dev instance up and running. So far, I haven't found much. Can someone point me in the right direction? Thanks!

**Comment by charlieduong94** [comment]
I too am interested in contributing to this project. I tried pulling down parts of the project down earlier today and wasn't quite able to get the project running locally or test running properly either.

**Comment by christophwitzko** [comment]
Heya, thanks for reaching out. We are setting up a community slack at the moment and we will also write down a document on how to run a local test setup. Stay tuned. ☺️

**Comment by christophwitzko** [comment]
Hey everyone, we just have created our Greenkeeper community slack. 🎉 
https://greenkeeper-slack.herokuapp.com/
For support requests please continue to use [support@greenkeeper.io](mailto:support@greenkeeper.io).
