### ISSUE TITLE
Changelog in PR attributes (and potentially closes) issues of own repo

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#45]
Full conversation: https://twitter.com/patrickkettner/status/651115260003250176

Solution: Use GitHub API to render markdown in correct context: https://developer.github.com/v3/markdown/ and add HTML to PR body 
Or maybe we can just change the content type on the release requests to get it pre-rendered to begin with.

**Comment by boennemann** [comment]
Resolved as of now by using the html media type.

@patrickkettner

**Comment by hzoo** [comment]
:smile:
