### ISSUE TITLE
Greenkeeper not getting latest release of module

### ISSUE THREAD

**Issue by amalv** [greenkeeperio/greenkeeper#450]
In the `package.json` the `react-dropzone` version is set as `^3.13.1` and the latest release is `^3.13.2` (since 15 days ago), however no Greenkeeper PR has arrive in order to update the module.

Other module updates have been properly handled by Greenkeeper, any idea why is not updating `drop-zone` to the latest release version?

**Comment by gr2m** [comment]
`^3.13.2` is within the range of `^3.13.1` so it does not get updated by Greenkeeper. Greenkeeper does however create branches to make sure that new versions which are within your ranges do not break your tests, see https://blog.greenkeeper.io/announcing-real-time-dependency-break-detection-for-greenkeeper-4f7558c10d77

**Comment by amalv** [comment]
I've tried to use `yarn install` in order to update the `react-dropzone` release version but the `yarn.lock` does not get updated and the release version stays the same.

However I understand now that this is not a Greenkepeer problem, but thanks anyways.

**Comment by gr2m** [comment]
check out https://blog.greenkeeper.io/greenkeeper-support-for-lockfiles-9d9c282efcbe for lock files support
