### ISSUE TITLE
Can't get greenkeeper to update after "no CI enabled" issue

### ISSUE THREAD

**Issue by mattiamanzati** [greenkeeperio/greenkeeper#452]
Hello everyone, first of all, thanks for this amazing service!

I tried to initialize greenkeeper few days ago, but as no CI was enabled, it opened an issue and relative init branch.
https://github.com/mattiamanzati/mobx-state-tree-playground/issues/1

After I updated the master with CI, no update on the issue. So I have deleted the initial branch, uninstalled and reinstalled greenkeeper in the repo and closed the old issue, but nothing seems to trigger.

What did I do wrong? :)

Thanks for any help!

**Comment by overlookmotel** [comment]
I have the same issue here: https://github.com/overlookmotel/got-resume/issues/2

**Comment by overlookmotel** [comment]
NB I've got Greenkeeper enabled for all my repos.

**Comment by overlookmotel** [comment]
Related to https://github.com/greenkeeperio/greenkeeper/issues/432?

**Comment by mattiamanzati** [comment]
I did as @finnp sayed, but with no luck :/

**Comment by Realtin** [comment]
Closing this because it seems to work now for all of you. If it comes up again please reopen.
