### ISSUE TITLE
Support: Configure Greenkeeper to create PRs against dev branch instead of master

### ISSUE THREAD

**Issue by ORESoftware** [greenkeeperio/greenkeeper#454]
Ughh sorry you probably have heard this question before, but how can I configure Greenkeeper to create PRs against dev branch instead of master?

thanks!

**Comment by ORESoftware** [comment]
bump pls thx

**Comment by Realtin** [comment]
Greenkeeper makes it's pull request against the **default branch** of your repository. You can set it (in the repository settings) to your dev branch.

**Comment by ORESoftware** [comment]
Thanks, since there may be other factors that keep someone's default branch to be master, might there not be a way to configure greenkeeper to make PRs against a non-default branch? :)

**Comment by ORESoftware** [comment]
One way to do this, I imagine, would be to have users place a .greenkeeper config file in each project where they did not want default settings, etc.

**Comment by thebrodmann** [comment]
It's really frustrating, is there any plan for this?
