### ISSUE TITLE
Review all comments and PR messages GK posts for actionability

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#470]
Some comments, like the `Greenkeeper could not be activated` one, aren‘t totally clear on what actions are expected of the user:

![bildschirmfoto 2017-07-11 um 16 21 55](https://user-images.githubusercontent.com/391124/28073132-2a36ea06-6655-11e7-99f4-f5fa2b69bb00.png)

This one, for example, requires dis- and re-enabling GK so it can try sending the initial PR again, but that’s not mentioned or explained.

**Comment by Realtin** [comment]
For the CI issue we just merged a better wording: https://github.com/greenkeeperio/greenkeeper/pull/466
