### ISSUE TITLE
How frequently update PR happens?

### ISSUE THREAD

**Issue by netil** [greenkeeperio/greenkeeper#473]
My project is https://github.com/naver/billboard.js, and I integrated last week.

I merged the initial PR from the bot, and seeing the badge looks greenkeeper is enabled.
![](https://badges.greenkeeper.io/naver/billboard.js.svg)

But, one of the modules were updated after the greenkeeper initial commit, and is not creating any new PR from the bot. There's something more to do? or I missed some setups?

Thanks in advance.

**Comment by Realtin** [comment]
Hey, I can see that there are Greenkeeper PRs on your repo so I'm closing this one.
