### ISSUE TITLE
Error: can not identify job owner

### ISSUE THREAD

**Issue by Realtin** [greenkeeperio/greenkeeper#477]
Since July 8th everyday at 3:16 pm this error occurs.

https://rollbar.com/neighbourhoodie/gk-jobs/items/1276/?item_page=0&item_count=100&#instances

**Comment by finnp** [comment]
It is unable to identify the job owner of `schedule-stale-initial-pr-reminders`. It expects a user to be associated with this job, but there should not be one.

It would have to be whitelisted here: https://github.com/greenkeeperio/greenkeeper/blob/4e7d407d91934a4a12763fe2cab94bdbfa892a5c/index.js#L78.

**Comment by Realtin** [comment]
Ah cool, will fix it with @rmehner tomorrow!
