### ISSUE TITLE
ERR! enable Couldn’t find a repo with this slug. Either it doesn’t exist on GitHub, it’s a fork, or private.

### ISSUE THREAD

**Issue by wulfsolter** [greenkeeperio/greenkeeper#48]
┌─[wulfsolter@Wulfs-MBP]-[2015-10-09 00:58 - 1444305503]-[~/Code/mongo-express] (master)
    └─[$]-> greenkeeper -v
    2.1.1
    
    ┌─[wulfsolter@Wulfs-MBP]-[2015-10-09 00:58 - 1444305520]-[~/Code/mongo-express] (master)
    └─[$]-> git remote -v
    origin  git@github.com:andzdroid/mongo-express.git (fetch)
    origin  git@github.com:andzdroid/mongo-express.git (push)
    
    ┌─[wulfsolter@Wulfs-MBP]-[2015-10-09 00:58 - 1444305525]-[~/Code/mongo-express] (master)
    └─[$]-> greenkeeper enable
    🌴  info enable The GitHub slug is: andzdroid/mongo-express
    🌴  ERR! enable Couldn’t find a repo with this slug.
    🌴  ERR! enable Either it doesn’t exist on GitHub, it’s a fork, or private.
    
    ┌─[wulfsolter@Wulfs-MBP]-[2015-10-09 00:58 - 1444305537]-[~/Code/mongo-express] (master)
    └─[$]-> greenkeeper enable --slug andzdroid/mongo-express
    🌴  info enable The GitHub slug is: andzdroid/mongo-express
    🌴  ERR! enable Couldn’t find a repo with this slug.
    🌴  ERR! enable Either it doesn’t exist on GitHub, it’s a fork, or private.
<img width="651" alt="screen shot 2015-10-09 at 12 59 06 am" src="https://cloud.githubusercontent.com/assets/1692132/10365622/41b2da42-6e21-11e5-99c5-1c94dffa9761.png">

https://github.com/andzdroid/mongo-express is a public repo to which I have write access, and I have tried `gk logout && gk login`.

**Comment by boennemann** [comment]
Hey @wulfsolter,

thank you for this issue. Do you have admin rights? They're required to enable repos, because we need to create some webhooks for you.

We've just pushed a new version of the CLI that better explains the error you encountered.

Best,
Stephan

**Comment by boennemann** [comment]
Just realized that the repo you're trying to enable is a personal repo of another GitHub user, which unfortunately means you can't enable it for them, because you can't have admin access on it.

Best,
Stephan

**Comment by wulfsolter** [comment]
Hmm. Greenkeepr worked the first time on this repo as installed by me, made
commits to lock in versions and a few upgrades. On the 30th Sept you sent
me a very kind email of apologies for falsely attributed PRs (
https://github.com/kentcdodds/invoke-filter/pull/7 ), but it hasn't worked
since.

While I am not the creator of this repo, I do have admin ability - to
create and merge PRs.

Closed #48 <https://github.com/greenkeeperio/greenkeeper/issues/48>.

—
Reply to this email directly or view it on GitHub
<https://github.com/greenkeeperio/greenkeeper/issues/48#event-430682515>.

**Comment by boennemann** [comment]
Hey @wulfsolter,

we allowed enabling for a short time, because we didn't enforce the required rights. In this case the webhooks enabling failed and we could never sync your package.json content, which is required to send you PRs for all dependencies.

We're working on manual webhooks enabling, so admin rights are no longer required to be granted to us (https://github.com/greenkeeperio/greenkeeper/issues/46), but with that working GitHub would still require this to be done by @andzdroid.

Thanks for understanding

Best,
Stephan

// cc @christophwitzko
