### ISSUE TITLE
Update package.json in-place, preserve formatting/comments

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#49]
e.g. using [jsup](https://github.com/substack/jsup)

**Comment by mathiasbynens** [comment]
:+1:

**Comment by ljharb** [comment]
or https://www.npmjs.com/package/json-file-plus which i created for this sole purpose.

This currently makes PR diffs unreadable for those of us that don't use two-space formatting: https://github.com/ljharb/find-value-locations/pull/1/files and also makes merging these PRs a non-starter.

**Comment by boennemann** [comment]
Thanks for your input @ljharb :)

We haven't fixed this yet, because with jsup we can't set [a property on a child object](https://github.com/substack/jsup/pull/3) and json-file-plus won't work without the filesystem.

I think we might use the json-file-plus approach for operating on strings and make that it's own module.

Expect an update soon.

Best,
Stephan

**Comment by ljharb** [comment]
@boennemann If you do, please publish it and PR it into `json-file-plus` so we can benefit from using the same code :-)

**Comment by boennemann** [comment]
Alright so we're no longer touching your tabs now :+1: 

@ljharb I ended up building this very basic thing, so we could just get this fix out. If you really want to use it for json-file-plus, then let me know after looking at it ;) https://github.com/boennemann/json-preserve-indent

**Comment by ljharb** [comment]
@boennemann Awesome! I don't want to add a lodash dep, so instead I factored out the guts of `json-file-plus` into "JSONData", a property on `json-file-plus`'s default export. Feel free to use it instead of `json-preserve-indent` if you find it valuable :-)

Thanks for fixing this!
