### ISSUE TITLE
"Action required: Greenkeeper could not be activated" impossible to execute

### ISSUE THREAD

**Issue by ankon** [greenkeeperio/greenkeeper#498]
> Once you have installed CI on this repository, you’ll need to re-trigger Greenkeeper’s initial Pull Request. To do this, please delete the greenkeeper/initial branch in this repository, and then _remove and re-add_ this repository to the Greenkeeper integration’s white list on Github.

The repository in question is part of an organization, and the organization has whitelisted all repositories for greenkeeper. Therefore I cannot remove/add the repository -- and I'm a bit too scared to disable the whitelist just to try whether that triggers anything. 

Note that the underlying issue is that greenkeeper found the new repository, and then started on it before the CI was in place. 

(https://github.com/Collaborne/intl-chrome-i18n/issues/2)

**Comment by gr2m** [comment]
Thanks Andreas, I’ll have a look today!

**Comment by gr2m** [comment]
Hi @ankon, I’ve reset the single repository and I think things worked out this time, can you confirm?

**Comment by ankon** [comment]
@gr2m yes, this time things worked out, and the "Action required" issue was closed, and the the initial PR was submitted successfully. 

In the grander scheme of things though: would it be "ok" if I temporarily enabled the whitelist in the settings, save, and then disable it again? We do have a couple of projects in this state actually :)

**Comment by rmehner** [comment]
@ankon We're working on something that allows you to reset repos within the accounts app, right now it's only accessible to us :)

We don't recommend using the "enable all" approach, as this doesn't allow you a more fine grained control over which repos Greenkeeper should be enabled for and what repo is ready to use it (read: CI is ready to run, package.json exists).

In your case, if you disable the "enable all", we'll delete all our knowledge of your repos from our database. If you then add a new repo via the whitelist, it will run through the regular initial process (create initial branch -> wait for commit status from CI -> create initial PR).

If you have other repos that you need us to reset, don't hesitate to just post them here, for us it's just a command away :)

**Comment by ankon** [comment]
Thanks for the offer to press buttons for me :)

Here's another one:
https://github.com/Collaborne/eslint-config-collaborne/issues/1

**Comment by gr2m** [comment]
done 👍

**Comment by ankon** [comment]
https://github.com/Collaborne/incremental-json-parser/issues/1 appeared before I had Travis enabled, branch is deleted. 

/me is wondering whether it would work to just create a PR manually from the branch and/or just add the badge to the right place to enable things :)

**Comment by ankon** [comment]
Ok, I this isn't workable for us: every single new repository ends up with the 'Action required', and every time I either have to kill the ticket (non-OSS project, but we're not using greenkeeper.io with a paid subscription due to the pricing model), or delete the branch and ticket, link it to here (if I don't forget) and hope it eventually figures things out.

So, I've now enabled the whitelist, and will just go through all our OSS repos again to enable them when I have the time for that.

**Comment by Tiendq** [comment]
Even when I enable whitelist repos, I needed to add/remove my repo 2 times to make Greenkeeper to create a pull request. I merged the initial pull request 2 hours ago, but Greenkeeper is still disabled for my repo now. Could you please have a look at it? @gr2m 

https://github.com/Tiendq/youtube-embed-video

Thanks,

**Comment by Realtin** [comment]
@Tiendq I enabled it. If you encounter any more problems write a short mail to  support@greenkeeper.io 🌴 📫

**Comment by Tiendq** [comment]
@Realtin I just checked README file, it's enabled now. Thanks.

**Comment by janl** [comment]
closing this in favour of https://github.com/greenkeeperio/greenkeeper/issues/355
