### ISSUE TITLE
Integration still isn't enabling on newly added/renamed repositories

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#509]
When the integration is enabled for an entire organization it seems to ignore all repositories added or renamed after the integration was first enabled.

Most recently the [linter-hadolint](https://github.com/AtomLinter/linter-hadolint) repository was added to the [AtomLinter](https://github.com/AtomLinter) organization yesterday but as you can see it isn't enabled:
* [linter-hadolint](https://github.com/AtomLinter/linter-hadolint): [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-hadolint.svg)](https://greenkeeper.io/)

Note: This is a duplicate of #395! @boennemann never re-opened that when I reported that it was still an issue. There are _many_ more examples of repositories that GreenKeeper has still failed to enable itself on in that issue.

**Comment by gr2m** [comment]
@Arcanemagus I’m very sorry for the trouble this causes you. The reasons behind this are very complicated. To fix the symptoms, we are working on adding a simple way that you can reset a repository in https://account.greenkeeper.io. But right now, only we can do that for you. If you could send me list of repositorys in the format `:owner/:name`, I’ll happily do that for you. You can also send them to support@greenkeeper.io if yo u don’t want to share them publicly.

**Comment by Arcanemagus** [comment]
@gr2m Here is the list of packages that currently show as `not found`:

* [linter-gfortran](https://github.com/AtomLinter/linter-gfortran)
* [linter-hadolint](https://github.com/AtomLinter/linter-hadolint)
* [linter-spell](https://github.com/AtomLinter/linter-spell)
* [linter-spell-project](https://github.com/AtomLinter/linter-spell-project)
* [linter-spell-ruby](https://github.com/AtomLinter/linter-spell-ruby)
* [linter-spell-javascript](https://github.com/AtomLinter/linter-spell-javascript)
* [linter-spell-html](https://github.com/AtomLinter/linter-spell-html)
* [linter-spell-latex](https://github.com/AtomLinter/linter-spell-latex)
* [linter-spell-word-list](https://github.com/AtomLinter/linter-spell-word-list)

Note that the last one currently has no specs and/or CI enabled on it, but interestingly several other projects in the organization that essentially have nothing in them show as "enabled", so I'm guessing it should at least show that?

**Comment by gr2m** [comment]
thank you! We have currently no way of knowing that a repository was moved to a different account or organisation or if it was renamed (There are no Github event hooks for it). This is why this case is so complicated for us. 

I was able to reset `AtomLinter/linter-gfortran` (it can take up to 30min for Greenkeeper to create a branch. Does that repo have CI enabled?). I could not reset the other repositories, I’m still investigating

**Comment by Arcanemagus** [comment]
@gr2m All of the repos except the last one (`linter-spell-word-list`) should have CI configured of some sort. Thanks for taking a look at this, I only filed an issue as it's a bug and didn't seem to be listed here (at least when I initially filed #395).

**Comment by Arcanemagus** [comment]
As a note, `linter-gfortran` is still showing as disabled (with no issue created explaining what potentially is blocking Greenkeeper from enabling on it).

**Comment by Arcanemagus** [comment]
Closing based on https://github.com/greenkeeperio/greenkeeper/issues/816#issuecomment-399048640.
