### ISSUE TITLE
tries to update lodash to latest stable.

### ISSUE THREAD

**Issue by jdalton** [greenkeeperio/greenkeeper#51]
I noticed when I enabled greenkeeper for [lodash-cli](https://github.com/lodash/lodash-cli/pull/46/files) it tries to update the `lodash` dep from v4.0.0 to v3.10.1. The v4 dep isn't published but I'm using it in development. It would be nice if it notices it higher than published to just let it be.

**Comment by boennemann** [comment]
Thanks @jdalton,

we fixed this. From now on we won't send PRs if the new version is lower than the existing one.

Best,
Stephan

**Comment by jdalton** [comment]
Rock! Thanks!
