### ISSUE TITLE
Account is not working in Firefox

### ISSUE THREAD

**Issue by Thomblin** [greenkeeperio/greenkeeper#512]
I am not able to see account details for my profile or organisations in Firefox 55.0.2 (64-bit). It works perfectly fine with chrome. After selecting a profile or organisation I can the the title and nothing else.

Firebug says:

TypeError: I is undefined
https://account.greenkeeper.io/public/js/main.js
Line 20

**Comment by gr2m** [comment]
Thanks for reporting the issue Sebastian, we’ll have a look into it

**Comment by gr2m** [comment]
I just tried myself and it works without a problem for me in 55.0.3, could you please try to update to it and see if it works? If it does not, can you try private mode? It might be an exteinsion you have installed?

**Comment by Thomblin** [comment]
I see. Stripe was blocked by Ghostery. Thank you for the quick help

**Comment by gr2m** [comment]
anytime 👍 Have a nice weekend and thanks for letting us know that it’s fine now
