### ISSUE TITLE
Feature request: periodically rebase off of master to prevent merge conflicts

### ISSUE THREAD

**Issue by jedwards1211** [greenkeeperio/greenkeeper#515]
Sometimes I add or remove a dependency to or from a greenkeeper project and it causes merge conflicts `package.json` in the greenkeeper PRs (since I'm always behind on merging them).  If greenkeeper would periodically rebase from master, it would solve this problem.

**Comment by travi** [comment]
if your project has enough automated test coverage to be confident enough to merge the PRs automatically, you might consider [greenkeeper-keeper](https://github.com/greenkeeper-keeper) to merge the PRs before the conflicts get introduced. I'm the maintainer of that project and its one of the major benefits that I've found from leveraging full automation.

**Comment by jedwards1211** [comment]
@travi cool, I'll check it out, thanks!

**Comment by jedwards1211** [comment]
@travi that would end up merging major updates that pass the build though, right?

**Comment by travi** [comment]
thats part of what i mean by if your project has enough automated test coverage to be confident. the hope is that if a major version introduces a change that is actually breaking in your context, that it would cause one of your tests to fail. if your build fails, `greenkeeper-keeper` does not merge the PR. 

like `greenkeeper`, `greenkeeper-keeper` does not check out your project and therefore does not have the ability to inspect what the actual change contained w/in the PR is. it relies on the status checks, as reported back to github. if all checks pass, the PR gets merged regardless of the change. if a check fails, the PR does not get merged.

**Comment by gr2m** [comment]
> commit that back to the PR branch

I think that Greenkeeper is supposed to rebase its open PRs based on latest master. but I’ll have to double check with the team

**Comment by jedwards1211** [comment]
@gr2m well, even if it did, there could be conflicts when it tries to rebase.  Git's diff isn't exactly ideal for `package.json`.  But even if there's a rebase conflict, greenkeeper could just get the latest `package.json` from master, apply the new dep version, and commit it to the PR branch.

**Comment by jedwards1211** [comment]
@travi is saying greenkeeper doesn't check your project out though, which would mean it's not able to do a rebase or commit a change to the PR branch and do a `git push -f` to blow away useless commits from the PR.

**Comment by travi** [comment]
@jedwards1211 i am not a `greenkeeper` maintainer, so my statement is only around what i've come to understand from using it over time (and trying to ensure `greenkeeper-keeper` compliments it well). that understanding could certainly have some holes, or be out of date.

@gr2m you probably have better insight than me, but to my knowledge, `greenkeeper` does not update PRs after opening them. if this did happen, it would probably greatly reduce the number of conflicts that result from monorepo publishes, which normally result in one mergeable change and conflicts with that one and the remaining PRs. 

if rebasing is not an option, maybe closing the existing branch and creating a new branch with the same change, but from the current head of master could accomplish the same goal, but w/o the need to rebase?

**Comment by jedwards1211** [comment]
@travi yeah, creating a new branch with the same change from current master would work.

**Comment by jedwards1211** [comment]
Actually I think I'm confused, plain old `git rebase` probably would work.

**Comment by gr2m** [comment]
> @gr2m you probably have better insight than me, but to my knowledge, greenkeeper does not update PRs after opening them. if this did happen, it would probably greatly reduce the number of conflicts that result from monorepo publishes, which normally result in one mergeable change and conflicts with that one and the remaining PRs.

So the current Greenkeeper is not rebasing. I agree that it shouldn’t rebase in the first place, but force-update existing pull requests instead.

**Comment by ad1992** [comment]
Is there any plan on pushing this feature?

**Comment by travi** [comment]
an update was mentioned a few days ago in https://github.com/greenkeeperio/greenkeeper/issues/777

**Comment by janl** [comment]
closing this in favour of #777
