### ISSUE TITLE
Ignore 'pre-releases'

### ISSUE THREAD

**Issue by Realtin** [greenkeeperio/greenkeeper#518]
Greenkeeper ignores all distribution tags other then `latest` but apparently it still suggests updates for pre-released version. example: bankai 9.0.0-1

Maybe those are released as 'latest'. Greenkeeper should probably check more thoroughly.

**Comment by nikolas** [comment]
Similarly, is there a way to prevent greenkeeper from updating a given package? For example, I need to freeze jsdom at 9.x, because jest doesn't support newer versions of it yet.

**Comment by Realtin** [comment]
@nikolas as we just merged the new 'docs' section for the website I refere you to theses topics:
[Pinning a dependency](https://greenkeeper.io/docs.html#pinning)
[Ignoring certain dependency’s updates](https://greenkeeper.io/docs.html#ignoring-dependencies)

**Comment by Realtin** [comment]
@travi I think that would be a separate ticket.

**Comment by travi** [comment]
sounds good. your issue sparked the thought, so i figured it would be worth confirming if you considered it a reasonable request before opening a separate issue. i'll get one added. thanks!

**Comment by janl** [comment]
we fixed this recently
