### ISSUE TITLE
Can't enable repo if case mismatches

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#52]
We need to normalize the user and repo before trying to enable it. Case mismatches currently cause an error when trying to enable a repo.

cc @AutoSponge

**Comment by Flet** [comment]
Came here to report this as well. My username on github is Flet, but I'm able to treat it as lowercase flet  just about everywhere without issue.

Greenkeeper throws an error when I `greenkeeper enable`:
```
info enable The GitHub slug is: flet/revisit-mutagen
ERR! enable Couldn’t enable a project with this slug.
```

**Workaround**: If I fix the case on in my `origin` url on git, things work just fine.
```
git remote set-url origin git@github.com:Flet/revisit-mutagen
greenkeeper enable
info enable The GitHub slug is: Flet/revisit-mutagen
Flet/revisit-mutagen enabled
```

Maybe this will help others who run into this issue. Happy to test any patch that comes along :smile: 

Thanks for putting together this great tool! :+1:

**Comment by AVGP** [comment]
Ran into this, too. Would love to make a pull request with a fix, but this is something that I think should be handled on the API side.

@boennemann If you have anything I could do, lemme know!

**Comment by boennemann** [comment]
This is now fixed on our site and will go live with the next deploy.

Thanks for your reports and patience.


Best,
Stephan
