### ISSUE TITLE
Don't use `/` in branch names

### ISSUE THREAD

**Issue by slaweet** [greenkeeperio/greenkeeper#526]
Greenkeeper is a cool project, but I don't like that it creates branches names like `greenkeeper/electron-builder-19.32.2`. Please use some other character instead of `/`. For example, `_` would be nice, that is `greenkeeper_electron-builder-19.32.2`.

### Why? 
`/` is used path separation and branch names are great for in paths, either in URLs or in the file system. Then we have to escape `/` in some way and it just complicates everything.

**Comment by gr2m** [comment]
It’s a nice way to clearly separate / group branches. It works great for us so far but let’s keep the issue open to see if others run into trouble with it.

The `/` does not need to be escaped in the GitHub URls at least. Could you give us a specific example of where it is causing problems?

**Comment by travi** [comment]
i'm a cli user, but other members of my team that use gui applications for git actually really like the use of the `/` because the tools group the branches into folders. i think its a fairly common practice, so that tools are able to do helpful things like that.

**Comment by slaweet** [comment]
@gr2m an example is when we want to`rsync` built files in Jenkins to a folder named by `$BRANCH_NAME`
```
rsync -axl --delete  "$WORKSPACE/app/dist/" "jenkins@master-01:/var/www/test/project-name/$BRANCH_NAME/"
```
It fails with the following:
```
rsync: mkdir "/var/www/test/project-name/greenkeeper/i18next-pin-9.0.0" failed: No such file or directory (2)
```
Off course, we can escape the slash or run something like `mkdir -p ...` to ensure the path exists. So far I see others like slash as a feature, so we'll have to fix our use case. It's not much work, I just thought that more people might have similar issues and then it would be worth to fix it at the source ;-)

**Comment by janl** [comment]
This would be a larger change for us (taking greenkeeper-lockfile into account), so we are probably not going to do this if simple enough workarounds are available. We might revisit this in the future.
