### ISSUE TITLE
Greenkeeper did not create branch for patch update

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#529]
I’ve created this app yesterday and enabled it successfully with Greenkeeper: https://github.com/gr2m/funky-app. It currently depends on `funky-sloth-42@^2.0.0`. I released `funky-sloth-42@2.0.1` to test the real-time monitoring feature, but the branch was never created it seems, because it would have broken the tests. I also don’t see builds for it on Travis.

**Comment by pvdlg** [comment]
Isn't it due to #506 ?

**Comment by gr2m** [comment]
no, it doesn’t even create the branch. And greenkeeper-lockfile is setup correctly, it worked before

**Comment by pvdlg** [comment]
I think this is what #506 does. It prevent Greenkeeper to create the branch when you have an in range update and a package-lock.json.
And this is your situation. You have a package-lock.json and you did and you had an in range update on funky-sloth-4 (2.0.0 => 2.0.1 is in range of funky-sloth-4@^2.0.0).

To test you can remove package-locks.json from your repo, release funky-sloth-4@2.0.2 and it should create the branch and trigger the tests.

**Comment by gr2m** [comment]
Cheers I'll check
