### ISSUE TITLE
State mismatch after merging an amended Greenkeeper-created branch

### ISSUE THREAD

**Issue by jarrodldavis** [greenkeeperio/greenkeeper#530]
I `git commit --amend` the commits created by Greenkeeper to have them signed with a GPG signature, but that appears to confuse Greenkeeper because it doesn't automatically delete the branch once merged, and subsequent updates to the same dependency result in a comment linking to a branch it creates (and then deletes) off of the pre-merged state of the default branch. [Here is an example comment](https://github.com/jarrodldavis/probot-gpg/pull/48#issuecomment-334655981) and the [commit that was created](https://github.com/jarrodldavis/probot-gpg/commit/b1388af7b6e2fdab969665f4118fbb23bf39e2b2).

<img width="673" alt="screen shot 2017-10-06 at 9 26 02 pm" src="https://user-images.githubusercontent.com/235875/31303980-03f67f2e-aadd-11e7-826a-0c3c79efe1cb.png">

**Comment by janl** [comment]
I see how this happens, but this isn’t a priority for us at the moment, I’m sorry!
