### ISSUE TITLE
GK creates multiple "Add Greenkeeper badge" PRs

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#537]
- https://github.com/gr2m/before-after-hook/pull/13 (I edited it before merging)
- https://github.com/gr2m/before-after-hook/pull/14 (showed up later)

**Comment by gr2m** [comment]
not sure if that’s related. It first created the issue that CI needs to setup, and then sends a PR to update all dependencies

- https://github.com/gr2m/selsa/issues/50
- https://github.com/gr2m/selsa/pull/51

not that this repo was activated before

**Comment by janl** [comment]
should be fixed
