### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by travi** [greenkeeperio/greenkeeper#544]
thanks a ton for everything you do to keep my packages up to date! with the recent security patches going out for node, it got me thinking about something i've considered submitting a feature request for in the past. 

would it be reasonable for you to send me PRs for the version of node, in addition to the PRs you send me for package versions? not everyone tracks this the same in their projects, but for those that do track it, there should be a small handful of potential places to update.

i use `nvm` to define the version for local development and for travis-ci, which respects an `.nvmrc` automatically. i also define `engines` in the `package.json` for applications that i host on heroku or google app engine.

since travis would run my tests against the `.nvmrc`, updated by you, i would be comfortable not making this change manually. this would also help me not get as far out of date in a similar way to how you help me with packages.

**Comment by janl** [comment]
closing in favour of #710
