### ISSUE TITLE
Some kind of notification for successful tests

### ISSUE THREAD

**Issue by curiousdannii** [greenkeeperio/greenkeeper#545]
GitHub recently changed the dashboard so that the Greenkeeper branch addition and deletion messages do not get displayed. They also don't appear in notifications.

I found it useful to see when there were updates being tested. It now appears to no longer be possible to see that in Github itself, so I will have to check Travis more frequently.

But I'm posting this here in case there's some other kind of notification you can produce using the Github API. Who knows, it could even be cleaner than the old addition+deletion dual messages.

**Comment by janl** [comment]
Would it be enough to show that info next time you get an Issue/PR?

**Comment by janl** [comment]
Closing until reply.

**Comment by curiousdannii** [comment]
@janl which info? Are you suggesting that when a PR is made it would have a section saying all the versions that passed? I hadn't thought of that, but it could be good. I'd expect it to be shown collapsed by default.

**Comment by travi** [comment]
i tend to looks at build history on the ci service (travis in my case) when i'm looking for this activity. does that approach not satisfy what you are looking for in these situations?
