### ISSUE TITLE
greenkeeper not updating react package

### ISSUE THREAD

**Issue by nikolas** [greenkeeperio/greenkeeper#546]
Hi,
I have a react project set up with greenkeeper here:
https://github.com/ccnmtl/juxtapose

The version of `react` is set to `~15.6.0`:

https://github.com/ccnmtl/juxtapose/blob/master/package.json

Version 16.0.0 has been out for a while: https://www.npmjs.com/package/react And greenkeeper hasn't updated it automatically, as I would expect it to.

**Comment by janl** [comment]
Heya, sorry for the trouble. I’ve reset your repo on our end. You should get a new initial PR and normal package updates will resume. Please let us know if anything is going not the way you expect them.
