### ISSUE TITLE
No Github activity

### ISSUE THREAD

**Issue by pascalduez** [greenkeeperio/greenkeeper#55]
Greetings,

most likely I'm missing something obvious, but I enabled Greenkeeper on one of my repos and although I get activity reports from Travis (commits), I can't see anything happening on Github (no PR, commit, ...) 

https://travis-ci.org/pascalduez/postcss-map/builds 
https://github.com/pascalduez/postcss-map/pulls

**Comment by AdriVanHoudt** [comment]
afaik greenkeeper will only do a pr if a dep updates and a) the build fails b) the version is bigger than allowed in package.json
so if you have 1.0.x and the dep updates to 1.0.2 and it doesn't break your tests, greenkeeper will not do a pr

**Comment by boennemann** [comment]
Hey @pascalduez,

@AdriVanHoudt explained it already. As long as versions that are covered by your existing version range don't fail your tests there is no need to bother you with a PR, as everything still works as expected. Should any of these builds fail you'll see GitHub activity (i.e. a PR).

If there is a new version of your dependency outside of the current version you'll get the PR either way.

Thanks for asking, and thanks for the explanation @AdriVanHoudt,

Best,
Stephan

**Comment by AdriVanHoudt** [comment]
Np, glad I got it right

**Comment by pascalduez** [comment]
Thanks guys for the explanations, indeed, makes much sense.

**Comment by AdriVanHoudt** [comment]
It used to do that?

**Comment by AdriVanHoudt** [comment]
As in it did, it doesn't anymore?

**Comment by phillipj** [comment]
It probably did before they added support for version ranges October 7th https://github.com/greenkeeperio/greenkeeper/issues/27#issuecomment-146212266.
