### ISSUE TITLE
Not getting PRs from greenkeeper for `electron-apps` updates

### ISSUE THREAD

**Issue by zeke** [greenkeeperio/greenkeeper#554]
Hi Greenkeeper humans!

Greenkeeper is set up on the Electron website repo and we've been getting PRs: https://github.com/electron/electronjs.org/pulls?q=is%3Apr+is%3Aclosed+label%3Agreenkeeper

However, the `electron-apps` module keeps getting updates but Greenkeeper does not seem to be picking them up. Any idea why this might be happening?

**Comment by gr2m** [comment]
hey @zeke the repository doesn’t seem to be activated on our side. If it is on yours, can you please try to remove it and add it back again?

**Comment by zeke** [comment]
`electron/electron.atom.io` was renamed to `electron/electronjs.org` -- might that have something to do with it?

**Comment by zeke** [comment]
Thanks!

**Comment by zeke** [comment]
After @gr2m reset the repo on Greenkeeper's side, we got a new starter PR from Greenkeeper: https://github.com/electron/electronjs.org/pull/882

That worked but we're still not getting any PRs when the `electron-apps` module is updated.

**Comment by gr2m** [comment]
you won’t get PRs unless there is a `electron-apps` release which is outside of the defined range:

https://github.com/electron/electronjs.org/blob/59495005d5f3e2ccb771a9a75cf15ee02b5605a9/package.json#L35

I think for your usecase it makes sense to pin the `electron-apps` version, so you get a pull request for every release, no matter if breaking, feature or fix release?

**Comment by zeke** [comment]
> outside of the defined range

Ah that's a subtlety of Greenkeeper that I was unaware of. Thanks for the clarification.

**Comment by zeke** [comment]
Locking the version did the trick. Thanks, @gr2m 🙏 

https://github.com/electron/electronjs.org/pull/904
