### ISSUE TITLE
Handle archived repositories

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#556]
Just a heads-up issue: repositories can now be archived which makes them read-only, e.g. https://github.com/gr2m/selsa

I’m not sure what the error response it, but it’s a case we should handle. There are [archived / unarchived actions for the repository event](https://developer.github.com/v3/activity/events/types/#repositoryevent) that Greenkeeper can subscribe to disable/re-enable repositories

**Comment by janl** [comment]
Done!
