### ISSUE TITLE
Greenkeeper runs PR's twice

### ISSUE THREAD

**Issue by daleharvey** [greenkeeperio/greenkeeper#561]
Hey, cheers for greenkeeper, its the 3rd largest contributor on PouchDB :)

One issue we have been having I feel like it started around 6 months ago or something, is that most of our greenkeeper PR's started running 2 test suite runs `continuous-integration/travis-ci/push` and `continuous-integration/travis-ci/pr`

Our test suite runs into 4 hours and uses a bunch of other resources like saucelabs, so running them when we dont need to is pretty wasteful and results in our travis being backlogged often

Not a huge git or github+travis expert, I remember trying to tweak the branches configuration in travis to fix this but not having much luck, its @ https://github.com/pouchdb/pouchdb/blob/master/.travis.yml#L138

Cheers

**Comment by gr2m** [comment]
This is very odd, I use the same setting to avoid double travis builds. But I guess it makes sense, we allow builds for `greenkeeper/*` branches as well as PR builds, so for pull requests coming from Greenkeeper they both apply. But I can’t recall if I saw the double builds with that setting on other projects, I’ll keep an eye open for it

**Comment by janl** [comment]
@daleharvey is this still happening?
