### ISSUE TITLE
Feedback re: Lockfile

### ISSUE THREAD

**Issue by holvonixAdvay** [greenkeeperio/greenkeeper#564]
We've been testing out dependabot and greenkeeper simultaneously on some simple open-source repos. Greenkeeper's realtime nature and its logic for when to post PRs is great, but the separate lockfile process means we have some [gnarly logic re: --frozen-lockfile in our .travis.yml](https://github.com/holvonix-open/json2array/blob/ec230185a48fc37cb35d9363542c1b3ba22949f2/.travis.yml).  Will lockfile updates be a first-class citizen in greenkeeper?

Keep up the great work!
(Corresponding feedback to dependabot: https://github.com/dependabot/feedback/issues/61 )

**Comment by espy** [comment]
Thanks for the praise, and yes, we want to support lockfiles natively without the need for `gk-lockfile`. It’s become technically possible for us to to `package-lock.json` files natively, but we’re still figuring out whether the other file types can also be done in this manner (purely in code, without running on a CI service). But it’s high on our list ⬆️  🌴

**Comment by janl** [comment]
Update: https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0 :)
