### ISSUE TITLE
ampproject/amphtml: greenkeeper/verify check not showing up, lockfile not being updated

### ISSUE THREAD

**Issue by rsimha** [greenkeeperio/greenkeeper#574]
We recently enabled `greenkeeper` and `greenkeeper-lockfile` on our repository at https://github.com/ampproject/amphtml

Today, I saw a new PR from `greenkeeper` pop in due to an updated dependency, at https://github.com/ampproject/amphtml/pull/12766.

However, the PR is missing two things:
- The `greenkeeper/verify` check never appeared. Is this a known issue (perhaps related to https://github.com/greenkeeperio/greenkeeper-lockfile/issues/92)? Or could I be missing a step?
- The second commit from `greenkeeper-lockfile` never appeared. Due to https://github.com/greenkeeperio/greenkeeper-lockfile/issues/98#issuecomment-352087908, I tried adding a workaround in https://github.com/ampproject/amphtml/pull/12789 and updating the branch created by `greenkeeper`, but I still see the message `Only running on first push of a new branch` even though there is only one commit on the branch.

Here is our `.travis.yml`: https://github.com/ampproject/amphtml/blob/master/.travis.yml#L18

Any idea what I'm missing? Thanks!

**Comment by rsimha-amp** [comment]
Looks like item 2 is because of a permission error: https://travis-ci.org/ampproject/amphtml/jobs/327380341#L808

Any idea if item 1 is due to item 2 not working?

**Comment by rsimha-amp** [comment]
Unfortunately, we're still having trouble updating our lockfiles because the update code seems to think it has pushed multiple commits to the greenkeeper branch, even though there's only one commit on the branch. I've filed https://github.com/greenkeeperio/greenkeeper-lockfile/issues/100 to track this. Hope someone is able to help figure out what's missing.

**Comment by janl** [comment]
greenkeeper-lockfile 2.0 should fix this, it is currently in `next` state, but testable.
