### ISSUE TITLE
greenkeeperio-bot account needs to sign CLA in order to commit to ampproject/amphtml

### ISSUE THREAD

**Issue by rsimha** [greenkeeperio/greenkeeper#578]
Hi, we're the AMP project team, and we've been using `greenkeeper` to maintain our dependencies.

Since we use `yarn`, we recently deployed `greenkeeper-lockfile` to update `yarn.lock`. However, `greenkeeperio-bot`, the bot account used by `greenkeeper-lockfile-upload` appears to be different from the account that pushes the initial commit  to update `package.json`.

This is failing our Google CLA check at https://cla.developers.google.com/about. See https://github.com/ampproject/amphtml/pull/12819#issuecomment-357304685 for example.

Would it be possible for someone to make sure that the `greenkeeperio-bot` account signs our CLA so we can continue to use `greenkeeper`? Thanks!

**Comment by Arcanemagus** [comment]
See https://github.com/greenkeeperio/greenkeeper/issues/329, which links to https://platform.github.community/t/set-the-email-address-of-the-bot/806 which is unfortunately only "planned".

**Comment by rsimha-amp** [comment]
Thanks @janl, one step closer. We have a new error now: https://github.com/ampproject/amphtml/pull/12834#issuecomment-357704712

> The bad news is that it appears that one or more commits were authored by someone other than the pull request submitter. We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that here in the pull request.
