### ISSUE TITLE
typo in stale initial PR reminder

### ISSUE THREAD

**Issue by makebbekus** [greenkeeperio/greenkeeper#585]
[Currently reads](https://github.com/greenkeeperio/greenkeeper/blob/e3b2ec236139c0202df840f33187d75deca9222e/content/stale-initial-pr-reminder.js#L8):

> If don't want to enable Greenkeeper here, just close or ignore this PR, we won't nag you again. ✌️

Should read:

> If you don't want to enable Greenkeeper here, just close or ignore this PR, we won't nag you again. ✌️

**Comment by espy** [comment]
Whoops :) Thanks for that!
