### ISSUE TITLE
support rc file config

### ISSUE THREAD

**Issue by travi** [greenkeeperio/greenkeeper#586]
i know opinions are all over the board for where to store config, but i'm curious if you'd be open to supporting more locations than just within the `package.json` file. 

my concern is that package files can get very noisy without a bunch of config in them, so keeping config there too makes it even harder to maintain. i've already conceded that the root of most of my projects is a dumping ground for config files, so i'm fine with continuing to add more there. they end up being easier for me to ignore there too.

could something like `.greenkeeperrc` work? i recently spotted that `semantic-release` is using [cosmicconfig](https://github.com/davidtheclark/cosmiconfig) to simplify finding config in various locations. would that be a good fit in this case?

**Comment by travi** [comment]
looks like this is planned from the details of #594. thanks!

**Comment by janl** [comment]
Yup, we now support `/.greenkeeper` as a config file. We made it a single file because being able to monitor a well-known path is about two orders of magnitude less complicated than being able to configure the name of the config file 😎

**Comment by travi** [comment]
> Yup, we now support /.greenkeeper as a config file.

You mean `greenkeeper.json`, correct? Either way, thank you. Much better than only being able to use `package.json`.

I understand wanting to keep complexity down, so this isn't me trying to convince you to add additional complexity, but just want to mention that my reason for preferring it being a dotfile is to avoid tab completion collisions with non-config files.
