### ISSUE TITLE
Feature Request: Re-trigger Jenkins builds on fail

### ISSUE THREAD

**Issue by julmot** [greenkeeperio/greenkeeper#588]
From my personal experience with Greenkeeper, the issues it opens are most of the time caused by some interruption in the build services, e.g. SauceLab. In this case, I often trigger a rebuild and it works again. It would be great if Greenkeeper could also do that before opening an issue.

**Comment by janl** [comment]
Since it is hard to decide whether a build failure is caused by a legit error in the tests or something else, we’d rather not auto-restart CI services.
