### ISSUE TITLE
PRs with "untested" status, when there are tests

### ISSUE THREAD

**Issue by boneskull** [greenkeeperio/greenkeeper#59]
see [this PR](https://github.com/boneskull/ketch/pull/1) for an example

**Comment by boennemann** [comment]
Hey @boneskull,

there is no definite way of telling whether a project has a CI setup. Our current approach is to check the status of the latest commit on the default branch, and see if it has any results attached to it.

If not we assume there is no CI configured. It seems like things get mixed up with your repository, which could have a lot of reasons.

We're investigating this.

Best,
Stephan

**Comment by boennemann** [comment]
One possible cause for this is having the CI configured so that it doesn't run tests for every branch. See: https://github.com/greenkeeperio/greenkeeper/issues/162#issuecomment-206748524

I saw that this is no longer a problem for the specific repo, do you recall what could have changed this behavior?

Best,
Stephan

**Comment by boneskull** [comment]
@boennemann I don't recall changing anything... hmm.

**Comment by fvdm** [comment]
I have this problem too on two repos where in the first GK reports untested all the time and the second started doing that since today.

* https://github.com/fvdm/nodejs-cloudsight/pull/7
* https://github.com/fvdm/nodejs-dnsimple/pull/15

**Comment by danez** [comment]
We have the same Problem, in our case it is because some commits are marked with `[skip ci]` because they didn't touch any sourcecode. Then the logic described above fails.

https://github.com/babel/babel-eslint/pull/347

**Comment by deepsweet** [comment]
+1 here, `[skip ci]` on the last commit leads to "falsy" PRs with "I was looking at the latest commit of your default branch, but GitHub said there is no status attached to it" message.

**Comment by blakeembrey** [comment]
Is there a known obvious or straightforward workaround for this, short of pushing an empty commit to master? It's a big issue with @types that I'm seeing as I'm just starting to enable it in a few locations alongside Travis, but having every new release trigger PRs until a push on `master` is difficult here as none of these projects are actively worked on (being type definition mirrors to real source code repos).

**Comment by boennemann** [comment]
Y'all are right, this isn't the best way to handle this.
We assumed that just letting PRs time out would lead to a lot of false "untested" PRs as well, but just checking master doesn't work any better.

We're trying to come up with a solution and I'll let you know once that's out. We're happy for any ideas or feedback here.

Thanks,
Stephan

**Comment by blakeembrey** [comment]
@boennemann Wouldn't the timeout approach be better, or are there other concerns? I haven't really looked into it, but GitHub has a pending state and at least CircleCI and TravisCI both use it. You could wait for a minute before checking that perhaps? E.g. https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref.

**Comment by jamiemjennings** [comment]
+1 for the `[ci skip]` issue being a major nuisance! Could greenkeeper ignore commits with `[ci skip]` and instead find the latest commit without it (which would have automated test results)?

**Comment by deepsweet** [comment]
I have something like 30 repos affected with this issue. and 30 e-mails on every patch update of every dependency. and 30 "falthy" branches with PRs. and also 7 or 8 github hooks for few CI services and etc... nice feelings, robots have been working so hard :) just because all my latests commits were with `[skip ci]` – I had to update a bunch of readme files.

**Comment by boennemann** [comment]
This issue is related to Greenkeeper 1, which we're shutting down at the end of the month. I'll go ahead and close this issue now.
