### ISSUE TITLE
Monorepo Support Proposal/Discussion 🤔 💡 💬 

### ISSUE THREAD

**Issue by Realtin** [greenkeeperio/greenkeeper#594]
# Greenkeeper Monorepo Support
This issue outlines our proposed approach for making Greenkeeper work with multiple package.json files. Something otherwise known as a “Monorepo”. Monorepos come in different variants that we’ll explain further below. Today, Greenkeeper only supports updating a single `package.json` that’s at the root of a repository.

As a general mission statement: *We want Greenkeeper to work with repositories that have one or more `package.json` files in subdirectories*.

For example, a project could combine a frontend and a backend component and only the frontend has a `package.json` file:
```
/project/
/project/backend/
/project/frontend/package.json
```
In the above case the backend might be written in Ruby and as such has no `package.json` file.

Alternatively: 
```
/project/
/project/backend/package.json
/project/frontend/package.json
```
In the above case, the backend is written in Node.js and also has a `package.json` file, but they are independent, e.g. updates to dependencies in one package.json have no effect on the other.

See the “Scenarios” section further down for other examples.
## Limitations
There are two aspects to handling monorepos:
1. Handling dependency updates where the target repository is a monorepo.
2.  Handling dependency updates where the source is a monorepo, where different, dependent packages are released at once, and targets need to update them in one go. (Babel and PouchDB are examples.

This issue only covers the first case and we’ll cover the second case separately.

## Features
- Greenkeeper can find all `package.json` files in a repository.
- The combined package information from all `package.json` files is stored in a repository document in the Greenkeeper database.
- By default there will be one pull request per dependency (affecting multiple `package.json` files).
- `package.json` files can be grouped by the user to receive a pull request per dependency per group.
### Greenkeeper configuration file

There will be a `greenkeeper.json` file that will allow the user to define named groups of `package.json` files that should be updated together. It will also allow ignoring dependency updates of certain dependencies per group. This file is the single source of truth for how Greenkeeper handles the repo, it will make no assumptions based on the other files in the repo. If this file is not present in the project root, Greenkeeper behaves as before, handling a single  `package.json` in the project root, if present. No additional config is needed to run Greenkeeper in “single `package.json` mode”.

⚠️ *Note: for now, we will refer to this config file as `greenkeeper.json`, but we might change that name.*

This will look something like this:

```js
{
  "groups": {
    "frontend": {
      "packages": [
        "package.json",
        "apps/frontend/react-thing/package.json",
        "apps/frontend/our-own-webpack-fork/package.json"
      ]
    },
    "backend": {
      "ignore": [
        "lodash"
      ],
      "packages": [
        "apps/backend/hapiserver/package.json"
      ]
    }
  }
}
```
On install, if Greenkeeper finds more than one `package.json` file, it will generate a default `greenkeeper.json` with the paths to all of them. Users can then edit this file to their liking, grouping `package.json` files, adding ignored dependencies etc.

```js
{
  "groups": {
    "default": {
      "packages": [
        "package.json",
        "apps/frontend/react-thing/package.json",
        "apps/frontend/our-own-webpack-fork/package.json",
        "apps/backend/hapiserver/package.json"
      ]
    }
  }
}
```

## Current Behaviour
Currently Greenkeeper only looks for **one** `package.json` file in the **root directory**.

From this `package.json`  Greenkeeper extracts the package information and stores those in a repository document in our database. The information looks similar to this:

```js
"packages": {
   "package.json": {
    "name": "Package Name",
    "dependencies": {
     "async": "^2.5.0",
     "chalk": "^2.1.0",
     "fs-walk": "0.0.1",
     "request": "^2.83.0",
    },
    "devDependencies": {
     "hapi": "^16.6.2",
     "mock-fs": "^4.4.1",
     "simple-mock": "^0.8.0",
     "standard": "^10.0.3",
     "tap": "^11.0.0"
    },
    "author": "Me"
   }
  }
```
## New Repository Scenarios 
1. Frontend and Backend are located in subfolders within the same repo, e.g. a typical Rails backend with Ember.js frontend setup
2. Lerna
```json
my-lerna-repo/
  package.json
  packages/
    package-1/
      package.json
    package-2/
      package.json
```
3. [‚alle‘-style monorepo configuration](https://github.com/boennemann/alle#readme) e.g. PouchDB (Greenkeeper already works with this kind of Monorepo configuration)

### Installation
1. Greenkeeper searches the file tree for package.json files. 
2.  It creates a PR with all the updated dependencies, the greenkeeper README Badge and a new `greenkeeper.json` in the root directory containing the paths of all found `package.json` files, if it doesn’t already exist. The PR will contain information about how to customize this file.
3. The user may commit their desired customisation of the `greenkeeper.json` and merge the PR
~~4. After the merge Greenkeeper create its initial branch and updates all dependencies in all `package.json` files.~~

### What happens to existing repositories?
Existing repositories will continue to work as before. You don’t need to add the `greenkeeper.json` if you only have a single `package.json` file in the project root.
If the `greenkeeper.json` is added to an existing repository, Greenkeeper will create a new initial pull request per group so all `package.json` files are up-to-date to have a common starting point.
### What happens if a package.json is added/removed/renamed/moved in the repo?
Event|Description
------------ | -------------
**Added** | nothing, if it is not also added the the `greenkeeper.json`. The `greenkeeper.json` is the source of truth, we only act on what is configured there
**Removed** | it will be removed from our copy of `greenkeeper.json`
**Renamed** | doesn’t happen: they’re always called `package.json`. If the folder is renamed, it’s a move:
**Moved** | Since this probably reaches us in the form of a delete plus an add, we can’t know what was moved, and should treat this as exactly what it is: a delete and an add (https://developer.github.com/v3/activity/events/types/#pushevent)
### What happens if a package.json is added/removed/renamed/moved in the greenkeeper.json or a group changes in any way?
Event|Description
------------ | -------------
**Added** | we run a sub-initial PR for the group it was added to
**Removed** | it just works™ because we treat the `greenkeeper.json` as the single source of truth. Greenkeeper will also delete all existing greenkeeper-branches of that group (this will also close open PRs)
**Renamed/Path of a package.json edited** | we can’t detect moves, only deletes and adds, so we treat this as “added”.
**Moved to another group** | greenkeeper triggers a sub-initial PR for the group it was added to
### What happens if a new greenkeeper.json appears, or a new group appears in it?
Greenkeeper is already enabled, so we just need to get each group up to current, so we need a sub-initial PR for each group that has at least one out-of-date dep. Otherwise somehow inform user that we’ve noticed and will handle their monorepo from now on. 
### What happens if a greenkeeper.json is removed, moved from root or renamed?
Will now only handle top-level `package.json`, if it exists
Won’t notify user
### When a group disappears from the `greenkeeper.json`
We close all open PRs that refer to the now non-existent group, unless that group only contained a root `package.json` which still exists, in that case the open PRs still have value
### How does a dependency update work?
* All grouped `package.json` files will be changed in the same commit.
* The Greenkeeper dependency branch name will be changed from `greenkeeper/cosmiconfig-4.0.0` to `greenkeeper/[group]/cosmiconfig-4.0.0`, where [group] might be the group name `backend` from the example configuration above.
* Depending on the status of the CI build that is running on the Greenkeeper branch, the usual Greenkeeper processes happen (issues, PRs, or silently deleting branches that are no longer needed). 
#### What is the new Initial Subgroup PR?
Every time a new group appears, or a new `package.json` file appears in a group, we need to get all the dependencies of all of the files in that group up to date. This is done via a new type of initial PR that only updates  `package.json`  files in a single group. 
#### What happens if the ranges for a dependency in a group have become inconsistent?
This shouldn’t happen (this is why we have the initial PRs), but since users can freely edit their  `package.json` files, it’s still a possibility. If, for example, one or more updates are out of range, eg. two are “^1.1.0” and one is “1.0.5”, we send an “out of range” PR to get all dependencies back up to current. 
### When things go wrong
* If Greenkeeper can’t find a `package.json` in the defined path, it will open the PR with the remaining files (if any) and add a note to the PR. If there are no findable files left, but there are files listed in the group, we **open an issue** to notify the users. This is a very likely error scenario: a folder name is changed, but paths in group in `greenkeeper.json` are not updated
* If the `greenkeeper.json` is not in a valid format, Greenkeeper will also **open an issue**.
#### If repeated errors of the same type happen: 
⚠️ TBD: Before we open an issue, if an issue with the same name exists (“Greenkeeper has encountered a problem with your `greenkeeper.json`”, maybe something more specific than that), do we update the initial comment? Definitely _not_ add a comment. This needs more thought. What if we can’t find a file 120 times? We’d like to let the user know how to fix that, but not 120 times…
## New Workflow Charts
![monorepo_diagrams 001](https://user-images.githubusercontent.com/507997/35289645-33b71e18-0068-11e8-9204-8d43c369eba9.png)
![monorepo_diagrams 002](https://user-images.githubusercontent.com/507997/35289650-369de224-0068-11e8-8ba3-59992cf3e4c6.png)
![monorepo_diagrams 003](https://user-images.githubusercontent.com/507997/35289652-3a5c5ecc-0068-11e8-91bd-74f3dff036ae.png)

## Possible Implementation
➡️  💬  [WIP branch](https://github.com/greenkeeperio/greenkeeper/compare/support_monorepos)

_edited (14.March 2018): updated example config files, renamed .greenkeeperrc to greenkeeper.json, removed the two-step initial PR process, added some words for clarification_

**Comment by espy** [comment]
This has been shipped! 🚢
