### ISSUE TITLE
Branch for non existing version on NPM

### ISSUE THREAD

**Issue by simov** [greenkeeperio/greenkeeper#60]
:wave: 

I just noticed that we received 3 consecutive failing PRs for `karma`, and the reason was because the module's version was not published on NPM yet:

```
npm ERR! notarget No compatible version found: karma@'>=0.13.14 <0.14.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.8.0","0.9.0-dart","0.8.1","0.8.2","0.8.3","0.9.0","0.8.4","0.9.1","0.8.5","0.9.2","0.9.2-dart","0.9.3","0.8.6","0.9.4","0.8.7","0.9.5","0.9.6","0.8.8","0.9.7","0.9.8","0.10.0","0.10.1","0.10.2","0.11.0","0.11.1","0.10.3","0.10.4","0.11.2","0.11.3","0.10.5","0.11.4","0.11.5","0.10.6","0.11.6","0.10.7","0.11.7","0.11.8","0.11.9","0.10.8","0.11.10","0.11.11","0.11.12","0.11.11-dev","0.10.9","0.11.12-dev","0.11.12-dev2","0.11.13","0.11.14","0.12.0","0.10.10","0.12.1","0.12.2","0.12.3","0.12.4","0.12.5","0.12.6","0.12.6-beta-43e6e28","0.12.7","0.12.8","0.12.9","0.12.10","0.12.11","0.12.12","0.12.11-beta-3029418","0.12.13","0.12.14","0.12.15","0.12.16","0.12.16-beta-905422d","0.12.17","0.12.18","0.12.19","0.12.20","0.12.21","0.12.22","0.12.23","0.12.24","0.12.24-beta-6cf7955","0.12.25","0.12.25-beta-37a7958","0.12.25-beta-ad5bc24","0.12.26","0.12.27","0.12.28","0.12.28-beta-b9be580","0.12.29","0.12.30","0.12.31","0.12.28-beta-f65c864","0.12.24-dev-test","0.12.24-dev-socketio10","0.12.24-dev-socketio10-2","0.12.32-beta.0","0.12.32","0.13.0-rc.0","0.12.33","0.13.0-rc.1","0.12.34","0.13.0-rc.2","0.12.35","0.13.0-rc.3","0.12.36","0.13.0-rc.4","0.12.37","0.13.0-rc.5","0.13.0-rc.6","0.13.0-rc.7","0.13.0-rc.8","0.13.0-rc.9","0.13.0","0.13.1","0.13.2","0.13.3","0.13.4","0.13.5","0.13.6","0.13.7","0.13.8","0.13.9","0.13.10","0.13.11","0.13.12","0.13.13"]
```

Basically we received PR for `karma@0.13.14` only because the build was failing, but as you can see at the time Travis CI tried to install it, it wasn't available on NPM yet.

I'm not showing you direct links, because I'm going to re-run the build, of course now everything passes, but it was kind of annoying because they just released `0.13.12`, `0.13.13` and `0.13.14` in very short amount of time, probably fixing bugs, and we got 3 failing PRs, even though we shouldn't receive any, until `0.14.0`.

**Comment by boennemann** [comment]
Hey @simov,

I'm sorry that this happened. We only start creating branches and PRs after npm informs us of new versions (via their https://skimdb.npmjs.com/).

It looks like this happened because of some inconsistencies or caching issues on npm's side. I hope that this won't happen again, but if it keeps reappearing we will add a waiting period, or other mechanisms to check whether newly published modules are already installable.

Best,
Stephan

**Comment by simov** [comment]
```
npm ERR! notarget No compatible version found: bluebird@'>=3.0.5 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.7.1-1","0.7.1-2","0.7.1-3","0.7.1-4","0.7.1-5","0.7.2-0","0.7.3-0","0.7.4-0","0.7.4-1","0.7.5-0","0.7.6-0","0.7.7-0","0.7.7-1","0.7.8-0","0.7.8-1","0.7.9-0","0.7.9-1","0.7.10-0","0.7.10-1","0.7.11-0","0.7.12-0","0.7.12-1","0.7.12-2","0.8.0-0","0.8.0-1","0.8.0-2","0.8.0-3","0.8.1-0","0.8.2-0","0.8.2-1","0.8.2-2","0.8.3-0","0.8.3-1","0.8.3-2","0.8.3-3","0.8.4-0","0.8.4-1","0.8.5-0","0.8.5-1","0.9.0-0","0.9.1-0","0.9.1-1","0.9.2-0","0.9.2-1","0.9.3-0","0.9.4-0","0.9.4-1","0.9.5-0","0.9.6-0","0.9.7-0","0.9.8-0","0.9.9-0","0.9.10-0","0.9.10-1","0.9.11-0","0.9.11-1","0.10.0-0","0.10.0-1","0.10.1-0","0.10.2-0","0.10.2-1","0.10.3-0","0.10.4-0","0.10.4-1","0.10.5-0","0.10.6-0","0.10.7-0","0.10.8-0","0.10.9-0","0.10.9-1","0.10.10-0","0.10.11-0","0.10.11-1","0.10.11-2","0.10.11-4","0.10.12-0","0.10.13-0","0.10.13-1","0.10.14-0","0.11.0-0","0.11.1-0","0.11.2-0","0.11.3-0","0.11.4-0","0.11.4-1","0.11.5-0","0.11.5-1","0.11.6-0","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.7","1.0.8","1.1.0","1.1.1","1.2.0","1.2.1","1.2.2","1.2.3","1.2.4","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.1.1","2.1.2","2.1.3","2.2.0","2.2.1","2.2.2","2.3.0","2.3.1","2.3.2","2.3.3","2.3.4","2.3.5","0.11.6","2.3.6","2.3.9","2.3.10","2.3.11","2.4.0","2.4.1","2.4.2","2.4.3","2.5.0","2.5.1","2.5.2","2.5.3","2.6.0","2.6.1","2.6.2","2.6.3","2.6.4","2.7.0","2.7.1","2.8.0","2.8.1","2.8.2","2.9.0","2.9.1","2.9.2","2.9.3","2.9.4","2.9.5","2.9.6","2.9.7","2.9.8","2.9.9","2.9.10","2.9.11","2.9.12","2.9.13","2.9.14","2.9.15","2.9.16","2.9.17","2.9.18","2.9.19","2.9.20","2.9.21","2.9.22","2.9.23","2.9.24","2.9.25","2.9.26","2.9.27","2.9.28","2.9.29","2.9.30","2.9.31","2.9.32","2.9.33","2.9.34","2.10.0","2.10.1","2.10.2","3.0.0","3.0.1","3.0.2","3.0.3","3.0.4"]
```

This time 3 out of 4 build targets are passing, but still a *fake* PR was created due to one of them failing.

**Comment by nkbt** [comment]
NPM uses replication between multiple servers, so as soon as the first one emits, that does not mean other servers have it. I would go for an arbitrary delay as an easy fix.

Note, when I publish my own dependency (AU), most likely it utilizes the closes NPM registry, so new PR comes quite quickly and is not faulty. When pretty much any other dependency is updated (US) - I'm getting broken build =(.

**Comment by boennemann** [comment]
Alright, we'll add an arbitrary timeout for now. I'll let you know once that's deployed. 
Thanks for the feedback.

**Comment by simov** [comment]
Take a look at this PR https://github.com/request/request/pull/1992, again some of the build targets pass, and some of them fail. I'll keep it open for a while, check out the Travis logs.

**Comment by boennemann** [comment]
Once npm's skimdb tells us about a new version we're now waiting an additional 60 seconds to allow them to populate all edge locations of their CDN, before creating branches.

We think these false alarms should no longer appear now. Please report back in this issue should you ever receive a false-positive like this again.

Thanks for your reports and patience :+1: 
Stephan

**Comment by TheAlphaNerd** [comment]
timeout ftw

**Comment by nkbt** [comment]
Thank you!

**Comment by trodrigues** [comment]
Also noticed this recently on a couple of broken builds, and it seems to be exactly what I suspected. Will report back if it happens again.

**Comment by focusaurus** [comment]
I'm seeing this happening and causing my semaphoreCI builds to fail. Recently happened for fresh superagent and bower releases on several of my repos. Chatted with npm support about it on twitter. Might need a bit longer delay.
