### ISSUE TITLE
release notes are missing

### ISSUE THREAD

**Issue by travi** [greenkeeperio/greenkeeper#603]
i've noticed over the last few days that the release notes are missing from at least most greenkeeper PRs, even when the release on github shows release notes. would something have changed recently to make these disappear?

**Comment by espy** [comment]
👍  Thanks Matt, we’re aware of the problem and are looking in to it, but we’re a bit understaffed this week for a number of reasons, so it’s taking a bit longer. I’ll be in touch!

**Comment by travi** [comment]
No worries. Not a blocker in any way. Only for awareness in case it slipped through unnoticed.

**Comment by Realtin** [comment]
I may have found the issue: https://github.com/greenkeeperio/greenkeeper/pull/611

**Comment by Realtin** [comment]
@travi I just deployed the fix. But a quick search on new Greenkeeper PRs revealed that it did not fix the issue :/

**Comment by Realtin** [comment]
We may have found a fix again: https://github.com/greenkeeperio/greenkeeper/pull/621

**Comment by espy** [comment]
Release notes are back! 

<img width="782" alt="bildschirmfoto 2018-02-21 um 16 11 56" src="https://user-images.githubusercontent.com/391124/36487775-00550000-1722-11e8-8673-8d9079cc4aba.png">

**Comment by travi** [comment]
awesome. thanks!
