### ISSUE TITLE
Use another convention : (extended) ESLint Convention ?

### ISSUE THREAD

**Issue by jy95** [greenkeeperio/greenkeeper#608]
Hello,

I would like to customize the message generated by greenkeeper by another convention : [ESLint Convention](https://www.npmjs.com/package/conventional-changelog-eslint) (instead of the ugly default Angular convention)

For example , this is a default message :

`chore(package): update conventional-changelog-eslint to version 1.0.0`

I would like to have this instead : 

`:wrench: Chore: Package.json: update conventional-changelog-eslint to version 1.0.0`

For example, it could be done like that:
```js
// package.json
{
   "greenkeeper": {
          "update-message" : ":wrench: Chore: Package.json: update [dependancy-name] to version [dependancy-version]"
    }
}
```

Thanks

**Comment by Arcanemagus** [comment]
See https://github.com/greenkeeperio/greenkeeper/issues/153.

I laid out an outline of a potential way to implement this in https://github.com/greenkeeperio/greenkeeper/issues/153#issuecomment-359144774 which hasn't recieved any comments _against_ it, so I might set aside some time to implement that if somebody doesn't beat me to it.

**Comment by jy95** [comment]
Thanks : semantic-release and its plugins (like the @semantic-release/git plugin [configurable message](https://github.com/semantic-release/git#message) ) allows to override default config. It could help you for this feature

**Comment by Arcanemagus** [comment]
Yep, one of the authors of `semantic-release` pointed that out [here](https://github.com/AtomLinter/Meta/issues/18#issuecomment-359221805) 😉.

**Comment by jy95** [comment]
For this feature, I think the best is to create a file like `lib/get-commitMessages.js` that returns the right message depending of the situation (the default will be their current message) and to replace string message by calling this helper ...

My advice : 
> When you want something, do it instead of hoping someone will do it for you XD

In your original issue, they removed the 'Will be implemented' label 6 months ago and nobody has worked for this, so feel free to do it ^^

**Comment by Realtin** [comment]
I like the idea! We have a bunch of Features lined up, that we are working on at the moment. So we will not get around to this any time soon. @Arcanemagus your comment https://github.com/greenkeeperio/greenkeeper/issues/153#issuecomment-359144774 lines out the effort perfectly, thank you for that!

You are welcome to give this a try if you want. I recently added [Development Setup instructions](https://github.com/greenkeeperio/greenkeeper/blob/master/CONTRIBUTING.md#development-setup) so I hope setting up the project should be possible now (there was this one not obvious step about adding a Private Key to the env file..)

**Comment by jy95** [comment]
thanks @Realtin : @Arcanemagus has done his PR but got the "Tests fail with: incorrect header check" case on travis ^^

I wonder if it is not possible to set a default PRIVATE_KEY like explained on [travis](https://docs.travis-ci.com/user/environment-variables/#Defining-public-variables-in-.travis.yml) and 

> If you define a variable with the same name in .travis.yml and in the Repository Settings, the one in .travis.yml takes precedence. If you define a variable in .travis.yml as both [encrypted ](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) and [unencrypted](https://docs.travis-ci.com/user/environment-variables/#Defining-public-variables-in-.travis.yml) , the one defined later in the file takes precedence.

**Comment by Realtin** [comment]
@jy95 We have the PRIVATE_KEY set in the Repository Settings on Travis. I don't get why that wouldn't work for third-party PRs. I can set it in the travis.yml as well, maybe it helps..

**Comment by Realtin** [comment]
I get it now :D security reasons. But this Private key can be just a randomly generated one so it is not needed to be secure anyways so I'll 'unsecure' it

**Comment by jy95** [comment]
No problem : CI configuration can be tough something ^^
