### ISSUE TITLE
broken images on ToS page

### ISSUE THREAD

**Issue by zeke** [greenkeeperio/greenkeeper#623]
Good day, Greenkeepers! 💚 

Hey just saw some broken images on the footer of this page: 
https://mailchi.mp/ebfddc9880a9/were-updating-our-terms-of-service

<img width="679" alt="screen shot 2018-02-22 at 9 20 54 am" src="https://user-images.githubusercontent.com/2289/36553646-b69be24a-17b1-11e8-915f-6f9a056bdffd.png">

**Comment by espy** [comment]
Hiya, thanks for letting us know. 

That’s possibly down to either 
- Mailchimp, who host that particular page and the footer assets
- the CDN they’re using
- or maybe to an especially strict ad blocker you have running?

In any case, I’m afraid we have no control over this particular problem and would have to defer to Mailchimp.
