### ISSUE TITLE
Support for educational private teams

### ISSUE THREAD

**Issue by Aarbel** [greenkeeperio/greenkeeper#624]
@greenkeeperio-bot @Realtin @rmehner @espy 
Hi Greenkeeper teams ! 

I use many services for my educational teams (Github / Travis / GitKraken / Studio3T / AWS / Sendgrid / Sentry / Unreal). It's a great business strategy for tech services.

When will you provide this kind of access ?

Thanks a lot !

**Comment by janl** [comment]
Hi @Aarbel,

As I’ve written in the Email a few weeks ago already, we are working through the details with GitHub at the moment. Please be patient until we have found out more.

Best
Jan
—

**Comment by Aarbel** [comment]
thanks janl ;)
