### ISSUE TITLE
Greenkeeper keeps alerting me of new semver major releases though I've chosen to stay on a lower version

### ISSUE THREAD

**Issue by jdalton** [greenkeeperio/greenkeeper#634]
I'm running into an issue where greenkeeper keeps opening PRs to upgrade me to webpack v4 even after I've closed previous ones and my semver range is ^3. See https://github.com/standard-things/esm/pull/305.

**Comment by travi** [comment]
unfortunately, there isn't a completely clean way of handling this yet, but the most recent conversation related to it is in https://github.com/greenkeeperio/greenkeeper/issues/581

if you want to completely ignore a dependency, you can [ignore](https://greenkeeper.io/docs#ignoring-dependencies) it, but you need to remember to remove the ignore once you are ready to accept latest again.

**Comment by jdalton** [comment]
Ah thank you @travi!
