### ISSUE TITLE
Unable to `npm i -g greenkeeper@5.0.0`

### ISSUE THREAD

**Issue by bhovhannes** [greenkeeperio/greenkeeper#637]
Hi,

I am trying to install the latest greenkeeper (5.0.0) with the command `npm i -g greenkeeper`. Getting the following error:
```
npm i -g greenkeeper
npm ERR! path /Users/testuser/Development/nvm/versions/node/v6.9.1/lib/node_modules/greenkeeper/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/testuser/Development/nvm/versions/node/v6.9.1/lib/node_modules/greenkeeper/bin.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/testuser/.npm/_logs/2018-03-12T11_43_38_853Z-debug.log
```

However, `npm i -g greenkeeper@4.2.1` works fine.

Node v6.9.1,  NPM v4.6.1

**Comment by janl** [comment]
Heya, the Greenkeeper CLI version 5 is deprecated. Our Enterprise customers can still install version 4 for backwards compatibility reasons.

**Comment by bhovhannes** [comment]
In that case it will be nice to add a deprecation warning which users will see during installation of greenkeeper@5.0.0.
It is confusing to get an error during executing first step after installation of GK enterprise.
