### ISSUE TITLE
Repo not showing up

### ISSUE THREAD

**Issue by simlu** [greenkeeperio/greenkeeper#639]
Is there a problem with repos not synchronizing?

I've deleted and re-added the integration, but the link to the integration on the homepage still points to the old id and I get a 404. So something isn't updating?

**Comment by espy** [comment]
Hi @simlu! Was this on your personal account? I can see that your installation ID changed back when you opened this issue, did the link in the dashboard correct itself eventually? It may just have been a timing issue. 

In any case: you don’t have to rely on the link we provide in the accounts dashboard: on https://github.com/settings/installations, if you click on "configure", you should get to the interface you previously got a 404 for.

**Comment by simlu** [comment]
This eventually sorted itself out. I tried the next day and it worked. So issue can stay closed. Thanks!
