### ISSUE TITLE
Disable Pull Requests

### ISSUE THREAD

**Issue by malliapi** [greenkeeperio/greenkeeper#641]
Hi,

We run a project with forks and it doesnt make much sense for us for greenkeeper to open pull requests but issues are welcome. Is there any way to disable opening pull requests?

**Comment by espy** [comment]
Hi @malliapi, there currently isn’t an option for this, no. Just to clarify: would you want Greenkeeper to simply never send you PRs (which are only for out-of-range updates anyway), or notify you of out-of-range updates in issues instead? Also, Greenkeeper relies on initialising/resetting a repo with an initial pull request, is that also something that causes problems in your workflow, or is it only the regular PRs concerning out-of-range updates?

Thanks for getting in touch!
