### ISSUE TITLE
Logs: various issues/missing logs

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#676]
- [x] Misleading log message in `create-group-version-branch`: `database: found open PR for this dependency`, but the logged object is actually empty, and there are no open PRs.
- [ ] The job that creates the `An in-range update of […] is breaking your build` issue doesn’t have any logs
- [x] Inaccurate log: If there is no `greenkeeper.json` in the repo, the log message is: `Could not parse greenkeeper.json`, with the error `TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object`. If 404, should log `No greenkeeper.json found in repo`.
- [x] Inaccurate: `Fetched greenkeeper.json from GitHub` with empty array, when there is no greenkeeper.json in the repository
- [x] Uneccessary log: As a follow-up to the point above, the next log item is `Fetched greenkeeper.json from GitHub` with an empty object. Should not log at all if the previous fetch was a 404. 
- [x] Inaccurate: `starting to delete branches` when there are no branches to delete
- [x] Missing: in `create-initial-subgroup-branch`, it should be logged when no action needs to be taken (such as all dep satisfy semver)
- [x] Inaccurate: `updating existing greenkeeper config` should show the before and after version of the greenkeeper.json but shows the same, probably mutation problem.
- [ ] `worker could not be created` error on an archived repo should be a warn. Generally look at handling of archived repos (do we get a push for that?)
- [ ] `worker recieved no payload` sends along data that doesn’t help figuring out why it received no payload. In some cases, this is probably completely avoidable.

**Comment by janl** [comment]
@espy can we cl
