### ISSUE TITLE
Bug: A disabled repo receives no invalid greenkeeper.json issues, but should

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#678]
If a monorepo has no more groups or package files, it is disabled. If the user then configures the `greenkeeper.json` incorrectly to start it up again, no issue is opened. The job will detect the file is not valid JSON, but no issue will be opened.

An invalid `greenkeeper.json` triggers the error log at `/package/lib/get-files.js:111:31`, and this should open an issue but doesn’t, prooooobably because the repo is disabled.

**Comment by janl** [comment]
This is what I wanted to get addressed with (the as of yet incomplete) https://github.com/greenkeeperio/greenkeeper/pull/672

**Comment by espy** [comment]
This is actually handled by https://github.com/greenkeeperio/greenkeeper/pull/672
