### ISSUE TITLE
Bug `create-initial-subgroup-branch : success` does not create a PR

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#679]
⚠️ **Update**: this seems to be true of all repos, not just disabled ones. Nevertheless, the two checkboxes below remain relevant.

<summary>Original, wrong isssue text is in here:</summary>
<details>
A disabled repo that receives an update with a new group to its previously group-less `greenkeeper.json` will not receive an initial subgroup PR. This kinda makes sense, because the repo wasn’t enabled, but this push action on the `greenkeeper.json` does arguably imply that the user _wants_ to enable Greenkeeper on the repo.
</details>

## Todos:
- [ ] The initial subgroup PR should be opened _even if the repo is disabled_
- [ ] The repo should enable itself **when an initial-subgroup-pr is merged and it was previously disabled**. However, this can incur costs, so the PR needs to indicate this on private repos, just as a initial PR does.

**Comment by janl** [comment]
This is what I wanted to get addressed with (the as of yet incomplete) https://github.com/greenkeeperio/greenkeeper/pull/672

**Comment by Realtin** [comment]
current behaviour:  branch is created and after the CI status comes in it gets deleted.

I suspect it could be an unhandled case in `github-event/status.js`

**Comment by janl** [comment]
Fixing this issue should also fix that issue: https://github.com/greenkeeperio/greenkeeper/issues/684
