### ISSUE TITLE
Bug: don’t update greenkeeper.json if the only difference is whitespace

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#680]
Could be considered a bug or a feature, really. 

![bildschirmfoto 2018-04-10 um 15 16 48](https://user-images.githubusercontent.com/391124/38559052-45c354b8-3cd2-11e8-97dd-9c38290c5d68.png)

**Comment by janl** [comment]
feature. nobody should do this by hand :)

**Comment by espy** [comment]
Haha :D
