### ISSUE TITLE
Bug: open compare for correct base on a forked repo

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#682]
Currently, when you click the `Update to this version instead 🚀` link in a comment in a out-of-range issue, it takes you to this page:

![bildschirmfoto 2018-04-10 um 16 00 17](https://user-images.githubusercontent.com/391124/38561537-9656d91c-3cd8-11e8-876c-65237eb2de07.png)

which compares the greenkeeper branch to the fork’s upstream origin. What we want is this:

![bildschirmfoto 2018-04-10 um 16 00 39](https://user-images.githubusercontent.com/391124/38561573-aa0e8f86-3cd8-11e8-94d7-931a99478844.png)

At least I think that’s what we want.

**Comment by Realtin** [comment]
that's how I accidentally opened a PR at vue/vue-cli  yesterday 🙈 
But I think it is just GitHubs UI fault.

**Comment by espy** [comment]
Would be cool if we had control over this :)

**Comment by espy** [comment]
We currently do:
https://github.com/neighbourhoodie/gk-test-ember-on-rails-backend-frontend/compare/greenkeeper%2Fui%2Fember-cli-3.1.0?expand=1

…which automatically redirects to:
https://github.com/tutsplus/create-a-full-stack-rails-and-ember-app/compare/master...neighbourhoodie:greenkeeper/ui/ember-cli-3.1.0?expand=1

correct would be:
https://github.com/neighbourhoodie/gk-test-ember-on-rails-backend-frontend/compare/master...neighbourhoodie:greenkeeper/ui/ember-cli-3.1.0?expand=1

Seems as if the URL syntax for pull request/compare pages has changed completely at some point.

We have: 
```
${env.GITHUB_URL}/${owner}/${repo}/compare/${encodeURIComponent(newBranch)}?expand=1
```
We need something like:
```
${env.GITHUB_URL}/${owner}/${repo}/compare/${defaultBranch}…${owner}:${encodeURIComponent(newBranch)}?expand=1
```

Also need to check other parts of the code (pinning message?) for similar URLs.

**Comment by espy** [comment]
The same URL is used in the `Build failing` link here:

![bildschirmfoto 2018-04-11 um 15 33 16](https://user-images.githubusercontent.com/391124/38619994-b9bc6e06-3d9d-11e8-8711-99aec4b78d17.png)

**Comment by espy** [comment]
This is helpful: (from https://gist.github.com/nevik/5689882)

GitHub's compare view is available at:

    https://github.com/$USER/$REPO/compare/$REV_A...$REV_B

Naturally, `$USER` and `$REPO` are the owner (user/organization) and repository names, respectively.

`$REV{A,B}` are the two sides of the compare view; they can either be a *ref* in `$USER`'s repository, i.e. the name of a branch, tag or a commit SHA, or it can be a *ref* in `$OWNER`'s fork of the repository by using the format `$OWNER:$REF`.

You can get a diff or patch for the result of the compare view by appending `.diff` or `.patch` to the URL, respectively.

---

**Examples:**

[`https://github.com/octocat/Spoon-Knife/compare/ed12290ba...master`](https://github.com/octocat/Spoon-Knife/compare/ed12290ba...master)  
*Default usage is pretty straight-forward.*

`https://github.com/SomeUserName/Spoon-Knife/compare/master...ForkerChamp:topic/awesome-feature`  
*Branchname is `topic/awesome-feature` in `ForkerChamp`'s repo.*

**Comment by espy** [comment]
![bildschirmfoto 2018-04-13 um 16 09 15](https://user-images.githubusercontent.com/391124/38739374-0a6758dc-3f35-11e8-9a74-286a268f4b36.png)

Fixed!
