### ISSUE TITLE
Unable to add private repo as single payment after using github marketplace

### ISSUE THREAD

**Issue by LiamDotPro** [greenkeeperio/greenkeeper#721]
I recently added greenkeeper to my private project and initally when I signed up through greenkeeper I could input my credit details and then enabled greenkeeper on a per project basis for a reasonable fee. Though not I've enabled greenkeeper through github marketplace that option has disappeared from my greenkeeper account and instead I can only activate it for my open source projects and I'm limited to upgrading to a much more expensive teams plan that I don't need.

**Comment by espy** [comment]
Hi there, sorry about that, I’ve set your account to use the non-GitHub plans. If you reload the [billing page in the account dashboard](https://account.greenkeeper.io/account/LiamDotPro#plans-and-billing), you should be able to select the old plan now. 

Hope I could help!
