### ISSUE TITLE
Greenkeeper commented instead of opening a new PR

### ISSUE THREAD

**Issue by zeke** [greenkeeperio/greenkeeper#732]
I merged this PR two days ago. Today, greenkeeper commented on the PR instead of opening a new PR. This seems like a bug, right 🐞 

https://github.com/nice-registry/ghub.io/pull/66#issuecomment-384782718

Thanks for all your hard work, BTW. 💛

**Comment by espy** [comment]
Hi Zeke!
Thanks for getting in touch, and thanks for the kind words, that means a lot 💚 

I just had a look at the logs, and it seems as if a push event from GitHub didn’t make it to our servers: it never got the message that you merged the PR. This is super rare, but we _could_ handle this kind of thing better, so thanks for point it out 👍 

Sorry for the confusion, and have a good weekend 👋

**Comment by zeke** [comment]
👍
