### ISSUE TITLE
Greenkeeper ignoring `greenkeeper.ignore` field.

### ISSUE THREAD

**Issue by SirWindfield** [greenkeeperio/greenkeeper#733]
I want to prevent a certain package from getting updated `@semantic-release/git`. But greenkeeper, for some reasons, does not respect my `package.json` configuration. 
[Here](https://github.com/SirWindfield/vscode-firebase-configuration-schema-plugin) is my repository. The PR is still up. Greenkeeper did update the package though, does the bot not respect scoped packages?

**Comment by espy** [comment]
Thanks for getting in touch, that was a good one 👍 Sorry for the inconvenience though. The fix is already deployed to production.

The trouble wasn’t related to the scoped package, by the way, it was a problem with the initial branch creation in general.

Have a good weekend! 👋 🌴
