### ISSUE TITLE
Many failed tests when run "npm test"

### ISSUE THREAD

**Issue by tiendq** [greenkeeperio/greenkeeper#747]
I just forked and followed exactly this guide [Contributing](https://github.com/greenkeeperio/greenkeeper/blob/master/CONTRIBUTING.md). All steps were done successfully but running test the first time result in many failed tests.

1. Fork: Ok
2. `npm install`: Ok
3. Install Docker: Ok (Docker CE for Mac 18.03.1-ce)
4. CouchDB `docker pull apache/couchdb:2.1.1`: Ok
5. Fake private key `(echo -n "PRIVATE_KEY="; openssl genrsa 2>/dev/null | gzip | base64) >> .env`: Ok
6. `npm test`: Failed

```bash
Test Suites: 2 failed, 54 passed, 56 total
Tests:       32 failed, 284 passed, 316 total
Snapshots:   0 total
```

There were many errors but I have noticed most of them related to `package.json`, `github-event`, `monorepo`, 

Some errors (there were many, if you want to see them all, let me know so I'll copy all console log).

```bash
github-event push › package.json added/modified for a not enabled repo (333)

github-event push › monorepo: subdirectory package.json, which is not listed in the config, was modified (555)

github-event push: monorepo › monorepo: new greenkeeper.json is added with 2 groups (3462)

github-event push: monorepo › monorepo: greenkeeper.json modified by user and it now has invalid groupname (mgm1)

/Users/tiendq/Github/greenkeeper/test/jobs/update-payments.js: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: console
```

macOS 10.12.6
NodeJS 10.0.0

**Comment by janl** [comment]
can you try running this in Node 8 instead?
