### ISSUE TITLE
Greenkeeper creates comment on closed pull request instead of creating a new one

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#752]
see https://github.com/octokit/rest.js/pull/854#issuecomment-387865736

Note that the version of `@octokit/routes` is pinned, maybe that makes a difference? I have not seen this happening before

**Comment by finnp** [comment]
I suspect that there's a database inconsistency, where the PR is still marked as open in the database: https://github.com/greenkeeperio/greenkeeper/blob/852ce6e6e52e6552e9f323015d60780118de788d/jobs/create-version-branch.js#L141-L148

**Comment by travi** [comment]
i've seen several of these again lately too. the team has been able to get the database back in the correct state when i reach out, but it seems like the PR could be checked before commenting to ensure that it hasn't already been closed

**Comment by hawkrives** [comment]
I'm still seeing Greenkeeper comment on closed PRs – namely https://github.com/StoDevX/AAO-React-Native/pull/2565.

Is there anything I can do to help with this? Love Greenkeeper, btw!

**Comment by oterral** [comment]
Same issue https://github.com/geoadmin/mf-geoadmin3/pull/4315 
Any news about this ?

**Comment by espy** [comment]
Hi @oterral /everyone, sorry for the delay, we’ve just finished the work, but Travis is [having issues](https://www.traviscistatus.com/) and we can't run our builds until they resolve this. Once that‘s done we manually test on staging and then it'll be live. So this _miiight_ get shipped today, depending on that Travis outage.
