### ISSUE TITLE
repo selection page for greenkeeping

### ISSUE THREAD

**Issue by dbkaplun** [greenkeeperio/greenkeeper#80]
Would be nice if I could have a list of my repos for which I could choose to turn greenkeeping on or off, and all of the ones I choose would be greenkept in one fell swoop. Thanks!

**Comment by boennemann** [comment]
Hey @dbkaplun,

thanks for your feedback. A web application with such functionality is on our list.
We'll let you know once that's out there.

Best,
Stephan

**Comment by finnp** [comment]
Hey @dbkaplun,

our web app is now online. It's still beta, but please give it a go https://app.greenkeeper.io/. Any feedback is very appreciated.

Best,
Finn
