### ISSUE TITLE
GK create new branches but does not create PR

### ISSUE THREAD

**Issue by albert-olive** [greenkeeperio/greenkeeper#810]
Hi,

I don't know why but greenkeeper is creating new branches to update versions but it doesn't create a new PR. I have tried to create manually one with the branch that has created and the bot has closed that PR and deleted the branch.

Any thoughts?

**Comment by janl** [comment]
https://greenkeeper.io/faq.html#branch-deletions

**Comment by albert-olive** [comment]
But why those branches doesn't get merged? Thanks
