### ISSUE TITLE
Greenkeeper failing to create any PRs

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#816]
It seems that Greenkeeper has decided that it can no longer find the [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) repository: [![Greenkeeper badge](https://badges.greenkeeper.io/AtomLinter/linter-stylelint.svg)](https://greenkeeper.io/)

The last update Greenkeeper did here was https://github.com/AtomLinter/linter-stylelint/commit/7d2045993df38dc2b51f001e948d865bde470ad5, on 2018-04-01.

I'm _guessing_ that this is related to https://github.com/greenkeeperio/greenkeeper/issues/506 and https://github.com/greenkeeperio/greenkeeper/issues/529, but as there are dependency updates that are outside the allowed (pinned) range, it's not the same issue.

Greenkeeper is enabled as an integration at the organization level, so this _should_ be working. I have no idea if there are additional repositories that are affected since I'm not sure if the other `Not found` repositories in [the list](https://github.com/AtomLinter/Meta/wiki/Packages-Information) are due to this bug, or https://github.com/greenkeeperio/greenkeeper/issues/509 where they just never were activated in the first place.

If there is any additional information I can provide just let me know.

**Comment by Realtin** [comment]
I don't know exactly what happened but `AtomLinter/linter-stylelint` (as well as all of the other `Not found` repos in the list)  is missing in our database. Because of that I can't reset it, unfortunately. The only way is to remove the repo(s) from the Greenkeeper Settings inside Github, Save, and adding the repo(s) it again.

**Comment by Arcanemagus** [comment]
> I don't know exactly what happened but `AtomLinter/linter-stylelint` (as well as all of the other `Not found` repos in the list) is missing in our database.

Interesting, at least that explains why it hasn't been getting updates.

> The only way is to remove the repo(s) from the Greenkeeper Settings inside Github, Save, and adding the repo(s) it again.

That's... rather difficult as there are 91 repositories in this organization. It's currently set to "All repositories" and it seems if I wanted to change that I would have to manually add each one to the list, and skip the "missing" ones.

![image](https://user-images.githubusercontent.com/427137/41671727-cf2a37ea-746c-11e8-829d-8fe1b0203ccb.png)

Does it make sense to implement some sort of routine check for new (or mysteriously missing) repositories in organizations that are configured like that? I'd imagine that would solve #509 as well since the newly transferred repositories would then get added.

**Comment by Realtin** [comment]
I added the repositories to our database by hand and then triggered the reset. They should all have a Greenkeeper Initial PR now!

We don't recommend using the 'All repositories' option because it often causes problems, especially with newly added repositories. We should probably highlight that more!

**Comment by Arcanemagus** [comment]
> I added the repositories to our database by hand and then triggered the reset.

Thanks!

> We don't recommend using the 'All repositories' option because it often causes problems, especially with newly added repositories. We should probably highlight that more!

Interesting, I was trying to avoid going the "enable for individual repos" route, but it certainly seems like that is necessary here. It looks like you already knew about the issue though 😉.
