### ISSUE TITLE
Remove 🚀emoji in Github Pull Request title

### ISSUE THREAD

**Issue by xplorld** [greenkeeperio/greenkeeper#834]
🚀 in Pull Request title will go into the merging commit message, which breaks Continuous Deployment in AWS services. Please provide an option to remove this non-ASCII character, or even options to customize the PR title.

**Comment by janl** [comment]
Closing this in favour of https://github.com/greenkeeperio/greenkeeper/issues/343

**Comment by Realtin** [comment]
PR Titles are now customisable: https://greenkeeper.io/docs.html#custom-pr-titles
