### ISSUE TITLE
Bug: rolling over the logs db to a new month doesn't work

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#838]
We [implemented this](https://github.com/greenkeeperio/greenkeeper/blob/master/lib/dbs.js#L52-L55) a while ago, but it just failed going from June to July, so something’s not right. It‘ll sort itself out when we restart the service, but we specifically added this so we’d no longer rely on restarts for the rollover.

**Comment by janl** [comment]
Closing in favour of https://github.com/greenkeeperio/greenkeeper/pull/846
