### ISSUE TITLE
Help - ERR! enable Couldn’t enable a project with this slug.

### ISSUE THREAD

**Issue by ericelliott** [greenkeeperio/greenkeeper#84]
```sh
$ greenkeeper enable
🌴  info enable The GitHub slug is: keystonejs/keystone
🌴  ERR! enable Couldn’t enable a project with this slug.
🌴  ERR! enable If you want to try your free private repo make sure to grant the necessary rights by running $ greenkeeper login --force --private
🌴  ERR! enable You have to have a plan for more than one private repo. To verify run $ greenkeeper whoami
🌴  ERR! enable If you have just recently created this repo try running $ greenkeeper sync
🌴  ERR! enable You need admin access to a repo to enable it.
🌴  ERR! enable If you think this error really shouldn’t appear let us look into it with $ greenkeeper support
```

The FAQ says something about a changed URL, but it looks like it's trying to enable the correct slug [for Keystone](https://github.com/keystonejs/keystone).

What am I missing?

**Comment by JedWatson** [comment]
This may be relevant: from memory I originally created the KeystoneJS repo under JedWatson/keystone

**Comment by ericelliott** [comment]
Interesting. But I don't see anything that refers that that slug in package.json, and Greenkeeper seems to know the correct current slug...

**Comment by christophwitzko** [comment]
Hi @ericelliott,
Hi @JedWatson,

thank you for trying out Greenkeeper. :+1: :blush: 
It looks like Greenkeeper has no access to the `keystonejs ` organization on GitHub.
Can you revoke access for the Greenkeeper application [here](https://github.com/settings/applications), then run `greenkeeper login --force` and grant access to the `keystonejs` organization.
After that `greenkeeper enable` should just work. (it gets the correct slug from the git remote named `origin` :wink:)

Have a great day,
Christoph

**Comment by ericelliott** [comment]
Looks like I don't have access to grant access to Greenkeeper @JedWatson =)

**Comment by ericelliott** [comment]
Thank you for your help @christophwitzko!

**Comment by JedWatson** [comment]
Thanks @christophwitzko! All good, I believe it's working now :)

**Comment by christophwitzko** [comment]
:ok_hand: :relaxed:
