### ISSUE TITLE
RC versions in range not getting updated

### ISSUE THREAD

**Issue by meltedspark** [greenkeeperio/greenkeeper#841]
According to [greenkeeper's documentation](https://greenkeeper.io/docs.html#greenkeeper-step-by-step) it should either update the dependency automatically (if the tests pass) or create an issue.  
It also suggests using [semver calculator](https://semver.npmjs.com/) to see which versions are within range.  
In my [project ](https://github.com/meltedspark/angular-cli-builders) I use `@angular-devkit/build-angular` version `0.7.0-rc.0` and I would expect it to be updated to the `0.7.0-rc.1` version that was published two days ago.  
Although semver calculator says that my dependency (`^0.7.0-rc.0`) is within the range, greenkeeper won't update it.

**Comment by janl** [comment]
Yes thanks, we didn’t realise we had that as a feature, heh 🤣 . We’ll look at restoring the existing behaviour while also avoiding the pre-release snafu protection we implemented. We apologise for the regression!

**Comment by janl** [comment]
This is live now.

**Comment by Realtin** [comment]
@meltedspark Greenkeeper still ignores every npm release that isn't `latest`. 
But if this release has a pre-release "syntax" e.g. `0.7.0-rc.1` or `7.0.0-beta.55` AND in your package.json the version for that dependency also has a pre-release syntax then greenkeeper will assume that you are cool with pre-releases and updates. 
If your package.json has a non-pre-release version defined (`7.0.0`) then Greenkeeper will not send you the update.

**Comment by meltedspark** [comment]
But in terms of pull requests, if I do have a pre-release version in package.json **and** greenkeeper updates to a new pre-release version **and** the tests pass - will it create a pull request or not?

**Comment by Realtin** [comment]
yes, if it is out-of-range. And in the pre-release cases it will only be out of range if you have the version pinned -> `"dep": "0.7.0-rc.1"`   so don't use `^` or `~`.
