### ISSUE TITLE
Greenkeeper support email is unavailable

### ISSUE THREAD

**Issue by ismay** [greenkeeperio/greenkeeper#847]
I've just emailed greenkeeper support on support@greenkeeper.io, as I'm encountering an issue described in the FAQ (https://greenkeeper.io/faq.html#renamed-repo) which recommends to email support with a reset request.

I immediately got an auto-reply from a greenkeeper member (Jan) with the message that he's away on holiday until the 30th, and the recommendation that I email support@greenkeeper.io. Which I just did.

So it seems that something's going wrong with your support email routing, as I assume someone else is handling support in his absence. So I'm opening this issue to let you know that support@greenkeeper.io sends out these autoresponder emails, but at the same time it recommends to contact support, which is a bit confusing.

**Comment by janl** [comment]
Sorry about the autoresponder, it's a mail setup thing on my personal account. The support team has gotten your email and will handle things shortly. /me goes back on vaca

**Comment by ismay** [comment]
No problem, thanks for the quick reply and happy holidays!
