### ISSUE TITLE
Consider use greenkeeper slash instead of hyphen in branch name

### ISSUE THREAD

**Issue by louy2** [greenkeeperio/greenkeeper#85]
I am using [erikras/react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) and greenkeeper branches are filling the sidepane of my SourceTree. If the branches are of the format `greenkeeper/xxx` then SourceTree can group them into a folder and fold them. 

Downside: if the repo that wants to use greenkeeper already has a branch named `greenkeeper` this would fail.

**Comment by vdh** [comment]
I'd also prefer this format for branch names, it would work well alongside existing branch organisation that already uses slashes, like git flow.

**Comment by christophwitzko** [comment]
Hi @louy2, 
Hi @vdh,

to change the branch prefix you can add `"greenkeeper": {"branchPrefix": "greenkeeper/"}` to your `package.json`.

Have a great day,
Christoph
