### ISSUE TITLE
502 Bad Gateway on login

### ISSUE THREAD

**Issue by stdavis** [greenkeeperio/greenkeeper#87]
I get this
![image](https://cloud.githubusercontent.com/assets/1326248/11657599/140ce022-9d7b-11e5-82f4-ee9b2f9e10b7.png)

When I run `greenkeeper login`.

**Comment by boennemann** [comment]
Hey @stdavis,

thanks for the report. Small hiccup with the service, can you retry now?

Best,
Stephan

**Comment by stdavis** [comment]
Working now. Thanks for the quick response!
