### ISSUE TITLE
Updating enzyme-adapter-react-16 version from 1.1.1 to 1.5.0

### ISSUE THREAD

**Issue by woahitsjc** [greenkeeperio/greenkeeper#886]
The latest version of enzyme-adapter-react-16 currently is 1.2.0. Though I cannot find any version for 1.5.0. I have a branch that is trying to do a monorepo update and the build is failing with an error: ```No matching version found for enzyme-adapter-react-16@^1.5.0```

Anyone having problems with this?

**Comment by espy** [comment]
This has been resolved, monorepo releases will have the correct info everywhere now 🌴 🤖
