### ISSUE TITLE
Greenkeeper bot drunk or out of his mind, updates a pull request 6 times with years old versions

### ISSUE THREAD

**Issue by nukeop** [greenkeeperio/greenkeeper#892]
Here's the problematic pull request:
https://github.com/nukeop/nuclear/pull/100

It says version 1.6.0 came out, but adds 3.4.4, then keeps mentioning all kinds of years old versions and updating package.json for several hours.

https://www.npmjs.com/package/enzyme
According to this link, Enzyme was updated only once yesterday.

**Comment by espy** [comment]
Hi there, thanks for reporting this! Needless to say, that shouldn’t have happened, sorry for the confusion. We’re on it!

**Comment by espy** [comment]
This is resolved, just forgot to close the issue. Monorepo release infos are now displayed correctly 👍 Thanks for your patience.

**Comment by nukeop** [comment]
Great, thanks for a fast reaction.
