### ISSUE TITLE
"Action required: Greenkeeper could not be activated 🚨" issue raised, possibly in error?

### ISSUE THREAD

**Issue by jameswilddev** [greenkeeperio/greenkeeper#893]
After installing Greenkeeper, it [created a pull request](https://github.com/jameswilddev/vnhtml/pull/14) to complete its configuration.  A CI build ran and completed successfully, and a build status was set on the commit in the pull request.  But then, an [issue was raised](https://github.com/jameswilddev/vnhtml/issues/13) saying that CI builds are not running, or not setting a status against the commit.

It looks like everything turned out OK in the end, and Greenkeeper is showing as enabled.  Possibly Travis took a little long to set a status or something?

Anyway, great product, thanks!

**Comment by espy** [comment]
Hi James, thanks for getting in touch and sorry for the delay. I know you’ve switched away from Greenkeeper in the meantime, but anyway: Yes, that sounds like a timing issue. Greenkeeper waits for half an hour for the first CI run to complete and then opens the issue you saw, sometimes the status and the issue just miss each other.
