### ISSUE TITLE
greenkeeper fails to update babel7 (monorepo packages) properly

### ISSUE THREAD

**Issue by wolfy1339** [greenkeeperio/greenkeeper#895]
So, greenkeeper opened up a PR as usual, but this time it grouped updates together. Not a problem, i actually wanted this feature myself.
Problem is, it failed to update all packages under the `@babel\` scope, and when it does, it doesn't update them all to the proper version indicated in the branch name. Ref: wolfy1339/m8tro-bootstrap#59
If it's going to miss those updates, then it's better to have the old functionality of one PR per dependency.

I really hope you guys can get this fixed soon. Thanks for making this tool.

**Comment by espy** [comment]
Hi @wolfy1339, thanks for getting in touch and sorry for the problem. At first glance this looks a lot like the issue described in #894, which I’m working on fixing today, hope to get this sorted as soon as we can.

**Comment by wolfy1339** [comment]
This seems to be working now with the `7.0.0` release of babel
