### ISSUE TITLE
Greenkeeper doesn't update Greenkeeper-lockfile

### ISSUE THREAD

**Issue by elwayman02** [greenkeeperio/greenkeeper#906]
As far as I can tell, Greenkeeper does not track updates to the Greenkeeper-lockfile package, even when it's added to package.json as a devDependency. This causes the lockfile features to fall way out of date as a result.

**Comment by travi** [comment]
recent `greenkeeper-lockfile` versions are being published to the `next` channel. greenkeeper currently only opens PRs for publishes to the `latest` channel, but there are some open issues suggesting support for other channels. i [can confirm](https://github.com/travi/project-scaffolder/pull/42) that PRs were sent for the latest version published to the `latest` channel.

does this align with the behavior that you are seeing?

**Comment by janl** [comment]
Confirming what @travi said :)

Please reopen if anything is different.

Also https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0
