### ISSUE TITLE
Badge not working

### ISSUE THREAD

**Issue by Apidcloud** [greenkeeperio/greenkeeper#917]
Good afternoon!

I have enabled Greenkeeper, got the initial PR, and merged it with no problems. In that PR, it added a badge to the README, which doesn't seem to be working:
[![Greenkeeper badge](https://badges.greenkeeper.io/scarlettgamestudio/scarlett-framework-2.svg)](https://greenkeeper.io/)

What could be the problem? I have noticed that the project isn't showing in the organisation account greenkeeper dashboard (at greenkeeper.io) for some reason.

Thanks!

**Comment by janl** [comment]
Thanks for the heads up, we’ll investigate.

**Comment by janl** [comment]
fixed! :)
