### ISSUE TITLE
Feature request: Update node/npm version in package.json when new version is released

### ISSUE THREAD

**Issue by jbuck** [greenkeeperio/greenkeeper#93]
Hi there! Greenkeeper is awesome and I love how much easier it makes my life. One feature that I'd like to have is if Greenkeeper could update the `engines.node` and or `engines.npm` key when a new release of node or npm came out.

Thanks, and keep up the great work!

**Comment by boennemann** [comment]
Hey @jbuck,

thanks for writing. This is something we've been thinking about from the beginning and we'd like to add this feature to Greenkeeper. Unfortunately it's not yet on top of our priorities, but we want to make it work in the future.

Best,
Stephan

**Comment by janl** [comment]
Closing in favour of #710
