### ISSUE TITLE
Greenkeeper opening duplicate branches

### ISSUE THREAD

**Issue by wolfy1339** [greenkeeperio/greenkeeper#952]
I've recently come across on one of my repos, greenkeeper creates a new branch identical to one already created.
It's trying to update the `babel7` monorepo deps from `7.1.0` to `7.1.2` again in the new branch.
Related PR (direct link to greenkeeper's coment trying to do the same update): https://github.com/wolfy1339/m8tro-bootstrap/pull/64#issuecomment-429095240

**Comment by wolfy1339** [comment]
Ping. This is happening in another repo of mine.
https://github.com/hellomouse/GNS

**Comment by hulkoba** [comment]
Should be solved in #978
