### ISSUE TITLE
Missing PRs

### ISSUE THREAD

**Issue by brainsiq** [greenkeeperio/greenkeeper#97]
I noticed some greenkeeper branches in my repo that have triggered CI builds, however no pull requests have been raised. I have had previous pull requests from greenkeeper on this repo.

https://github.com/brainsiq/hapi-boom-decorators

**Comment by lukaselmer** [comment]
+1

**Comment by ltegman** [comment]
I've been noticing the same thing on https://github.com/FreeCodeCamp/FreeCodeCamp

**Comment by BerkeleyTrue** [comment]
Unless there is a Semvar change that is without the range within your defined range, it opens the branches to detect CI failures. If test fail then it opens a PR so others know this Semver change that is within your Semvar ranges actually breaks the build and you must take action to ensure your app/library keeps running smoothly on new installs.

**Comment by jonathanong** [comment]
I would like every branch made by Greenkeeper to open a new PR (even if still covered by the current semver range), otherwise I have no notifications. I also want all my semver ranges to be up to date. Writing a comment in the commit might be okay, but a little more annoying. I don't mind if it were an option.

**Comment by brainsiq** [comment]
@BerkeleyTrue thanks. I didn't know that was the Greenkeeper workflow. That makes sense if you can rely on the next npm install to automatically update the dependency, but like @jonathanong I was hoping it'd raise a PR on every update because my dependencies are shrink-wrapped, which is covered by another issue #96
