### ISSUE TITLE
Auto-generated greenkeeper.json for monorepo includes invalid paths

### ISSUE THREAD

**Issue by corhere** [greenkeeperio/greenkeeper#970]
The initial PR for a monorepo included a file named `package.json.d.ts` to the packages list in `greenkeeper.json`. Once the PR was merged, Greenkeeper followed up by complaining that the `greenkeeper.json` _it created_ was invalid! I would expect Greenkeeper to only include valid paths in the `greenkeeper.json` it creates.

Offending commit: https://github.com/Fitbit/developer-bridge/commit/5675d017383eff6d3631db8a4b2e3b9baff607b2
Follow-up issue: https://github.com/Fitbit/developer-bridge/issues/14

**Comment by Realtin** [comment]
This should be fixed now: https://github.com/greenkeeperio/greenkeeper/pull/971
We will deploy this shortly.
