### ISSUE TITLE
Suggestion to use valid greenkeeper.json is not valid json.

### ISSUE THREAD

**Issue by richardson-trevor** [greenkeeperio/greenkeeper#973]
I recently had a greenkeeper.json file that had syntax errors. We got a notification on our repo that a bad greenkeeper.json file was detected, which was excellent 👏 , but the example suggested was not written in valid json. Here was the notification:
<img width="782" alt="rule-evaluator 2018-10-25 09-15-16" src="https://user-images.githubusercontent.com/2788272/47507062-101df600-d837-11e8-9059-9ec8bd640328.png">

**Comment by espy** [comment]
Haha, oh dear, thanks 🙈 Excellent point, we’ll get on it!
