### ISSUE TITLE
RFI prevent certain PRs to be opened when another one already includes the update

### ISSUE THREAD

**Issue by plozachm** [greenkeeperio/greenkeeper#987]
Hi,
I was wondering if there was a way to prevent greenkeeper bot from opening a PR  when there is another PR opened with this packaged already updated to the right version (any other PR).
Cheers,

**Comment by espy** [comment]
Hi there,
Greenkeeper only opens one PR per dependency and then keeps that PR up to date with comments. At least that’s what it should do, I’m not entirely sure what’s going on in your case. Could you link to an example if you have a publicly accessible one, or contact support@greenkeeper.io if it’s private, then I can look at the logs and check what’s up. 

Thanks in advance!

**Comment by plozachm** [comment]
I was thinking that other open PRs (not by greenkeeper) in the project could already have the upgraded dependency, but if greenkeeper closes its PR once the other has been merged it is ok. Thanks for your input.
