### ISSUE TITLE
Problems with vue

### ISSUE THREAD

**Issue by Stanzilla** [greenkeeperio/greenkeeper#995]
Some parts of vue depend on each other, greenkeeper always tries to bump them separately which always fails, see https://github.com/WeakAuras/WeakAuras-Companion/issues/21

**Comment by travi** [comment]
i'm not a vue user, so i don't know its specific details, but would it be helpful to define the versions that need to change together, so that greenkeeper sends them in the same PR? if so, it might be worth sending a PR to https://github.com/greenkeeperio/monorepo-definitions

**Comment by Stanzilla** [comment]
Oh interesting, will take a look, thanks

**Comment by hulkoba** [comment]
I'm closing this because https://github.com/greenkeeperio/monorepo-definitions/pull/27 is merged now.
Thanks to @Stanzilla
